using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using PocketQuests.Domain.Catalogs;
using PocketQuests.Domain.Commands;
using PocketQuests.Domain.Models.Schedules;
using PocketQuests.Domain.Models.Skills;
using PocketQuests.Services.Commands.Mapping;
using PocketQuests.Services.Exports.Mapping;
using PocketQuests.Services.Projections.Mapping;
using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using QuestCommand = PocketQuests.Domain.Models.Quests.QuestCommand;

namespace PocketQuests.Tests.Api;

/// <summary>Checks endpoint discovery, the committed schema and compatible wire output.</summary>
public sealed class ApiContractTests
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web) { Converters = { new JsonStringEnumConverter() } };

    /// <summary>The document is generated by ASP.NET from the same registered handlers used by HTTP tests.</summary>
    /// <returns>Completion of the HTTP assertions.</returns>
    [Fact]
    public async Task EndpointOpenApiMatchesCommittedContract()
    {
        await using var host = new ApiApplicationFactory();
        using var client = host.CreateClient();
        var document = await client.GetFromJsonAsync<JsonObject>("/openapi/v1.json");
        Assert.NotNull(document);
        var paths = document["paths"]!.AsObject();
        var endpoints = host.Services.GetRequiredService<EndpointDataSource>().Endpoints.OfType<RouteEndpoint>()
            .Where(endpoint => endpoint.RoutePattern.RawText?.StartsWith("/api/", StringComparison.Ordinal) == true).ToArray();
        var actual = endpoints.SelectMany(endpoint => endpoint.Metadata.GetRequiredMetadata<HttpMethodMetadata>().HttpMethods
            .Select(method => method.ToLowerInvariant() + " " + endpoint.RoutePattern.RawText)).Order().ToArray();
        var declared = paths.SelectMany(path => path.Value!.AsObject().Select(operation => operation.Key + " " + path.Key)).Order().ToArray();
        Assert.Equal(actual, declared);
        Assert.All(paths.SelectMany(path => path.Value!.AsObject()), operation => Assert.NotNull(operation.Value!["security"]));
        Assert.NotNull(paths["/api/commands"]!["post"]!["requestBody"]);
        Assert.NotNull(paths["/api/commands"]!["post"]!["responses"]!["429"]);
        Assert.NotNull(paths["/api/export/{format}"]!["get"]!["responses"]!["200"]!["content"]!["application/zip"]);
        Assert.NotNull(document["components"]!["schemas"]!["CatalogResponse"]!["properties"]!["rules"]);
        var generated = document.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n";
        var output = Environment.GetEnvironmentVariable("POCKETQUESTS_OPENAPI_OUTPUT");
        if (!string.IsNullOrEmpty(output))
        {
            await File.WriteAllTextAsync(output, generated, new UTF8Encoding(false));
        }
        else
        {
            var expected = await File.ReadAllTextAsync(Path.Combine(RepositoryRoot(), "contracts", "pocketquests-v1.openapi.json"));
            Assert.True(JsonNode.DeepEquals(JsonNode.Parse(expected), document), "Endpoint OpenAPI drifted. Run scripts/Test-ApiContract.ps1 -Update and regenerate the client.");
        }
    }

    /// <summary>State and export JSON remain equivalent after explicitly mapping API-owned DTOs.</summary>
    /// <returns>Completion of the HTTP assertions.</returns>
    [Fact]
    public async Task StateAndExportPreserveWireValues()
    {
        await using var host = await ApiTestHost.Start();
        AssertJsonEqual(host.Store.State, host.Store.State.ToModel());
        AssertJsonEqual(host.Store.Snapshot(), host.Store.Snapshot().ToModel());
        var state = await host.Client.GetFromJsonAsync<JsonNode>("/api/state");
        Assert.True(JsonNode.DeepEquals(JsonSerializer.SerializeToNode(host.Store.State, Json), state));
        var export = await host.Client.GetAsync(new Uri("/api/export/json", UriKind.Relative));
        Assert.Equal(HttpStatusCode.OK, export.StatusCode);
        Assert.Equal("pocket-quests.json", export.Content.Headers.ContentDisposition?.FileNameStar);
        Assert.True(JsonNode.DeepEquals(JsonSerializer.SerializeToNode(host.Store.Snapshot(), Json), JsonNode.Parse(await export.Content.ReadAsStringAsync())));
        Assert.NotNull(state!["completionOutcome"]);
        Assert.NotNull(state["occurrences"]![0]!["occurrence"]!["quest"]!["baseXp"]);
    }

    /// <summary>Every command field, including nested terms and clock proofs, survives HTTP mapping.</summary>
    /// <returns>Completion of the HTTP assertions.</returns>
    [Fact]
    public async Task CommandDtoPreservesAllWireFields()
    {
        await using var host = await ApiTestHost.Start();
        var command = new QuestCommand(Guid.NewGuid(), QuestActions.Accept, Guid.NewGuid(), "quest", "2026-10-05", Guid.NewGuid(), Catalog.Quests[0], 2, "skill", Experience.Expert, ["c01"], "12:00", Guid.NewGuid(), "reward", Guid.NewGuid(), Cadence.Weeks, 2, "c01", true, 5, new(Guid.NewGuid(), Guid.NewGuid(), 3, 1200, ApiTestStore.At), "name", Catalog.Quests[1], "UTC", "Europe/London", true, true);
        AssertJsonEqual(command, command.ToModel().ToModel());
        using var content = new StringContent(JsonSerializer.Serialize(command, Json), Encoding.UTF8, "application/json");
        Assert.Equal(HttpStatusCode.OK, (await host.Client.PostAsync(new Uri("/api/commands", UriKind.Relative), content)).StatusCode);
        AssertJsonEqual(command, host.Store.LastCommand);
    }

    internal static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "global.json")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new InvalidOperationException("Repository root not found.");
    }

    private static void AssertJsonEqual<TLeft, TRight>(TLeft left, TRight right) =>
        Assert.True(JsonNode.DeepEquals(JsonSerializer.SerializeToNode(left, Json), JsonSerializer.SerializeToNode(right, Json)));
}
