-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[Category] (
    [Id] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Name] nvarchar(120) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CatalogVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [SortOrder] int NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_Category_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_Category_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_Category_SortOrder] UNIQUE ([SortOrder]),
    CONSTRAINT [CK_Category_SortOrder] CHECK ([SortOrder] >= 1),
    CONSTRAINT [CK_Category_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_Category_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_Category_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt])
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one of the ten canonical life categories. Classification: Public. History: reference; Retain stable codes indefinitely; source control owns reference history. Not erased with accounts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable public catalog code; preserve existing IDs and ordinal allocation tie-breaking.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current public catalog display name.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category', @level2type=N'COLUMN', @level2name=N'Name';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Version of the reviewed catalog that supplied this row.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category', @level2type=N'COLUMN', @level2name=N'CatalogVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive canonical display order; not an independently chosen progression priority.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category', @level2type=N'COLUMN', @level2name=N'SortOrder';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Category', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
