-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[Account] (
    [Id] uniqueidentifier NOT NULL,
    [IdentityUserId] varchar(30) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [TimeZoneId] varchar(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [IsOnboardingComplete] bit NOT NULL CONSTRAINT [DF_Account_IsOnboardingComplete] DEFAULT (0),
    [HasExpiryWarnings] bit NOT NULL CONSTRAINT [DF_Account_HasExpiryWarnings] DEFAULT (0),
    [IsAccountPaused] bit NOT NULL CONSTRAINT [DF_Account_IsAccountPaused] DEFAULT (0),
    [SelectedBadgeId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [SelectedBadgeKind] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT [DF_Account_SelectedBadgeKind] DEFAULT ('Badge'),
    [SelectedFrameId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [SelectedFrameKind] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT [DF_Account_SelectedFrameKind] DEFAULT ('Frame'),
    [LastRecordedAt] datetimeoffset(7) NOT NULL,
    [MutationVersion] bigint NOT NULL CONSTRAINT [DF_Account_MutationVersion] DEFAULT (0),
    [ProjectionVersion] bigint NOT NULL CONSTRAINT [DF_Account_ProjectionVersion] DEFAULT (0),
    [ProjectionAsOfAt] datetimeoffset(7) NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_Account_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_Account_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    [HasPendingReconciliation] bit NOT NULL CONSTRAINT [DF_Account_HasPendingReconciliation] DEFAULT (0),
    CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_Account_IdentityUserId] UNIQUE ([IdentityUserId]),
    CONSTRAINT [UQ_Account_Id_IdentityUserId] UNIQUE ([Id], [IdentityUserId]),
    CONSTRAINT [CK_Account_SelectedBadgeKind] CHECK ([SelectedBadgeKind] IN ('Badge')),
    CONSTRAINT [CK_Account_SelectedFrameKind] CHECK ([SelectedFrameKind] IN ('Frame')),
    CONSTRAINT [CK_Account_IdentityUserId] CHECK (DATALENGTH([IdentityUserId])=30 AND LEFT([IdentityUserId],4)='usr_' AND SUBSTRING([IdentityUserId],5,26) NOT LIKE '%[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]%' COLLATE Latin1_General_100_BIN2),
    CONSTRAINT [CK_Account_ProjectionVersion] CHECK ([MutationVersion]>=0 AND [ProjectionVersion]>=0 AND [ProjectionVersion]<=[MutationVersion]),
    CONSTRAINT [CK_Account_LastRecordedAtUtc] CHECK (DATEPART(TZOFFSET,[LastRecordedAt])=0),
    CONSTRAINT [CK_Account_ProjectionAsOfAtUtc] CHECK (DATEPART(TZOFFSET,[ProjectionAsOfAt])=0),
    CONSTRAINT [CK_Account_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_Account_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_Account_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_Account_ProfileReward_SelectedBadge] FOREIGN KEY ([SelectedBadgeId], [SelectedBadgeKind]) REFERENCES [pocketquests].[ProfileReward] ([Id], [KindCode]) ON DELETE NO ACTION,
    CONSTRAINT [FK_Account_ProfileReward_SelectedFrame] FOREIGN KEY ([SelectedFrameId], [SelectedFrameKind]) REFERENCES [pocketquests].[ProfileReward] ([Id], [KindCode]) ON DELETE NO ACTION
);
GO
-- Supports FK_Account_ProfileReward_SelectedBadge parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_Account_FK_ProfileReward_SelectedBadge] ON [pocketquests].[Account] ([SelectedBadgeId], [SelectedBadgeKind]);
GO
-- Supports FK_Account_ProfileReward_SelectedFrame parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_Account_FK_ProfileReward_SelectedFrame] ON [pocketquests].[Account] ([SelectedFrameId], [SelectedFrameKind]);
GO
-- Bounded maintenance selects the oldest eligible materialization clocks, excluding inactive lifecycle barriers, without scanning account payloads.
CREATE INDEX [IX_Account_ReconciliationClock] ON [pocketquests].[Account] ([ProjectionAsOfAt], [Id]) INCLUDE ([IdentityUserId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one personal Pocket Quests profile for a verified canonical Identity user. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canonical never-recycled usr_ identifier returned by HoneyDrunk.Identity, not a provider subject or email.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'IdentityUserId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Selected IANA timezone used for personal calendar calculations, not a UTC offset.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'TimeZoneId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether explicit product onboarding completed.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'IsOnboardingComplete';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether the account requested optional grouped expiry warnings; device OS permission is separate.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'HasExpiryWarnings';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current explicit all-category pause setting; effective intervals are stored separately.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'IsAccountPaused';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Selected badge code; null means no selected badge.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'SelectedBadgeId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Constant Badge discriminator for the typed reward FK.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'SelectedBadgeKind';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Selected frame code; null means no selected frame.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'SelectedFrameId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Constant Frame discriminator for the typed reward FK.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'SelectedFrameKind';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Fixed account logical-time high-water mark; never a future deadline. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'LastRecordedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Monotonic committed account mutation number; issued anchors retain this visibility version.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'MutationVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Mutation version fully reflected by the current materialized progress projection.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'ProjectionVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Clock instant through which time-driven projection state is reconciled. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'ProjectionAsOfAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether bounded recurrence delivery has more work at the latest requested clock; ProjectionAsOfAt advances only when that work is complete.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'COLUMN', @level2name=N'HasPendingReconciliation';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_Account_ProfileReward_SelectedBadge parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'INDEX', @level2name=N'IX_Account_FK_ProfileReward_SelectedBadge';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_Account_ProfileReward_SelectedFrame parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'INDEX', @level2name=N'IX_Account_FK_ProfileReward_SelectedFrame';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Bounded maintenance selects the oldest eligible materialization clocks, excluding inactive lifecycle barriers, without scanning account payloads.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Account', @level2type=N'INDEX', @level2name=N'IX_Account_ReconciliationClock';
GO
