-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[AccountAuditRecord] (
    [AccountId] uniqueidentifier NOT NULL,
    [AuditRecordId] varchar(32) COLLATE DATABASE_DEFAULT NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_AccountAuditRecord_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_AccountAuditRecord] PRIMARY KEY CLUSTERED ([AccountId], [AuditRecordId]),
    CONSTRAINT [UQ_AccountAuditRecord_AuditRecordId] UNIQUE ([AuditRecordId]),
    CONSTRAINT [CK_AccountAuditRecord_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [FK_AccountAuditRecord_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_AccountAuditRecord_AuditRecords] FOREIGN KEY ([AuditRecordId]) REFERENCES [dbo].[AuditRecords] ([Id]) ON DELETE NO ACTION
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one ownership association between a personal account and its canonical shared audit record. Classification: Restricted. History: event; Retain with the linked personal audit record. Delete association and owned audit record atomically on approved final erasure; no content duplicated.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountAuditRecord';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountAuditRecord', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canonical shared AuditRecord ID; envelope content and shape remain Audit-owned. Uses DATABASE_DEFAULT collation to match the unchanged shared AuditRecords.Id.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountAuditRecord', @level2type=N'COLUMN', @level2name=N'AuditRecordId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountAuditRecord', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
