-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[ErasureMarker] (
    [Id] varchar(30) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL,
    CONSTRAINT [PK_ErasureMarker] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [CK_ErasureMarker_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_ErasureMarker_IdentityUserId] CHECK (DATALENGTH([Id])=30 AND LEFT([Id],4)='usr_' AND SUBSTRING([Id],5,26) NOT LIKE '%[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]%' COLLATE Latin1_General_100_BIN2)
);
GO
-- Bounded cleanup at original CreatedAt plus 35 elapsed days; restore and retry never restart retention.
CREATE INDEX [IX_ErasureMarker_Retention] ON [pocketquests].[ErasureMarker] ([CreatedAt], [Id]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one minimal verified deletion marker consisting only of opaque Identity ID and deletion time. Classification: Restricted. History: marker; Retain exactly 35 elapsed days after original verified live erasure, then remove. CreatedAt is the sole deletion/marker-creation clock and is preserved across restore and retry. External authoritative copies must survive backups and obey the same minimum-content policy.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ErasureMarker';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canonical never-recycled Identity user ID used for restore fencing; intentionally no FK to deleted personal data.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ErasureMarker', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original verified live-erasure and marker-creation instant, written atomically with successful purge. The writer supplies this canonical value; restore/import must preserve it and duplicate delivery must not update it. Retention expires exactly 35 elapsed days after this instant, never after restore or retry. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ErasureMarker', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Bounded cleanup at original CreatedAt plus 35 elapsed days; restore and retry never restart retention.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ErasureMarker', @level2type=N'INDEX', @level2name=N'IX_ErasureMarker_Retention';
GO
