-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestCompletion] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestOccurrenceId] uniqueidentifier NOT NULL,
    [QuestOccurrenceRevisionId] uniqueidentifier NOT NULL,
    [RecordedAt] datetimeoffset(7) NOT NULL,
    [UndoneAt] datetimeoffset(7) NULL,
    [UndoQuestOccurrenceEventId] uniqueidentifier NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestCompletion_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestCompletion_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    CONSTRAINT [PK_QuestCompletion] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestCompletion_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_QuestCompletion_AccountId_QuestOccurrenceId_Id] UNIQUE ([AccountId], [QuestOccurrenceId], [Id]),
    CONSTRAINT [CK_QuestCompletion_Undo] CHECK (([UndoneAt] IS NULL AND [UndoQuestOccurrenceEventId] IS NULL) OR ([UndoneAt] IS NOT NULL AND [UndoQuestOccurrenceEventId] IS NOT NULL AND [UndoneAt]>=[RecordedAt] AND [UndoneAt]<DATEADD(hour,24,[RecordedAt]))),
    CONSTRAINT [CK_QuestCompletion_RecordedAtUtc] CHECK (DATEPART(TZOFFSET,[RecordedAt])=0),
    CONSTRAINT [CK_QuestCompletion_UndoneAtUtc] CHECK ([UndoneAt] IS NULL OR DATEPART(TZOFFSET,[UndoneAt])=0),
    CONSTRAINT [CK_QuestCompletion_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestCompletion_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_QuestCompletion_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_QuestCompletion_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCompletion_QuestOccurrenceEvent_Completion] FOREIGN KEY ([AccountId], [QuestOccurrenceId], [Id]) REFERENCES [pocketquests].[QuestOccurrenceEvent] ([AccountId], [QuestOccurrenceId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCompletion_QuestOccurrenceRevision] FOREIGN KEY ([AccountId], [QuestOccurrenceId], [QuestOccurrenceRevisionId]) REFERENCES [pocketquests].[QuestOccurrenceRevision] ([AccountId], [QuestOccurrenceId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCompletion_QuestOccurrenceEvent_Undo] FOREIGN KEY ([AccountId], [QuestOccurrenceId], [UndoQuestOccurrenceEventId]) REFERENCES [pocketquests].[QuestOccurrenceEvent] ([AccountId], [QuestOccurrenceId], [Id]) ON DELETE NO ACTION
);
GO
-- At most one surviving completion per occurrence.
CREATE UNIQUE INDEX [UQ_QuestCompletion_OneLive] ON [pocketquests].[QuestCompletion] ([AccountId], [QuestOccurrenceId]) WHERE [UndoneAt] IS NULL;
GO
-- A stable Undo event reverses one specific completion only.
CREATE UNIQUE INDEX [UQ_QuestCompletion_OneUndo] ON [pocketquests].[QuestCompletion] ([AccountId], [UndoQuestOccurrenceEventId]) WHERE [UndoQuestOccurrenceEventId] IS NOT NULL;
GO
-- Page completion history and consistent exports by event time.
CREATE INDEX [IX_QuestCompletion_History] ON [pocketquests].[QuestCompletion] ([AccountId], [RecordedAt], [Id]);
GO
-- Supports FK_QuestCompletion_QuestOccurrenceRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestCompletion_FK_QuestOccurrenceRevision] ON [pocketquests].[QuestCompletion] ([AccountId], [QuestOccurrenceId], [QuestOccurrenceRevisionId]);
GO
-- Supports FK_QuestCompletion_QuestOccurrenceEvent_Undo parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestCompletion_FK_QuestOccurrenceEvent_Undo] ON [pocketquests].[QuestCompletion] ([AccountId], [QuestOccurrenceId], [UndoQuestOccurrenceEventId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one immutable successful completion with at most one write-once Undo annotation. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'UUID of its Completed occurrence event and stable completion identifier.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Occurrence completed by this fact.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'QuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact completed terms; never replaced by a later definition edit.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'QuestOccurrenceRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Trusted recorded completion time, including validated offline time. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'RecordedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Trusted recorded Undo time, if the completion was reversed. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'UndoneAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable Undone event; null exactly when UndoneAt is null.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'UndoQuestOccurrenceEventId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'At most one surviving completion per occurrence.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'INDEX', @level2name=N'UQ_QuestCompletion_OneLive';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A stable Undo event reverses one specific completion only.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'INDEX', @level2name=N'UQ_QuestCompletion_OneUndo';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Page completion history and consistent exports by event time.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'INDEX', @level2name=N'IX_QuestCompletion_History';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestCompletion_QuestOccurrenceRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'INDEX', @level2name=N'IX_QuestCompletion_FK_QuestOccurrenceRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestCompletion_QuestOccurrenceEvent_Undo parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCompletion', @level2type=N'INDEX', @level2name=N'IX_QuestCompletion_FK_QuestOccurrenceEvent_Undo';
GO
