-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[ProfileReward] (
    [Id] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [KindCode] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Name] nvarchar(120) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [RequiredCount] int NOT NULL,
    [RequiredRank] char(1) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [RulesetVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_ProfileReward_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_ProfileReward_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_ProfileReward] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_ProfileReward_Id_KindCode] UNIQUE ([Id], [KindCode]),
    CONSTRAINT [CK_ProfileReward_KindCode] CHECK ([KindCode] IN ('Achievement','Badge','Frame')),
    CONSTRAINT [CK_ProfileReward_RequiredRank] CHECK ([RequiredRank] IN ('F','E','D','C','B','A','S')),
    CONSTRAINT [CK_ProfileReward_RequiredCount] CHECK ([RequiredCount] >= 0),
    CONSTRAINT [CK_ProfileReward_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_ProfileReward_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_ProfileReward_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt])
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one public achievement, badge or frame definition. Classification: Public. History: reference; Retain referenced reward codes; history is the versioned catalog. Not erased with accounts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable reward code, including existing A01/A02/B01/B02/F01/F02 IDs.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Achievement, Badge or Frame; only Badge and Frame are selectable.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'KindCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Public display name of this reward.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'Name';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nonnegative qualifying count in the versioned reward rule.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'RequiredCount';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Minimum global rank in the versioned reward rule.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'RequiredRank';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Reviewed catalog/ruleset version that defines the qualifying predicate.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'RulesetVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'ProfileReward', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
