-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[XpLedgerEntry] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestOccurrenceEventId] uniqueidentifier NOT NULL,
    [ContributionCode] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [TrackCode] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [AttributeId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [SystemSkillId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [CustomSkillId] uniqueidentifier NULL,
    [EffectiveAt] datetimeoffset(7) NOT NULL,
    [Amount] bigint NOT NULL,
    [ProjectionVersion] bigint NOT NULL,
    [RulesetVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_XpLedgerEntry_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_XpLedgerEntry_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_XpLedgerEntry] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_XpLedgerEntry_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_XpLedgerEntry_SourceContributionTarget] UNIQUE ([AccountId], [QuestOccurrenceEventId], [ContributionCode], [TrackCode], [CategoryId], [AttributeId], [SystemSkillId], [CustomSkillId]),
    CONSTRAINT [CK_XpLedgerEntry_TrackTarget] CHECK (([TrackCode]='Overall' AND [CategoryId] IS NULL AND [AttributeId] IS NULL AND [SystemSkillId] IS NULL AND [CustomSkillId] IS NULL) OR ([TrackCode]='Category' AND [CategoryId] IS NOT NULL AND [AttributeId] IS NULL AND [SystemSkillId] IS NULL AND [CustomSkillId] IS NULL) OR ([TrackCode]='Attribute' AND [CategoryId] IS NULL AND [AttributeId] IS NOT NULL AND [SystemSkillId] IS NULL AND [CustomSkillId] IS NULL) OR ([TrackCode]='Skill' AND [CategoryId] IS NULL AND [AttributeId] IS NULL AND (([SystemSkillId] IS NOT NULL AND [CustomSkillId] IS NULL) OR ([SystemSkillId] IS NULL AND [CustomSkillId] IS NOT NULL)))),
    CONSTRAINT [CK_XpLedgerEntry_ContributionCode] CHECK ([ContributionCode] IN ('Base','StreakBonus','Penalty')),
    CONSTRAINT [CK_XpLedgerEntry_ProjectionVersion] CHECK ([ProjectionVersion] >= 0),
    CONSTRAINT [CK_XpLedgerEntry_SignAndPool] CHECK (([ContributionCode]='Penalty' AND [Amount]<=0 AND [TrackCode]='Category') OR ([ContributionCode] IN ('Base','StreakBonus') AND [Amount]>=0 AND ([ContributionCode]<>'StreakBonus' OR [TrackCode]='Category'))),
    CONSTRAINT [CK_XpLedgerEntry_EffectiveAtUtc] CHECK (DATEPART(TZOFFSET,[EffectiveAt])=0),
    CONSTRAINT [CK_XpLedgerEntry_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_XpLedgerEntry_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_XpLedgerEntry_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_XpLedgerEntry_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpLedgerEntry_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpLedgerEntry_Attribute] FOREIGN KEY ([AttributeId]) REFERENCES [pocketquests].[Attribute] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpLedgerEntry_Skill_System] FOREIGN KEY ([SystemSkillId]) REFERENCES [pocketquests].[Skill] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpLedgerEntry_CustomSkill] FOREIGN KEY ([AccountId], [CustomSkillId]) REFERENCES [pocketquests].[CustomSkill] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpLedgerEntry_QuestOccurrenceEvent] FOREIGN KEY ([AccountId], [QuestOccurrenceEventId]) REFERENCES [pocketquests].[QuestOccurrenceEvent] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Read/export/recalculate the current chronological ledger.
CREATE INDEX [IX_XpLedgerEntry_Timeline] ON [pocketquests].[XpLedgerEntry] ([AccountId], [EffectiveAt], [Id]);
GO
-- Supports FK_XpLedgerEntry_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpLedgerEntry_FK_Category] ON [pocketquests].[XpLedgerEntry] ([CategoryId]);
GO
-- Supports FK_XpLedgerEntry_Attribute parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpLedgerEntry_FK_Attribute] ON [pocketquests].[XpLedgerEntry] ([AttributeId]);
GO
-- Supports FK_XpLedgerEntry_Skill_System parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpLedgerEntry_FK_Skill_System] ON [pocketquests].[XpLedgerEntry] ([SystemSkillId]);
GO
-- Supports FK_XpLedgerEntry_CustomSkill parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpLedgerEntry_FK_CustomSkill] ON [pocketquests].[XpLedgerEntry] ([AccountId], [CustomSkillId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one currently effective derived contribution from an authoritative occurrence event. Classification: Restricted. History: projection; Retain only the current derived ledger; replace affected suffix transactionally. Source events remain authoritative. Erase with account.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable derived-entry UUID from source event, contribution kind and target identity.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Source event whose contribution is represented.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'QuestOccurrenceEventId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Base, StreakBonus or Penalty; placement seeds are separate.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'ContributionCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Progression pool: Overall, Category, Attribute or Skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'TrackCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Category target; null unless TrackCode is Category.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Attribute target; null unless TrackCode is Attribute.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'AttributeId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'System skill target; null for other pools or a custom skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'SystemSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account-owned custom skill target; null for other pools or a system skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'CustomSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Chronological application instant of the contribution. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'EffectiveAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Signed exact XP change; negative values are permitted for penalties only.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'Amount';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account projection generation represented by this current derived row.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'ProjectionVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Ruleset used when deriving this contribution.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'RulesetVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Read/export/recalculate the current chronological ledger.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'INDEX', @level2name=N'IX_XpLedgerEntry_Timeline';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpLedgerEntry_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'INDEX', @level2name=N'IX_XpLedgerEntry_FK_Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpLedgerEntry_Attribute parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'INDEX', @level2name=N'IX_XpLedgerEntry_FK_Attribute';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpLedgerEntry_Skill_System parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'INDEX', @level2name=N'IX_XpLedgerEntry_FK_Skill_System';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpLedgerEntry_CustomSkill parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpLedgerEntry', @level2type=N'INDEX', @level2name=N'IX_XpLedgerEntry_FK_CustomSkill';
GO
