-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[CategoryProgress] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [StreakDays] int NOT NULL,
    [BonusRatePercent] int NOT NULL,
    [HasQualifiedToday] bit NOT NULL,
    [IsExplicitlyPaused] bit NOT NULL,
    [AsOfDate] date NOT NULL,
    [TimeZoneId] varchar(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [ProjectionVersion] bigint NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_CategoryProgress_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_CategoryProgress_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_CategoryProgress] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_CategoryProgress_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_CategoryProgress_AccountId_CategoryId] UNIQUE ([AccountId], [CategoryId]),
    CONSTRAINT [CK_CategoryProgress_StreakDays] CHECK ([StreakDays] >= 0),
    CONSTRAINT [CK_CategoryProgress_BonusRatePercent] CHECK ([BonusRatePercent] BETWEEN 0 AND 20),
    CONSTRAINT [CK_CategoryProgress_ProjectionVersion] CHECK ([ProjectionVersion] >= 0),
    CONSTRAINT [CK_CategoryProgress_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_CategoryProgress_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_CategoryProgress_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_CategoryProgress_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_CategoryProgress_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION
);
GO
-- Supports FK_CategoryProgress_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_CategoryProgress_FK_Category] ON [pocketquests].[CategoryProgress] ([CategoryId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one current account/category streak and explicit pause setting. Classification: Restricted. History: projection; Current projection plus explicit category switch; source pause intervals are retained. Erase with account.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Category whose streak is displayed.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nonnegative category streak length under pause/zone history.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'StreakDays';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Integer category streak bonus percentage, from 0 through the approved maximum 20 under PQ-MVP-013.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'BonusRatePercent';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether the account qualified in this category on AsOfDate.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'HasQualifiedToday';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current explicit category-pause switch; distinct from the account-wide switch.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'IsExplicitlyPaused';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account-calendar date used for the current-day flag.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'AsOfDate';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'IANA timezone used for AsOfDate.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'TimeZoneId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account projection generation of this summary.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'ProjectionVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_CategoryProgress_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CategoryProgress', @level2type=N'INDEX', @level2name=N'IX_CategoryProgress_FK_Category';
GO
