-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestSeries] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestDefinitionId] uniqueidentifier NOT NULL,
    [Revision] int NOT NULL,
    [NextSequence] int NOT NULL,
    [PauseDays] int NOT NULL,
    [NextDeliveryOn] date NULL,
    [StoppedAt] datetimeoffset(7) NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestSeries_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestSeries_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    [CreationOrdinal] int NOT NULL CONSTRAINT [DF_QuestSeries_CreationOrdinal] DEFAULT (0),
    CONSTRAINT [PK_QuestSeries] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestSeries_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_QuestSeries_Revision] CHECK ([Revision] >= 1),
    CONSTRAINT [CK_QuestSeries_NextSequence] CHECK ([NextSequence] >= 0),
    CONSTRAINT [CK_QuestSeries_PauseDays] CHECK ([PauseDays] >= 0),
    CONSTRAINT [CK_QuestSeries_StoppedAtUtc] CHECK ([StoppedAt] IS NULL OR DATEPART(TZOFFSET,[StoppedAt])=0),
    CONSTRAINT [CK_QuestSeries_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestSeries_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_QuestSeries_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [CK_QuestSeries_CreationOrdinal] CHECK ([CreationOrdinal]>=0),
    CONSTRAINT [FK_QuestSeries_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestSeries_QuestDefinition] FOREIGN KEY ([AccountId], [QuestDefinitionId]) REFERENCES [pocketquests].[QuestDefinition] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Find due recurrence for the authenticated account without loading stopped history.
CREATE INDEX [IX_QuestSeries_Due] ON [pocketquests].[QuestSeries] ([AccountId], [NextDeliveryOn], [Id]) WHERE [StoppedAt] IS NULL;
GO
-- Supports FK_QuestSeries_QuestDefinition parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestSeries_FK_QuestDefinition] ON [pocketquests].[QuestSeries] ([AccountId], [QuestDefinitionId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one opted-in recurrence series and its durable delivery cursor. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Quest identity delivered by this recurrence series.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'QuestDefinitionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current immutable series configuration revision.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'Revision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Next nonnegative sequence within the current series revision.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'NextSequence';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nonnegative local-calendar days shifted by effective pauses.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'PauseDays';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Next delivery date in the selected account calendar; null when stopped or no representable next date.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'NextDeliveryOn';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Time recurrence was explicitly stopped; stopped series are never silently restarted. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'StoppedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable one-based position in the existing API array, set once at creation; zero is reserved for public catalog adoption or the retained v1 adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'COLUMN', @level2name=N'CreationOrdinal';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Find due recurrence for the authenticated account without loading stopped history.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'INDEX', @level2name=N'IX_QuestSeries_Due';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestSeries_QuestDefinition parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeries', @level2type=N'INDEX', @level2name=N'IX_QuestSeries_FK_QuestDefinition';
GO
