-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestCommandHistory] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [CommandReceiptId] uniqueidentifier NULL,
    [AccountMutationVersion] bigint NOT NULL,
    [ActionCode] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [RulesetVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [TimeZoneBefore] varchar(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [ReconciledAt] datetimeoffset(7) NOT NULL,
    [RecordedAt] datetimeoffset(7) NOT NULL,
    [ProjectionAt] datetimeoffset(7) NOT NULL,
    [QuestOccurrenceId] uniqueidentifier NULL,
    [QuestCompletionId] uniqueidentifier NULL,
    [QuestDefinitionRevisionId] uniqueidentifier NULL,
    [CompletionTermsRevisionId] uniqueidentifier NULL,
    [ExpectedRevision] int NULL,
    [SystemSkillId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [CustomSkillId] uniqueidentifier NULL,
    [SkillName] nvarchar(80) COLLATE DATABASE_DEFAULT NULL,
    [ExperienceCode] varchar(12) COLLATE Latin1_General_100_BIN2 NULL,
    [DueOn] date NULL,
    [PlannedTime] time(0) NULL,
    [ParentQuestOccurrenceId] uniqueidentifier NULL,
    [ProfileRewardId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [QuestSeriesId] uniqueidentifier NULL,
    [CadenceCode] varchar(6) COLLATE Latin1_General_100_BIN2 NULL,
    [Interval] int NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [ConfirmPenalty] bit NOT NULL,
    [AcceptedLoss] int NULL,
    [HasAcceptedTerms] bit NOT NULL,
    [NewTimeZone] varchar(100) COLLATE Latin1_General_100_BIN2 NULL,
    [ExpectedTimeZone] varchar(100) COLLATE Latin1_General_100_BIN2 NULL,
    [ConfirmZoneChange] bit NOT NULL,
    [HasExpiryWarnings] bit NULL,
    [SourceSyncAnchorId] uniqueidentifier NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL,
    [ReconciliationLimit] int NOT NULL CONSTRAINT [DF_QuestCommandHistory_ReconciliationLimit] DEFAULT (2147483647),
    [ActionReconciliationLimit] int NOT NULL CONSTRAINT [DF_QuestCommandHistory_ActionReconciliationLimit] DEFAULT (2147483647),
    CONSTRAINT [PK_QuestCommandHistory] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestCommandHistory_Account_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_QuestCommandHistory_Account_Version] UNIQUE ([AccountId], [AccountMutationVersion]),
    CONSTRAINT [CK_QuestCommandHistory_Action] CHECK ([ActionCode] IN ('accept','complete','undo','save-definition','archive-definition','assess-skill','save-skill','archive-skill','interests','finish-onboarding','plan','zone','expiry-warnings','link','select-badge','select-frame','save-series','stop-series','pause','resume','resume-occurrence','abandon','accept-offer','$reconcile','$lifecycle-pause')),
    CONSTRAINT [CK_QuestCommandHistory_Version] CHECK ([AccountMutationVersion]>0 AND ([ExpectedRevision] IS NULL OR [ExpectedRevision]>=0)),
    CONSTRAINT [CK_QuestCommandHistory_SkillTarget] CHECK ([SystemSkillId] IS NULL OR [CustomSkillId] IS NULL),
    CONSTRAINT [CK_QuestCommandHistory_Receipt] CHECK (([ActionCode] IN ('$reconcile','$lifecycle-pause') AND [CommandReceiptId] IS NULL) OR ([ActionCode]<>'$reconcile' AND [ActionCode]<>'$lifecycle-pause' AND [CommandReceiptId] IS NOT NULL AND [CommandReceiptId]=[Id])),
    CONSTRAINT [CK_QuestCommandHistory_Cadence] CHECK ([CadenceCode] IS NULL OR [CadenceCode] IN ('Days','Weeks','Months','Years')),
    CONSTRAINT [CK_QuestCommandHistory_Interval] CHECK ([Interval] IS NULL OR ([Interval]>=1 AND [Interval]<=999)),
    CONSTRAINT [CK_QuestCommandHistory_Experience] CHECK ([ExperienceCode] IS NULL OR [ExperienceCode] IN ('New','Practiced','Experienced','Expert')),
    CONSTRAINT [CK_QuestCommandHistory_Clocks] CHECK ([ProjectionAt]>=[ReconciledAt] AND [ProjectionAt]>=[RecordedAt]),
    CONSTRAINT [CK_QuestCommandHistory_ReconciledAtUtc] CHECK (DATEPART(TZOFFSET,[ReconciledAt])=0),
    CONSTRAINT [CK_QuestCommandHistory_RecordedAtUtc] CHECK (DATEPART(TZOFFSET,[RecordedAt])=0),
    CONSTRAINT [CK_QuestCommandHistory_ProjectionAtUtc] CHECK (DATEPART(TZOFFSET,[ProjectionAt])=0),
    CONSTRAINT [CK_QuestCommandHistory_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestCommandHistory_ReconciliationLimit] CHECK ([ReconciliationLimit]>=0),
    CONSTRAINT [CK_QuestCommandHistory_ActionReconciliationLimit] CHECK ([ActionReconciliationLimit]>=0),
    CONSTRAINT [FK_QuestCommandHistory_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_CommandReceiptId] FOREIGN KEY ([AccountId], [CommandReceiptId]) REFERENCES [pocketquests].[CommandReceipt] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_QuestOccurrenceId] FOREIGN KEY ([AccountId], [QuestOccurrenceId]) REFERENCES [pocketquests].[QuestOccurrence] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_QuestCompletionId] FOREIGN KEY ([AccountId], [QuestCompletionId]) REFERENCES [pocketquests].[QuestCompletion] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_QuestDefinitionRevisionId] FOREIGN KEY ([AccountId], [QuestDefinitionRevisionId]) REFERENCES [pocketquests].[QuestDefinitionRevision] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_CompletionTermsRevisionId] FOREIGN KEY ([AccountId], [CompletionTermsRevisionId]) REFERENCES [pocketquests].[QuestOccurrenceRevision] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_CustomSkillId] FOREIGN KEY ([AccountId], [CustomSkillId]) REFERENCES [pocketquests].[CustomSkill] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_ParentQuestOccurrenceId] FOREIGN KEY ([AccountId], [ParentQuestOccurrenceId]) REFERENCES [pocketquests].[QuestOccurrence] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_QuestSeriesId] FOREIGN KEY ([AccountId], [QuestSeriesId]) REFERENCES [pocketquests].[QuestSeries] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_SourceSyncAnchorId] FOREIGN KEY ([AccountId], [SourceSyncAnchorId]) REFERENCES [pocketquests].[SyncAnchor] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_Skill] FOREIGN KEY ([SystemSkillId]) REFERENCES [pocketquests].[Skill] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_ProfileReward] FOREIGN KEY ([ProfileRewardId]) REFERENCES [pocketquests].[ProfileReward] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestCommandHistory_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION
);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_CommandReceiptId.
CREATE INDEX [IX_QuestCommandHistory_CommandReceiptId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [CommandReceiptId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestOccurrenceId.
CREATE INDEX [IX_QuestCommandHistory_QuestOccurrenceId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [QuestOccurrenceId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestCompletionId.
CREATE INDEX [IX_QuestCommandHistory_QuestCompletionId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [QuestCompletionId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestDefinitionRevisionId.
CREATE INDEX [IX_QuestCommandHistory_QuestDefinitionRevisionId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [QuestDefinitionRevisionId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_CompletionTermsRevisionId.
CREATE INDEX [IX_QuestCommandHistory_CompletionTermsRevisionId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [CompletionTermsRevisionId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_CustomSkillId.
CREATE INDEX [IX_QuestCommandHistory_CustomSkillId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [CustomSkillId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_ParentQuestOccurrenceId.
CREATE INDEX [IX_QuestCommandHistory_ParentQuestOccurrenceId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [ParentQuestOccurrenceId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestSeriesId.
CREATE INDEX [IX_QuestCommandHistory_QuestSeriesId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [QuestSeriesId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_SourceSyncAnchorId.
CREATE INDEX [IX_QuestCommandHistory_SourceSyncAnchorId] ON [pocketquests].[QuestCommandHistory] ([AccountId], [SourceSyncAnchorId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_Skill.
CREATE INDEX [IX_QuestCommandHistory_SystemSkillId] ON [pocketquests].[QuestCommandHistory] ([SystemSkillId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_ProfileReward.
CREATE INDEX [IX_QuestCommandHistory_ProfileRewardId] ON [pocketquests].[QuestCommandHistory] ([ProfileRewardId]);
GO
-- Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_Category.
CREATE INDEX [IX_QuestCommandHistory_CategoryId] ON [pocketquests].[QuestCommandHistory] ([CategoryId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one immutable, typed successful action input and its replay clocks, never a serialized command or account snapshot. Classification: Restricted. History: immutable. Erase with its account; no age cutoff on replay history.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable transition UUID, equal to the operation UUID for a client command.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Owning personal account; all references use this same ownership boundary.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Receipt for a client command; null for an internal reconciliation or lifecycle transition. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Committed account sequence used to reconstruct a receipt or an issued sync anchor.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'AccountMutationVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable command action or the documented internal reconciliation/lifecycle action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ActionCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Retained domain replay implementation version; never silently replay through a different ruleset.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'RulesetVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'IANA zone immediately before this transition; the first row preserves the initial account zone.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'TimeZoneBefore';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'UTC clock through which due series deliveries were reconciled before applying the action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ReconciledAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Verified UTC effective action time; may precede receipt by any duration.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'RecordedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original UTC response projection time, independent of later retries.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ProjectionAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Target or server-resolved new occurrence identity. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'QuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Completion selected by Undo. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'QuestCompletionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Immutable quest terms supplied to a definition, acceptance, series or offer command. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'QuestDefinitionRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen occurrence revision actually used for a delayed completion after a later edit. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'CompletionTermsRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Optimistic public definition, skill or series revision supplied by the successful command. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ExpectedRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'System skill selected for assessment. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'SystemSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Owned skill selected for creation, editing, archival or assessment. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'CustomSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Validated name supplied by a skill save command; this is historical input, not the mutable current name. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'SkillName';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Validated experience selected for an assessment. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ExperienceCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Requested due or first-delivery local date. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'DueOn';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Requested local hour and minute. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'PlannedTime';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Owned parent selected by a link command. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ParentQuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Selected badge or frame; null also records an explicit clear. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ProfileRewardId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Owned recurrence selected for creation, edit or stop. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'QuestSeriesId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Requested recurrence unit. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'CadenceCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Requested positive recurrence interval. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'Interval';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Category pause/resume target; null means the whole account. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether the successful command explicitly confirmed penalty terms.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ConfirmPenalty';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact penalty amount accepted by the command. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'AcceptedLoss';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether the client supplied accepted quest terms; reconstruct them from the immutable typed terms reference.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'HasAcceptedTerms';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Requested IANA zone for a zone-change command. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'NewTimeZone';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Optimistic previous IANA zone supplied by the command. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ExpectedTimeZone';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether a successful zone change was explicitly confirmed.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ConfirmZoneChange';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Requested expiry-warning preference. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'HasExpiryWarnings';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original proof anchor, retaining offline acceptance provenance without copying an anchor snapshot. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'SourceSyncAnchorId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'UTC server insertion instant; never substituted for the effective action clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Maximum due-delivery cursor steps performed before this action; zero records lifecycle transitions that intentionally do not reconcile before freezing. Retain this input for exact partial-batch replay.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ReconciliationLimit';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Maximum due-delivery cursor work performed by the action itself, such as a zone change or series creation; retained independently of the pre-action budget for exact original-response replay.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'COLUMN', @level2name=N'ActionReconciliationLimit';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_CommandReceiptId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestOccurrenceId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_QuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestCompletionId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_QuestCompletionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestDefinitionRevisionId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_QuestDefinitionRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_CompletionTermsRevisionId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_CompletionTermsRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_CustomSkillId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_CustomSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_ParentQuestOccurrenceId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_ParentQuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_QuestSeriesId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_QuestSeriesId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_SourceSyncAnchorId.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_SourceSyncAnchorId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_Skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_SystemSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_ProfileReward.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_ProfileRewardId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports ownership FK validation and direct history lookup for FK_QuestCommandHistory_Category.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestCommandHistory', @level2type=N'INDEX', @level2name=N'IX_QuestCommandHistory_CategoryId';
GO
