-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestOccurrenceRevision] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestOccurrenceId] uniqueidentifier NOT NULL,
    [Revision] int NOT NULL,
    [QuestDefinitionId] uniqueidentifier NOT NULL,
    [QuestDefinitionRevisionId] uniqueidentifier NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [DueOn] date NULL,
    [PlannedTime] time(0) NULL,
    [DeadlineAt] datetimeoffset(7) NULL,
    [DeadlineTimeZoneId] varchar(100) COLLATE Latin1_General_100_BIN2 NULL,
    [StateCode] varchar(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [AcceptedAt] datetimeoffset(7) NULL,
    [FrozenAt] datetimeoffset(7) NULL,
    [IsIndividuallyFrozen] bit NOT NULL CONSTRAINT [DF_QuestOccurrenceRevision_IsIndividuallyFrozen] DEFAULT (0),
    [AbandonedAt] datetimeoffset(7) NULL,
    [LockedLoss] bigint NULL,
    [LossCategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [AccountMutationVersion] bigint NOT NULL,
    [EffectiveAt] datetimeoffset(7) NOT NULL,
    [CommandReceiptId] uniqueidentifier NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestOccurrenceRevision_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [OriginatedAt] datetimeoffset(7) NULL,
    [OriginatedOffsetMinutes] smallint NOT NULL CONSTRAINT [DF_QuestOccurrenceRevision_OriginatedOffsetMinutes] DEFAULT (0),
    CONSTRAINT [PK_QuestOccurrenceRevision] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestOccurrenceRevision_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_QuestOccurrenceRevision_AccountId_QuestOccurrenceId_Revision] UNIQUE ([AccountId], [QuestOccurrenceId], [Revision]),
    CONSTRAINT [UQ_QuestOccurrenceRevision_AccountId_QuestOccurrenceId_Id] UNIQUE ([AccountId], [QuestOccurrenceId], [Id]),
    CONSTRAINT [CK_QuestOccurrenceRevision_StateCode] CHECK ([StateCode] IN ('Active','Completed','Missed','Frozen','Abandoned','Offered')),
    CONSTRAINT [CK_QuestOccurrenceRevision_ScheduleNulls] CHECK (([DueOn] IS NULL AND [DeadlineAt] IS NULL AND [PlannedTime] IS NULL) OR ([DueOn] IS NOT NULL AND [DeadlineAt] IS NOT NULL AND [DeadlineTimeZoneId] IS NOT NULL AND [DueOn]<CONVERT(date,'9999-01-01'))),
    CONSTRAINT [CK_QuestOccurrenceRevision_LockedPenalty] CHECK (([LockedLoss] IS NULL AND [LossCategoryId] IS NULL) OR ([LockedLoss] IS NOT NULL AND [LockedLoss]>=0 AND [LossCategoryId] IS NOT NULL)),
    CONSTRAINT [CK_QuestOccurrenceRevision_Acceptance] CHECK (([StateCode]='Offered' AND [AcceptedAt] IS NULL AND [LockedLoss] IS NULL) OR ([StateCode]<>'Offered' AND [AcceptedAt] IS NOT NULL)),
    CONSTRAINT [CK_QuestOccurrenceRevision_FreezeFlag] CHECK ([IsIndividuallyFrozen]=0 OR [FrozenAt] IS NOT NULL),
    CONSTRAINT [CK_QuestOccurrenceRevision_Revision] CHECK ([Revision] >= 1),
    CONSTRAINT [CK_QuestOccurrenceRevision_AccountMutationVersion] CHECK ([AccountMutationVersion] >= 0),
    CONSTRAINT [CK_QuestOccurrenceRevision_DeadlineAtUtc] CHECK ([DeadlineAt] IS NULL OR DATEPART(TZOFFSET,[DeadlineAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_AcceptedAtUtc] CHECK ([AcceptedAt] IS NULL OR DATEPART(TZOFFSET,[AcceptedAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_FrozenAtUtc] CHECK ([FrozenAt] IS NULL OR DATEPART(TZOFFSET,[FrozenAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_AbandonedAtUtc] CHECK ([AbandonedAt] IS NULL OR DATEPART(TZOFFSET,[AbandonedAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_EffectiveAtUtc] CHECK (DATEPART(TZOFFSET,[EffectiveAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_OriginatedAtUtc] CHECK ([OriginatedAt] IS NULL OR DATEPART(TZOFFSET,[OriginatedAt])=0),
    CONSTRAINT [CK_QuestOccurrenceRevision_OriginatedOffset] CHECK ([OriginatedOffsetMinutes]>=-840 AND [OriginatedOffsetMinutes]<=840),
    CONSTRAINT [FK_QuestOccurrenceRevision_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrenceRevision_QuestDefinitionRevision] FOREIGN KEY ([AccountId], [QuestDefinitionId], [QuestDefinitionRevisionId]) REFERENCES [pocketquests].[QuestDefinitionRevision] ([AccountId], [QuestDefinitionId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrenceRevision_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrenceRevision_Category_Loss] FOREIGN KEY ([LossCategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrenceRevision_QuestOccurrence] FOREIGN KEY ([AccountId], [QuestOccurrenceId]) REFERENCES [pocketquests].[QuestOccurrence] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrenceRevision_CommandReceipt] FOREIGN KEY ([AccountId], [CommandReceiptId]) REFERENCES [pocketquests].[CommandReceipt] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Find the latest exact occurrence terms visible to an issued anchor.
CREATE INDEX [IX_QuestOccurrenceRevision_AnchorVisibility] ON [pocketquests].[QuestOccurrenceRevision] ([AccountId], [QuestOccurrenceId], [AccountMutationVersion], [Id]);
GO
-- Supports FK_QuestOccurrenceRevision_QuestDefinitionRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrenceRevision_FK_QuestDefinitionRevision] ON [pocketquests].[QuestOccurrenceRevision] ([AccountId], [QuestDefinitionId], [QuestDefinitionRevisionId]);
GO
-- Supports FK_QuestOccurrenceRevision_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrenceRevision_FK_Category] ON [pocketquests].[QuestOccurrenceRevision] ([CategoryId]);
GO
-- Supports FK_QuestOccurrenceRevision_Category_Loss parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrenceRevision_FK_Category_Loss] ON [pocketquests].[QuestOccurrenceRevision] ([LossCategoryId]);
GO
-- Supports FK_QuestOccurrenceRevision_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrenceRevision_FK_CommandReceipt] ON [pocketquests].[QuestOccurrenceRevision] ([AccountId], [CommandReceiptId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one immutable occurrence version visible at a committed account mutation. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Occurrence whose terms and scheduling state this version captures.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'QuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive version within this occurrence.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'Revision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Persistent account-owned definition identity.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'QuestDefinitionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact immutable content/reward revision used by this occurrence version.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'QuestDefinitionRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Materialized current/frozen category for filtering, constrained to the controlled revision write.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Due date in DeadlineTimeZoneId; null means unscheduled with no deadline.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'DueOn';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Optional local planned clock time; null means none; requires DueOn.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'PlannedTime';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Absolute end-of-due-day deadline; null for unscheduled occurrence. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'DeadlineAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'IANA calendar zone used to calculate DueOn/DeadlineAt. Null only for unscheduled occurrence.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'DeadlineTimeZoneId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Active, Completed, Missed, Frozen, Abandoned or Offered; time-dependent projection can be newer than persisted reconciliation.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'StateCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recorded acceptance time; null while only an unaccepted offer. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'AcceptedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Start of the current freeze, if any. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'FrozenAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether an individual freeze remains after account/category resume.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'IsIndividuallyFrozen';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Explicit abandonment time, if any. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'AbandonedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact accepted nonnegative penalty amount. Null means no penalty commitment.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'LockedLoss';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Category frozen with an accepted loss; null exactly when LockedLoss is null.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'LossCategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Visibility order at commit; distinct from backdated EffectiveAt.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'AccountMutationVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recorded effective time of the transition. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'EffectiveAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Receipt for the command that caused this fact. Null means trusted clock/lifecycle reconciliation, not a client command.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original occurrence creation/delivery instant used by the domain even while the recurring occurrence is still an unaccepted offer. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'OriginatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original domain/API display offset of OriginatedAt, retained separately from its authoritative UTC instant for exact recurring-offer response reconstruction.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'COLUMN', @level2name=N'OriginatedOffsetMinutes';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Find the latest exact occurrence terms visible to an issued anchor.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrenceRevision_AnchorVisibility';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrenceRevision_QuestDefinitionRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrenceRevision_FK_QuestDefinitionRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrenceRevision_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrenceRevision_FK_Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrenceRevision_Category_Loss parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrenceRevision_FK_Category_Loss';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrenceRevision_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrenceRevision', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrenceRevision_FK_CommandReceipt';
GO
