-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[AccountPause] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [ScopeCode] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [StartedAt] datetimeoffset(7) NOT NULL,
    [EndedAt] datetimeoffset(7) NULL,
    [CommandReceiptId] uniqueidentifier NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_AccountPause_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_AccountPause_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    [CreationOrdinal] int NOT NULL CONSTRAINT [DF_AccountPause_CreationOrdinal] DEFAULT (0),
    CONSTRAINT [PK_AccountPause] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_AccountPause_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_AccountPause_Scope] CHECK (([ScopeCode]='Account' AND [CategoryId] IS NULL) OR ([ScopeCode]='Category' AND [CategoryId] IS NOT NULL)),
    CONSTRAINT [CK_AccountPause_Interval] CHECK ([EndedAt] IS NULL OR [EndedAt]>=[StartedAt]),
    CONSTRAINT [CK_AccountPause_StartedAtUtc] CHECK (DATEPART(TZOFFSET,[StartedAt])=0),
    CONSTRAINT [CK_AccountPause_EndedAtUtc] CHECK ([EndedAt] IS NULL OR DATEPART(TZOFFSET,[EndedAt])=0),
    CONSTRAINT [CK_AccountPause_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_AccountPause_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_AccountPause_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [CK_AccountPause_CreationOrdinal] CHECK ([CreationOrdinal]>=0),
    CONSTRAINT [FK_AccountPause_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_AccountPause_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_AccountPause_CommandReceipt] FOREIGN KEY ([AccountId], [CommandReceiptId]) REFERENCES [pocketquests].[CommandReceipt] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- At most one open explicit pause per account/scope.
CREATE UNIQUE INDEX [UQ_AccountPause_OpenScope] ON [pocketquests].[AccountPause] ([AccountId], [ScopeCode], [CategoryId]) WHERE [EndedAt] IS NULL;
GO
-- Replay pause intervals by effective time; overlapping scopes are unioned, never double-counted.
CREATE INDEX [IX_AccountPause_Replay] ON [pocketquests].[AccountPause] ([AccountId], [StartedAt], [Id]);
GO
-- Supports FK_AccountPause_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_AccountPause_FK_Category] ON [pocketquests].[AccountPause] ([CategoryId]);
GO
-- Supports FK_AccountPause_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_AccountPause_FK_CommandReceipt] ON [pocketquests].[AccountPause] ([AccountId], [CommandReceiptId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one explicit account/category pause interval. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account or Category; distinguishes all-category intent from one-category intent.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'ScopeCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Paused category; null means account-wide scope.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Effective start of this pause. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'StartedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Effective end of this pause. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'EndedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Receipt for the command that caused this fact. Null means trusted clock/lifecycle reconciliation, not a client command.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable one-based position in the existing API array, set once at creation; zero is reserved for public catalog adoption or the retained v1 adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'COLUMN', @level2name=N'CreationOrdinal';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'At most one open explicit pause per account/scope.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'INDEX', @level2name=N'UQ_AccountPause_OpenScope';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Replay pause intervals by effective time; overlapping scopes are unioned, never double-counted.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'INDEX', @level2name=N'IX_AccountPause_Replay';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_AccountPause_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'INDEX', @level2name=N'IX_AccountPause_FK_Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_AccountPause_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountPause', @level2type=N'INDEX', @level2name=N'IX_AccountPause_FK_CommandReceipt';
GO
