-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestSeriesRevision] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestSeriesId] uniqueidentifier NOT NULL,
    [Revision] int NOT NULL,
    [QuestDefinitionRevisionId] uniqueidentifier NOT NULL,
    [CadenceCode] varchar(6) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Interval] int NOT NULL,
    [AnchorOn] date NOT NULL,
    [PlannedTime] time(0) NULL,
    [HasAutoAcceptPenalty] bit NOT NULL CONSTRAINT [DF_QuestSeriesRevision_HasAutoAcceptPenalty] DEFAULT (0),
    [EffectiveAt] datetimeoffset(7) NOT NULL,
    [CommandReceiptId] uniqueidentifier NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestSeriesRevision_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ScheduleVersion] int NOT NULL CONSTRAINT [DF_QuestSeriesRevision_ScheduleVersion] DEFAULT (1),
    CONSTRAINT [PK_QuestSeriesRevision] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestSeriesRevision_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_QuestSeriesRevision_AccountId_QuestSeriesId_Revision] UNIQUE ([AccountId], [QuestSeriesId], [Revision]),
    CONSTRAINT [UQ_QuestSeriesRevision_AccountId_QuestSeriesId_Id] UNIQUE ([AccountId], [QuestSeriesId], [Id]),
    CONSTRAINT [CK_QuestSeriesRevision_Revision] CHECK ([Revision] >= 1),
    CONSTRAINT [CK_QuestSeriesRevision_CadenceCode] CHECK ([CadenceCode] IN ('Days','Weeks','Months','Years')),
    CONSTRAINT [CK_QuestSeriesRevision_Schedule] CHECK ([Interval] BETWEEN 1 AND 999 AND [AnchorOn] < CONVERT(date,'9999-01-01')),
    CONSTRAINT [CK_QuestSeriesRevision_EffectiveAtUtc] CHECK (DATEPART(TZOFFSET,[EffectiveAt])=0),
    CONSTRAINT [CK_QuestSeriesRevision_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestSeriesRevision_ScheduleVersion] CHECK ([ScheduleVersion]>=1),
    CONSTRAINT [FK_QuestSeriesRevision_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestSeriesRevision_QuestSeries] FOREIGN KEY ([AccountId], [QuestSeriesId]) REFERENCES [pocketquests].[QuestSeries] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestSeriesRevision_QuestDefinitionRevision] FOREIGN KEY ([AccountId], [QuestDefinitionRevisionId]) REFERENCES [pocketquests].[QuestDefinitionRevision] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestSeriesRevision_CommandReceipt] FOREIGN KEY ([AccountId], [CommandReceiptId]) REFERENCES [pocketquests].[CommandReceipt] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Supports FK_QuestSeriesRevision_QuestDefinitionRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestSeriesRevision_FK_QuestDefinitionRevision] ON [pocketquests].[QuestSeriesRevision] ([AccountId], [QuestDefinitionRevisionId]);
GO
-- Supports FK_QuestSeriesRevision_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestSeriesRevision_FK_CommandReceipt] ON [pocketquests].[QuestSeriesRevision] ([AccountId], [CommandReceiptId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one immutable recurrence configuration and consent state. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Series to which this version belongs.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'QuestSeriesId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive configuration sequence within a series.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'Revision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen terms scheduled by this version.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'QuestDefinitionRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Calendar recurrence unit: Days, Weeks, Months or Years.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'CadenceCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Calendar-unit interval 1..999, matching current validation.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'Interval';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'First delivery date in the selected account calendar; must precede year 9999.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'AnchorOn';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Optional local planned clock time, not the completion deadline. Null means no planned time.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'PlannedTime';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Explicit consent to automatically accept this version of recurring penalty terms.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'HasAutoAcceptPenalty';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'When this configuration became effective. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'EffectiveAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Receipt for the command that caused this fact.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Public domain schedule version; internal revision also changes when definition terms change without editing recurrence.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'COLUMN', @level2name=N'ScheduleVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestSeriesRevision_QuestDefinitionRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'INDEX', @level2name=N'IX_QuestSeriesRevision_FK_QuestDefinitionRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestSeriesRevision_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestSeriesRevision', @level2type=N'INDEX', @level2name=N'IX_QuestSeriesRevision_FK_CommandReceipt';
GO
