-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[XpBalance] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [TrackCode] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [AttributeId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [SystemSkillId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [CustomSkillId] uniqueidentifier NULL,
    [EarnedXp] bigint NOT NULL,
    [SeedXp] bigint NOT NULL,
    [Level] int NOT NULL,
    [ProjectionVersion] bigint NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_XpBalance_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_XpBalance_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_XpBalance] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_XpBalance_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_XpBalance_TrackTarget] UNIQUE ([AccountId], [TrackCode], [CategoryId], [AttributeId], [SystemSkillId], [CustomSkillId]),
    CONSTRAINT [CK_XpBalance_TrackTarget] CHECK (([TrackCode]='Overall' AND [CategoryId] IS NULL AND [AttributeId] IS NULL AND [SystemSkillId] IS NULL AND [CustomSkillId] IS NULL) OR ([TrackCode]='Category' AND [CategoryId] IS NOT NULL AND [AttributeId] IS NULL AND [SystemSkillId] IS NULL AND [CustomSkillId] IS NULL) OR ([TrackCode]='Attribute' AND [CategoryId] IS NULL AND [AttributeId] IS NOT NULL AND [SystemSkillId] IS NULL AND [CustomSkillId] IS NULL) OR ([TrackCode]='Skill' AND [CategoryId] IS NULL AND [AttributeId] IS NULL AND (([SystemSkillId] IS NOT NULL AND [CustomSkillId] IS NULL) OR ([SystemSkillId] IS NULL AND [CustomSkillId] IS NOT NULL)))),
    CONSTRAINT [CK_XpBalance_EarnedXp] CHECK ([EarnedXp] >= 0),
    CONSTRAINT [CK_XpBalance_SeedXp] CHECK ([SeedXp] >= 0),
    CONSTRAINT [CK_XpBalance_Level] CHECK ([Level] >= 1),
    CONSTRAINT [CK_XpBalance_ProjectionVersion] CHECK ([ProjectionVersion] >= 0),
    CONSTRAINT [CK_XpBalance_SeedPool] CHECK ([TrackCode]='Skill' OR [SeedXp]=0),
    CONSTRAINT [CK_XpBalance_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_XpBalance_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_XpBalance_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_XpBalance_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpBalance_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpBalance_Attribute] FOREIGN KEY ([AttributeId]) REFERENCES [pocketquests].[Attribute] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpBalance_Skill_System] FOREIGN KEY ([SystemSkillId]) REFERENCES [pocketquests].[Skill] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_XpBalance_CustomSkill] FOREIGN KEY ([AccountId], [CustomSkillId]) REFERENCES [pocketquests].[CustomSkill] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Supports FK_XpBalance_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpBalance_FK_Category] ON [pocketquests].[XpBalance] ([CategoryId]);
GO
-- Supports FK_XpBalance_Attribute parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpBalance_FK_Attribute] ON [pocketquests].[XpBalance] ([AttributeId]);
GO
-- Supports FK_XpBalance_Skill_System parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpBalance_FK_Skill_System] ON [pocketquests].[XpBalance] ([SystemSkillId]);
GO
-- Supports FK_XpBalance_CustomSkill parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_XpBalance_FK_CustomSkill] ON [pocketquests].[XpBalance] ([AccountId], [CustomSkillId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one current account/track-target projection with earned and seed components separated. Classification: Restricted. History: projection; Current projection only; rebuild from history and erase with account. No temporal copies.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Progression pool: Overall, Category, Attribute or Skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'TrackCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Category target; null unless TrackCode is Category.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Attribute target; null unless TrackCode is Attribute.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'AttributeId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'System skill target; null for other pools or a custom skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'SystemSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account-owned custom skill target; null for other pools or a system skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'CustomSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nonnegative earned balance after chronological zero-floor processing.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'EarnedXp';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nonnegative experience placement component; nonzero only for Skill.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'SeedXp';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive level derived by the approved curve; zero XP starts at level 1.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'Level';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account projection generation to which this balance belongs.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'ProjectionVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpBalance_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'INDEX', @level2name=N'IX_XpBalance_FK_Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpBalance_Attribute parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'INDEX', @level2name=N'IX_XpBalance_FK_Attribute';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpBalance_Skill_System parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'INDEX', @level2name=N'IX_XpBalance_FK_Skill_System';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_XpBalance_CustomSkill parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'XpBalance', @level2type=N'INDEX', @level2name=N'IX_XpBalance_FK_CustomSkill';
GO
