-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestDefinition] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [SystemQuestId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [Revision] int NOT NULL,
    [ArchivedAt] datetimeoffset(7) NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestDefinition_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestDefinition_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    [CreationOrdinal] int NOT NULL CONSTRAINT [DF_QuestDefinition_CreationOrdinal] DEFAULT (0),
    [ClientKey] varchar(36) COLLATE Latin1_General_100_BIN2 NULL,
    CONSTRAINT [PK_QuestDefinition] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestDefinition_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_QuestDefinition_Revision] CHECK ([Revision] >= 1),
    CONSTRAINT [CK_QuestDefinition_ArchivedAtUtc] CHECK ([ArchivedAt] IS NULL OR DATEPART(TZOFFSET,[ArchivedAt])=0),
    CONSTRAINT [CK_QuestDefinition_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestDefinition_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_QuestDefinition_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [CK_QuestDefinition_CreationOrdinal] CHECK ([CreationOrdinal]>=0),
    CONSTRAINT [CK_QuestDefinition_ClientKey] CHECK ([ClientKey] IS NULL OR (DATALENGTH([ClientKey])=36 AND TRY_CAST([ClientKey] AS uniqueidentifier) IS NOT NULL AND TRY_CAST([ClientKey] AS uniqueidentifier)=[Id])),
    CONSTRAINT [FK_QuestDefinition_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestDefinition_SystemQuest] FOREIGN KEY ([SystemQuestId]) REFERENCES [pocketquests].[SystemQuest] ([Id]) ON DELETE NO ACTION
);
GO
-- Only one local adopted definition for a system quest in an account.
CREATE UNIQUE INDEX [UQ_QuestDefinition_SystemIdentity] ON [pocketquests].[QuestDefinition] ([AccountId], [SystemQuestId]) WHERE [SystemQuestId] IS NOT NULL;
GO
-- Supports FK_QuestDefinition_SystemQuest parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestDefinition_FK_SystemQuest] ON [pocketquests].[QuestDefinition] ([SystemQuestId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one account-owned persistent quest identity, custom or adopted from the system catalog. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'System template identity; null means an editable custom definition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'SystemQuestId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current content revision number; matching immutable revision is committed by the controlled writer.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'Revision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Instant this definition was archived; existing occurrences retain history. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'ArchivedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable one-based position in the existing API array, set once at creation; zero is reserved for public catalog adoption or the retained v1 adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'CreationOrdinal';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original accepted UUID spelling for API compatibility; the typed Id remains the ownership key. Null is reserved for public catalog adoption or the retained v1 adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'COLUMN', @level2name=N'ClientKey';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Only one local adopted definition for a system quest in an account.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'INDEX', @level2name=N'UQ_QuestDefinition_SystemIdentity';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestDefinition_SystemQuest parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinition', @level2type=N'INDEX', @level2name=N'IX_QuestDefinition_FK_SystemQuest';
GO
