-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestDefinitionRevision] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestDefinitionId] uniqueidentifier NOT NULL,
    [Revision] int NOT NULL,
    [Title] nvarchar(120) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Criterion] nvarchar(2000) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Description] nvarchar(2000) COLLATE Latin1_General_100_BIN2 NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [RankCode] char(1) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [EffortCode] varchar(6) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [BaseXp] bigint NOT NULL,
    [PenaltyPercent] tinyint NOT NULL,
    [RulesetVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [DisplaySnapshotVersion] smallint NOT NULL,
    [DisplaySnapshotJson] nvarchar(max) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [EffectiveAt] datetimeoffset(7) NOT NULL,
    [CommandReceiptId] uniqueidentifier NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestDefinitionRevision_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_QuestDefinitionRevision] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestDefinitionRevision_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [UQ_QuestDefinitionRevision_AccountId_QuestDefinitionId_Revision] UNIQUE ([AccountId], [QuestDefinitionId], [Revision]),
    CONSTRAINT [UQ_QuestDefinitionRevision_AccountId_QuestDefinitionId_Id] UNIQUE ([AccountId], [QuestDefinitionId], [Id]),
    CONSTRAINT [CK_QuestDefinitionRevision_Revision] CHECK ([Revision] >= 1),
    CONSTRAINT [CK_QuestDefinitionRevision_BaseXp] CHECK ([BaseXp] >= 0),
    CONSTRAINT [CK_QuestDefinitionRevision_RankCode] CHECK ([RankCode] IN ('F','E','D','C','B','A','S')),
    CONSTRAINT [CK_QuestDefinitionRevision_EffortCode] CHECK ([EffortCode] IN ('Small','Medium','Large')),
    CONSTRAINT [CK_QuestDefinitionRevision_PenaltyPercent] CHECK ([PenaltyPercent] IN (0,10,25,50)),
    CONSTRAINT [CK_QuestDefinitionRevision_Text] CHECK (LEN([Title]) BETWEEN 1 AND 120 AND LEN([Criterion]) BETWEEN 1 AND 2000 AND DATALENGTH([Title])=DATALENGTH(TRIM([Title])) AND DATALENGTH([Criterion])=DATALENGTH(TRIM([Criterion]))),
    CONSTRAINT [CK_QuestDefinitionRevision_DisplayDocument] CHECK ([DisplaySnapshotVersion]>=1 AND ISJSON([DisplaySnapshotJson])=1 AND DATALENGTH([DisplaySnapshotJson])<=65536),
    CONSTRAINT [CK_QuestDefinitionRevision_EffectiveAtUtc] CHECK (DATEPART(TZOFFSET,[EffectiveAt])=0),
    CONSTRAINT [CK_QuestDefinitionRevision_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [FK_QuestDefinitionRevision_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestDefinitionRevision_QuestDefinition] FOREIGN KEY ([AccountId], [QuestDefinitionId]) REFERENCES [pocketquests].[QuestDefinition] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestDefinitionRevision_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestDefinitionRevision_CommandReceipt] FOREIGN KEY ([AccountId], [CommandReceiptId]) REFERENCES [pocketquests].[CommandReceipt] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Supports FK_QuestDefinitionRevision_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestDefinitionRevision_FK_Category] ON [pocketquests].[QuestDefinitionRevision] ([CategoryId]);
GO
-- Supports FK_QuestDefinitionRevision_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestDefinitionRevision_FK_CommandReceipt] ON [pocketquests].[QuestDefinitionRevision] ([AccountId], [CommandReceiptId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one immutable content/reward version of an account quest definition. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Definition to which this immutable revision belongs.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'QuestDefinitionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive sequence within this definition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'Revision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen trimmed quest title, 1 to 120 characters.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'Title';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen self-attestation criterion, 1 to 2000 characters; may contain personal content.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'Criterion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen optional quest explanation. Null means none was supplied.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'Description';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen category of this content revision.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen quest rank F/E/D/C/B/A/S.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'RankCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen Small, Medium or Large effort tier.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'EffortCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Calibrated nonnegative base XP under the frozen ruleset; never client-authoritative.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'BaseXp';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Proposed penalty percentage for new acceptance: 0, 10, 25 or 50. Accepted losses are separately locked.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'PenaltyPercent';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen ruleset version used to derive rewards.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'RulesetVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Schema version of the immutable display-label document.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'DisplaySnapshotVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Frozen human-readable names for historical display/export only; typed references and allocations enforce rules. Maximum 65536 UTF-16 bytes.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'DisplaySnapshotJson';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Time the new content revision became effective. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'EffectiveAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Receipt for the command that caused this fact. Null means trusted clock/lifecycle reconciliation, not a client command.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestDefinitionRevision_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'INDEX', @level2name=N'IX_QuestDefinitionRevision_FK_Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestDefinitionRevision_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionRevision', @level2type=N'INDEX', @level2name=N'IX_QuestDefinitionRevision_FK_CommandReceipt';
GO
