-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[Skill] (
    [Id] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Name] nvarchar(120) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CatalogVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [SortOrder] int NOT NULL,
    [NormalizedName] nvarchar(80) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_Skill_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_Skill_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_Skill] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_Skill_SortOrder] UNIQUE ([SortOrder]),
    CONSTRAINT [UQ_Skill_NormalizedName] UNIQUE ([NormalizedName]),
    CONSTRAINT [CK_Skill_SortOrder] CHECK ([SortOrder] >= 1),
    CONSTRAINT [CK_Skill_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_Skill_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_Skill_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt])
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one canonical system skill. Classification: Public. History: reference; Retain stable codes indefinitely; source control owns reference history. Not erased with accounts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable public catalog code; preserve existing IDs and ordinal allocation tie-breaking.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current public catalog display name.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'Name';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Version of the reviewed catalog that supplied this row.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'CatalogVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive canonical display order; not an independently chosen progression priority.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'SortOrder';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Reserved system skill name normalized by the versioned OrdinalIgnoreCase-equivalent normalizer; compare with BIN2 collation.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'NormalizedName';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'Skill', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
