-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[SkillAssessment] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [SystemSkillId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [CustomSkillId] uniqueidentifier NULL,
    [ExperienceCode] varchar(12) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [SeedXp] bigint NOT NULL,
    [RulesetVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [EffectiveAt] datetimeoffset(7) NOT NULL,
    [CommandReceiptId] uniqueidentifier NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_SkillAssessment_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_SkillAssessment] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_SkillAssessment_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_SkillAssessment_ExactlyOneSkill] CHECK (([SystemSkillId] IS NOT NULL AND [CustomSkillId] IS NULL) OR ([SystemSkillId] IS NULL AND [CustomSkillId] IS NOT NULL)),
    CONSTRAINT [CK_SkillAssessment_ExperienceCode] CHECK ([ExperienceCode] IN ('New','Practiced','Experienced','Expert')),
    CONSTRAINT [CK_SkillAssessment_SeedXp] CHECK ([SeedXp] >= 0),
    CONSTRAINT [CK_SkillAssessment_EffectiveAtUtc] CHECK (DATEPART(TZOFFSET,[EffectiveAt])=0),
    CONSTRAINT [CK_SkillAssessment_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [FK_SkillAssessment_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_SkillAssessment_Skill_System] FOREIGN KEY ([SystemSkillId]) REFERENCES [pocketquests].[Skill] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_SkillAssessment_CustomSkill] FOREIGN KEY ([AccountId], [CustomSkillId]) REFERENCES [pocketquests].[CustomSkill] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_SkillAssessment_CommandReceipt] FOREIGN KEY ([AccountId], [CommandReceiptId]) REFERENCES [pocketquests].[CommandReceipt] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Select/replay placements for one account skill with stable event-ID ties.
CREATE INDEX [IX_SkillAssessment_SkillTimeline] ON [pocketquests].[SkillAssessment] ([AccountId], [SystemSkillId], [CustomSkillId], [EffectiveAt], [Id]);
GO
-- Supports FK_SkillAssessment_Skill_System parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_SkillAssessment_FK_Skill_System] ON [pocketquests].[SkillAssessment] ([SystemSkillId]);
GO
-- Supports FK_SkillAssessment_CustomSkill parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_SkillAssessment_FK_CustomSkill] ON [pocketquests].[SkillAssessment] ([AccountId], [CustomSkillId]);
GO
-- Supports FK_SkillAssessment_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_SkillAssessment_FK_CommandReceipt] ON [pocketquests].[SkillAssessment] ([AccountId], [CommandReceiptId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one replacement experience placement effective at a recorded time. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'System skill being referenced; null when CustomSkillId is supplied.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'SystemSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Custom skill owned by this account; null when SystemSkillId is supplied.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'CustomSkillId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'New, Practiced, Experienced or Expert placement; this is not earned XP.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'ExperienceCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact placement component under RulesetVersion; replaces the prior seed without granting other pools.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'SeedXp';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Rules version that maps experience placement to seed XP.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'RulesetVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recorded placement time. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'EffectiveAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Receipt for the command that caused this fact.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'CommandReceiptId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Select/replay placements for one account skill with stable event-ID ties.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'INDEX', @level2name=N'IX_SkillAssessment_SkillTimeline';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_SkillAssessment_Skill_System parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'INDEX', @level2name=N'IX_SkillAssessment_FK_Skill_System';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_SkillAssessment_CustomSkill parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'INDEX', @level2name=N'IX_SkillAssessment_FK_CustomSkill';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_SkillAssessment_CommandReceipt parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SkillAssessment', @level2type=N'INDEX', @level2name=N'IX_SkillAssessment_FK_CommandReceipt';
GO
