// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one current category selected as an account interest. Classification: Restricted. History: event; Current association only; remove when deselected and at final erasure. No historical interest tracking.</summary>
public sealed class AccountInterestEntity
{
    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Selected category; never enables recurrence implicitly.</summary>
    public string CategoryId { get; set; } = string.Empty;

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Current selected category array position, zero-based and at most nine.</summary>
    public int Position { get; set; }
}
