// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one latest accepted lifecycle fence for a canonical Identity user, possibly before onboarding. Classification: Restricted. History: mutable; Retain while required to fence the account/pre-onboarding identity. On verified erasure replace with minimal marker; no content history.</summary>
public sealed class AccountLifecycleStateEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Canonical external Identity user being fenced; never a provider identity.</summary>
    public string IdentityUserId { get; set; } = string.Empty;

    /// <summary>Local product profile if one exists; null before onboarding or after purge.</summary>
    public Guid? AccountId { get; set; }

    /// <summary>Highest accepted monotonic Identity lifecycle version; old deliveries cannot reduce it.</summary>
    public long Version { get; set; }

    /// <summary>Active, Inactive or Erasing, as defined by the reviewed Identity lifecycle contract.</summary>
    public string StateCode { get; set; } = string.Empty;

    /// <summary>Authoritative Identity transition instant. UTC instant.</summary>
    public DateTimeOffset EffectiveAt { get; set; }

    /// <summary>Original deletion-request pause origin, retained across cancellation. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? PausedAt { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }

    /// <summary>SQL-generated opaque concurrency token; compare as bytes, not as a clock.</summary>
    public byte[] RowVersion { get; set; } = [];
}
