// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one personal Pocket Quests profile for a verified canonical Identity user. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class AccountEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Canonical never-recycled usr_ identifier returned by HoneyDrunk.Identity, not a provider subject or email.</summary>
    public string IdentityUserId { get; set; } = string.Empty;

    /// <summary>Selected IANA timezone used for personal calendar calculations, not a UTC offset.</summary>
    public string TimeZoneId { get; set; } = string.Empty;

    /// <summary>Whether explicit product onboarding completed.</summary>
    public bool IsOnboardingComplete { get; set; }

    /// <summary>Whether the account requested optional grouped expiry warnings; device OS permission is separate.</summary>
    public bool HasExpiryWarnings { get; set; }

    /// <summary>Current explicit all-category pause setting; effective intervals are stored separately.</summary>
    public bool IsAccountPaused { get; set; }

    /// <summary>Selected badge code; null means no selected badge.</summary>
    public string? SelectedBadgeId { get; set; }

    /// <summary>Constant Badge discriminator for the typed reward FK.</summary>
    public string SelectedBadgeKind { get; set; } = string.Empty;

    /// <summary>Selected frame code; null means no selected frame.</summary>
    public string? SelectedFrameId { get; set; }

    /// <summary>Constant Frame discriminator for the typed reward FK.</summary>
    public string SelectedFrameKind { get; set; } = string.Empty;

    /// <summary>Fixed account logical-time high-water mark; never a future deadline. UTC instant.</summary>
    public DateTimeOffset LastRecordedAt { get; set; }

    /// <summary>Monotonic committed account mutation number; issued anchors retain this visibility version.</summary>
    public long MutationVersion { get; set; }

    /// <summary>Mutation version fully reflected by the current materialized progress projection.</summary>
    public long ProjectionVersion { get; set; }

    /// <summary>Clock instant through which time-driven projection state is reconciled. UTC instant.</summary>
    public DateTimeOffset ProjectionAsOfAt { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }

    /// <summary>SQL-generated opaque concurrency token; compare as bytes, not as a clock.</summary>
    public byte[] RowVersion { get; set; } = [];

    /// <summary>Whether bounded recurrence delivery has more work at the latest requested clock; ProjectionAsOfAt advances only when that work is complete.</summary>
    public bool HasPendingReconciliation { get; set; }
}
