// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one current account/category streak and explicit pause setting. Classification: Restricted. History: projection; Current projection plus explicit category switch; source pause intervals are retained. Erase with account.</summary>
public sealed class CategoryProgressEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Category whose streak is displayed.</summary>
    public string CategoryId { get; set; } = string.Empty;

    /// <summary>Nonnegative category streak length under pause/zone history.</summary>
    public int StreakDays { get; set; }

    /// <summary>Integer category streak bonus percentage, from 0 through the approved maximum 20 under PQ-MVP-013.</summary>
    public int BonusRatePercent { get; set; }

    /// <summary>Whether the account qualified in this category on AsOfDate.</summary>
    public bool HasQualifiedToday { get; set; }

    /// <summary>Current explicit category-pause switch; distinct from the account-wide switch.</summary>
    public bool IsExplicitlyPaused { get; set; }

    /// <summary>Account-calendar date used for the current-day flag.</summary>
    public DateOnly AsOfDate { get; set; }

    /// <summary>IANA timezone used for AsOfDate.</summary>
    public string TimeZoneId { get; set; } = string.Empty;

    /// <summary>Account projection generation of this summary.</summary>
    public long ProjectionVersion { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }
}
