// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one minimal verified deletion marker consisting only of opaque Identity ID and deletion time. Classification: Restricted. History: marker; Retain exactly 35 elapsed days after original verified live erasure, then remove. CreatedAt is the sole deletion/marker-creation clock and is preserved across restore and retry. External authoritative copies must survive backups and obey the same minimum-content policy.</summary>
public sealed class ErasureMarkerEntity
{
    /// <summary>Canonical never-recycled Identity user ID used for restore fencing; intentionally no FK to deleted personal data.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Original verified live-erasure and marker-creation instant, written atomically with successful purge. The writer supplies this canonical value; restore/import must preserve it and duplicate delivery must not update it. Retention expires exactly 35 elapsed days after this instant, never after restore or retry. UTC instant.</summary>
    public DateTimeOffset CreatedAt { get; set; }
}
