// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one short-lived acknowledgment-envelope ownership binding for private Identity delivery. Classification: Restricted. History: plumbing; Delete after dispatch or within one hour. May outlive Account only long enough to complete the current private acknowledgment.</summary>
public sealed class LifecycleMessageEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Canonical external user whose lifecycle acknowledgment this is.</summary>
    public string IdentityUserId { get; set; } = string.Empty;

    /// <summary>Product account if still present; null before onboarding or after purge.</summary>
    public Guid? AccountId { get; set; }

    /// <summary>Identity transition version being acknowledged.</summary>
    public long LifecycleVersion { get; set; }

    /// <summary>Shared Data.Outbox row containing the acknowledgment capability and payload.</summary>
    public Guid OutboxMessageId { get; set; }

    /// <summary>Hard delivery-envelope expiration; maximum one hour after creation, matching current protocol. UTC instant.</summary>
    public DateTimeOffset ExpiresAt { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }
}
