// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one public achievement, badge or frame definition. Classification: Public. History: reference; Retain referenced reward codes; history is the versioned catalog. Not erased with accounts.</summary>
public sealed class ProfileRewardEntity
{
    /// <summary>Stable reward code, including existing A01/A02/B01/B02/F01/F02 IDs.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Achievement, Badge or Frame; only Badge and Frame are selectable.</summary>
    public string KindCode { get; set; } = string.Empty;

    /// <summary>Public display name of this reward.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Nonnegative qualifying count in the versioned reward rule.</summary>
    public int RequiredCount { get; set; }

    /// <summary>Minimum global rank in the versioned reward rule.</summary>
    public string RequiredRank { get; set; } = string.Empty;

    /// <summary>Reviewed catalog/ruleset version that defines the qualifying predicate.</summary>
    public string RulesetVersion { get; set; } = string.Empty;

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }
}
