// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one immutable successful completion with at most one write-once Undo annotation. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class QuestCompletionEntity
{
    /// <summary>UUID of its Completed occurrence event and stable completion identifier.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Occurrence completed by this fact.</summary>
    public Guid QuestOccurrenceId { get; set; }

    /// <summary>Exact completed terms; never replaced by a later definition edit.</summary>
    public Guid QuestOccurrenceRevisionId { get; set; }

    /// <summary>Trusted recorded completion time, including validated offline time. UTC instant.</summary>
    public DateTimeOffset RecordedAt { get; set; }

    /// <summary>Trusted recorded Undo time, if the completion was reversed. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? UndoneAt { get; set; }

    /// <summary>Stable Undone event; null exactly when UndoneAt is null.</summary>
    public Guid? UndoQuestOccurrenceEventId { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }

    /// <summary>SQL-generated opaque concurrency token; compare as bytes, not as a clock.</summary>
    public byte[] RowVersion { get; set; } = [];
}
