// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one immutable content/reward version of an account quest definition. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class QuestDefinitionRevisionEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Definition to which this immutable revision belongs.</summary>
    public Guid QuestDefinitionId { get; set; }

    /// <summary>Positive sequence within this definition.</summary>
    public int Revision { get; set; }

    /// <summary>Frozen trimmed quest title, 1 to 120 characters.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Frozen self-attestation criterion, 1 to 2000 characters; may contain personal content.</summary>
    public string Criterion { get; set; } = string.Empty;

    /// <summary>Frozen optional quest explanation. Null means none was supplied.</summary>
    public string? Description { get; set; }

    /// <summary>Frozen category of this content revision.</summary>
    public string CategoryId { get; set; } = string.Empty;

    /// <summary>Frozen quest rank F/E/D/C/B/A/S.</summary>
    public string RankCode { get; set; } = string.Empty;

    /// <summary>Frozen Small, Medium or Large effort tier.</summary>
    public string EffortCode { get; set; } = string.Empty;

    /// <summary>Calibrated nonnegative base XP under the frozen ruleset; never client-authoritative.</summary>
    public long BaseXp { get; set; }

    /// <summary>Proposed penalty percentage for new acceptance: 0, 10, 25 or 50. Accepted losses are separately locked.</summary>
    public byte PenaltyPercent { get; set; }

    /// <summary>Frozen ruleset version used to derive rewards.</summary>
    public string RulesetVersion { get; set; } = string.Empty;

    /// <summary>Schema version of the immutable display-label document.</summary>
    public short DisplaySnapshotVersion { get; set; }

    /// <summary>Frozen human-readable names for historical display/export only; typed references and allocations enforce rules. Maximum 65536 UTF-16 bytes.</summary>
    public string DisplaySnapshotJson { get; set; } = string.Empty;

    /// <summary>Time the new content revision became effective. UTC instant.</summary>
    public DateTimeOffset EffectiveAt { get; set; }

    /// <summary>Receipt for the command that caused this fact. Null means trusted clock/lifecycle reconciliation, not a client command.</summary>
    public Guid? CommandReceiptId { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }
}
