// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one ordered category selected by a successful interests command, retained only to reconstruct its historical response. Classification: Restricted. History: immutable. Erase with its account; no age cutoff on replay history.</summary>
public sealed class QuestCommandInterestEntity
{
    /// <summary>Owning account, shared with the parent history row.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Immutable interests transition owning this selected category.</summary>
    public Guid QuestCommandHistoryId { get; set; }

    /// <summary>Selected public category code.</summary>
    public string CategoryId { get; set; } = string.Empty;

    /// <summary>Original distinct selection order, matching the existing profile array.</summary>
    public int Position { get; set; }

    /// <summary>UTC server insertion instant.</summary>
    public DateTimeOffset CreatedAt { get; set; }
}
