// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one immutable recurrence configuration and consent state. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class QuestSeriesRevisionEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Series to which this version belongs.</summary>
    public Guid QuestSeriesId { get; set; }

    /// <summary>Positive configuration sequence within a series.</summary>
    public int Revision { get; set; }

    /// <summary>Frozen terms scheduled by this version.</summary>
    public Guid QuestDefinitionRevisionId { get; set; }

    /// <summary>Calendar recurrence unit: Days, Weeks, Months or Years.</summary>
    public string CadenceCode { get; set; } = string.Empty;

    /// <summary>Calendar-unit interval 1..999, matching current validation.</summary>
    public int Interval { get; set; }

    /// <summary>First delivery date in the selected account calendar; must precede year 9999.</summary>
    public DateOnly AnchorOn { get; set; }

    /// <summary>Optional local planned clock time, not the completion deadline. Null means no planned time.</summary>
    public TimeOnly? PlannedTime { get; set; }

    /// <summary>Explicit consent to automatically accept this version of recurring penalty terms.</summary>
    public bool HasAutoAcceptPenalty { get; set; }

    /// <summary>When this configuration became effective. UTC instant.</summary>
    public DateTimeOffset EffectiveAt { get; set; }

    /// <summary>Receipt for the command that caused this fact.</summary>
    public Guid CommandReceiptId { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Public domain schedule version; internal revision also changes when definition terms change without editing recurrence.</summary>
    public int ScheduleVersion { get; set; }
}
