// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one opted-in recurrence series and its durable delivery cursor. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class QuestSeriesEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Quest identity delivered by this recurrence series.</summary>
    public Guid QuestDefinitionId { get; set; }

    /// <summary>Current immutable series configuration revision.</summary>
    public int Revision { get; set; }

    /// <summary>Next nonnegative sequence within the current series revision.</summary>
    public int NextSequence { get; set; }

    /// <summary>Nonnegative local-calendar days shifted by effective pauses.</summary>
    public int PauseDays { get; set; }

    /// <summary>Next delivery date in the selected account calendar; null when stopped or no representable next date.</summary>
    public DateOnly? NextDeliveryOn { get; set; }

    /// <summary>Time recurrence was explicitly stopped; stopped series are never silently restarted. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? StoppedAt { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }

    /// <summary>SQL-generated opaque concurrency token; compare as bytes, not as a clock.</summary>
    public byte[] RowVersion { get; set; } = [];

    /// <summary>Stable one-based position in the existing API array, set once at creation; zero is reserved for public catalog adoption or the retained v1 adapter.</summary>
    public int CreationOrdinal { get; set; }
}
