// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one immutable occurrence version visible at a committed account mutation. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class QuestOccurrenceRevisionEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>Occurrence whose terms and scheduling state this version captures.</summary>
    public Guid QuestOccurrenceId { get; set; }

    /// <summary>Positive version within this occurrence.</summary>
    public int Revision { get; set; }

    /// <summary>Persistent account-owned definition identity.</summary>
    public Guid QuestDefinitionId { get; set; }

    /// <summary>Exact immutable content/reward revision used by this occurrence version.</summary>
    public Guid QuestDefinitionRevisionId { get; set; }

    /// <summary>Materialized current/frozen category for filtering, constrained to the controlled revision write.</summary>
    public string CategoryId { get; set; } = string.Empty;

    /// <summary>Due date in DeadlineTimeZoneId; null means unscheduled with no deadline.</summary>
    public DateOnly? DueOn { get; set; }

    /// <summary>Optional local planned clock time; null means none; requires DueOn.</summary>
    public TimeOnly? PlannedTime { get; set; }

    /// <summary>Absolute end-of-due-day deadline; null for unscheduled occurrence. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? DeadlineAt { get; set; }

    /// <summary>IANA calendar zone used to calculate DueOn/DeadlineAt. Null only for unscheduled occurrence.</summary>
    public string? DeadlineTimeZoneId { get; set; }

    /// <summary>Active, Completed, Missed, Frozen, Abandoned or Offered; time-dependent projection can be newer than persisted reconciliation.</summary>
    public string StateCode { get; set; } = string.Empty;

    /// <summary>Recorded acceptance time; null while only an unaccepted offer. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? AcceptedAt { get; set; }

    /// <summary>Start of the current freeze, if any. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? FrozenAt { get; set; }

    /// <summary>Whether an individual freeze remains after account/category resume.</summary>
    public bool IsIndividuallyFrozen { get; set; }

    /// <summary>Explicit abandonment time, if any. UTC instant. Null means this event has not happened.</summary>
    public DateTimeOffset? AbandonedAt { get; set; }

    /// <summary>Exact accepted nonnegative penalty amount. Null means no penalty commitment.</summary>
    public long? LockedLoss { get; set; }

    /// <summary>Category frozen with an accepted loss; null exactly when LockedLoss is null.</summary>
    public string? LossCategoryId { get; set; }

    /// <summary>Visibility order at commit; distinct from backdated EffectiveAt.</summary>
    public long AccountMutationVersion { get; set; }

    /// <summary>Recorded effective time of the transition. UTC instant.</summary>
    public DateTimeOffset EffectiveAt { get; set; }

    /// <summary>Receipt for the command that caused this fact. Null means trusted clock/lifecycle reconciliation, not a client command.</summary>
    public Guid? CommandReceiptId { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Original occurrence creation/delivery instant used by the domain even while the recurring occurrence is still an unaccepted offer. Null means not applicable to this transition.</summary>
    public DateTimeOffset? OriginatedAt { get; set; }

    /// <summary>Original domain/API display offset of OriginatedAt, retained separately from its authoritative UTC instant for exact recurring-offer response reconstruction.</summary>
    public short OriginatedOffsetMinutes { get; set; }
}
