// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one canonical system skill. Classification: Public. History: reference; Retain stable codes indefinitely; source control owns reference history. Not erased with accounts.</summary>
public sealed class SkillEntity
{
    /// <summary>Stable public catalog code; preserve existing IDs and ordinal allocation tie-breaking.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Current public catalog display name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Version of the reviewed catalog that supplied this row.</summary>
    public string CatalogVersion { get; set; } = string.Empty;

    /// <summary>Positive canonical display order; not an independently chosen progression priority.</summary>
    public int SortOrder { get; set; }

    /// <summary>Reserved system skill name normalized by the versioned OrdinalIgnoreCase-equivalent normalizer; compare with BIN2 collation.</summary>
    public string NormalizedName { get; set; } = string.Empty;

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Server UTC time of the most recent persisted change; writer must set on each update.</summary>
    public DateTimeOffset ModifiedAt { get; set; }
}
