// <auto-generated />
#nullable enable

namespace PocketQuests.Data.Relational.Entities;

/// <summary>One row is one replacement experience placement effective at a recorded time. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.</summary>
public sealed class SkillAssessmentEntity
{
    /// <summary>Application-generated stable row UUID; never reused.</summary>
    public Guid Id { get; set; }

    /// <summary>Pocket Quests account that exclusively owns this row; supplied by trusted server context.</summary>
    public Guid AccountId { get; set; }

    /// <summary>System skill being referenced; null when CustomSkillId is supplied.</summary>
    public string? SystemSkillId { get; set; }

    /// <summary>Custom skill owned by this account; null when SystemSkillId is supplied.</summary>
    public Guid? CustomSkillId { get; set; }

    /// <summary>New, Practiced, Experienced or Expert placement; this is not earned XP.</summary>
    public string ExperienceCode { get; set; } = string.Empty;

    /// <summary>Exact placement component under RulesetVersion; replaces the prior seed without granting other pools.</summary>
    public long SeedXp { get; set; }

    /// <summary>Rules version that maps experience placement to seed XP.</summary>
    public string RulesetVersion { get; set; } = string.Empty;

    /// <summary>Recorded placement time. UTC instant.</summary>
    public DateTimeOffset EffectiveAt { get; set; }

    /// <summary>Receipt for the command that caused this fact.</summary>
    public Guid CommandReceiptId { get; set; }

    /// <summary>Server UTC insertion time; not the effective time of a delayed offline action.</summary>
    public DateTimeOffset CreatedAt { get; set; }
}
