-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[CommandReceipt] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [CommandType] varchar(80) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [ApiVersion] smallint NOT NULL,
    [PayloadDigest] binary(32) NOT NULL,
    [DigestVersion] smallint NOT NULL,
    [OutcomeVersion] smallint NOT NULL,
    [OutcomeJson] nvarchar(max) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [AppliedMutationVersion] bigint NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_CommandReceipt_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_CommandReceipt] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_CommandReceipt_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_CommandReceipt_ApiVersion] CHECK ([ApiVersion] >= 1),
    CONSTRAINT [CK_CommandReceipt_DigestVersion] CHECK ([DigestVersion] >= 1),
    CONSTRAINT [CK_CommandReceipt_OutcomeVersion] CHECK ([OutcomeVersion] >= 1),
    CONSTRAINT [CK_CommandReceipt_AppliedMutationVersion] CHECK ([AppliedMutationVersion] >= 0),
    CONSTRAINT [CK_CommandReceipt_OutcomeDocument] CHECK (ISJSON([OutcomeJson])=1 AND DATALENGTH([OutcomeJson])<=65536),
    CONSTRAINT [CK_CommandReceipt_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [FK_CommandReceipt_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one immutable original outcome of a committed account command. Classification: Restricted. History: plumbing; Retain compact outcome and deduplication digest while the account exists. Delete at final account erasure; no replay TTL.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable client operation UUID; unchanged across retries.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Typed command discriminator under the stored API contract version.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'CommandType';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive version of the accepted wire command contract.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'ApiVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SHA-256 of the versioned canonical command representation, excluding authentication secrets.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'PayloadDigest';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive canonicalization/digest schema version; never hash incidental serializer output.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'DigestVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive schema version of the compact original command outcome.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'OutcomeVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Immutable compact original result and feedback, never the whole account or raw provider credentials. Limited to 65536 UTF-16 bytes.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'OutcomeJson';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Committed account mutation represented by this outcome; unchanged on retry.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'AppliedMutationVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'CommandReceipt', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
