-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[SyncAnchor] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [DeviceId] uniqueidentifier NOT NULL,
    [BootId] uniqueidentifier NOT NULL,
    [ServerAt] datetimeoffset(7) NOT NULL,
    [DeviceAt] datetimeoffset(7) NOT NULL,
    [RecordedTimeFloorAt] datetimeoffset(7) NOT NULL,
    [IssuedMutationVersion] bigint NOT NULL,
    [LastOrdinal] bigint NOT NULL CONSTRAINT [DF_SyncAnchor_LastOrdinal] DEFAULT (0),
    [LastElapsedMilliseconds] float(53) NOT NULL CONSTRAINT [DF_SyncAnchor_LastElapsedMilliseconds] DEFAULT (0),
    [InvalidatedAt] datetimeoffset(7) NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_SyncAnchor_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_SyncAnchor_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    CONSTRAINT [PK_SyncAnchor] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_SyncAnchor_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_SyncAnchor_IssuedMutationVersion] CHECK ([IssuedMutationVersion] >= 0),
    CONSTRAINT [CK_SyncAnchor_LastOrdinal] CHECK ([LastOrdinal] >= 0),
    CONSTRAINT [CK_SyncAnchor_LastElapsedMilliseconds] CHECK ([LastElapsedMilliseconds] >= 0),
    CONSTRAINT [CK_SyncAnchor_ServerAtUtc] CHECK (DATEPART(TZOFFSET,[ServerAt])=0),
    CONSTRAINT [CK_SyncAnchor_DeviceAtUtc] CHECK (DATEPART(TZOFFSET,[DeviceAt])=0),
    CONSTRAINT [CK_SyncAnchor_RecordedTimeFloorAtUtc] CHECK (DATEPART(TZOFFSET,[RecordedTimeFloorAt])=0),
    CONSTRAINT [CK_SyncAnchor_InvalidatedAtUtc] CHECK ([InvalidatedAt] IS NULL OR DATEPART(TZOFFSET,[InvalidatedAt])=0),
    CONSTRAINT [CK_SyncAnchor_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_SyncAnchor_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_SyncAnchor_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_SyncAnchor_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION
);
GO
-- Locate proof history for one account/device/process; no independent expiry index.
CREATE INDEX [IX_SyncAnchor_DeviceProof] ON [pocketquests].[SyncAnchor] ([AccountId], [DeviceId], [BootId], [ServerAt]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one durable trusted clock/visibility proof for an account, device and process. Classification: Restricted. History: mutable; Retain compact proof while valid pending actions can reference it; no wall-clock expiry. Invalidate under lifecycle rules and erase with account. Safe retirement protocol is not implemented here.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Client device identifier, bound to the verified account; not an authentication credential.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'DeviceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Process-session identity used for monotonic clock proof; no silent rewrite across restarts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'BootId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Trusted server clock at proof issuance. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'ServerAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Device wall clock captured at issuance. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'DeviceAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Fixed issuance floor for already observed account history; never accumulated on refresh. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'RecordedTimeFloorAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account version whose visible immutable occurrence revisions this proof authenticates.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'IssuedMutationVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Largest committed ordinal under this proof.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'LastOrdinal';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Largest committed finite elapsed milliseconds under this proof. SQL float(53) preserves the existing API v1 IEEE-754 double, including fractional milliseconds; never rounded to an integer. Not money, XP, a wall clock or a duration added to the fixed issuance floor.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'LastElapsedMilliseconds';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Lifecycle revocation time; null means not explicitly revoked. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'InvalidatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Locate proof history for one account/device/process; no independent expiry index.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SyncAnchor', @level2type=N'INDEX', @level2name=N'IX_SyncAnchor_DeviceProof';
GO
