// <auto-generated />
#nullable enable
using System.Data;
using Microsoft.Data.SqlClient;
using PocketQuests.Data.Relational.Entities;

namespace PocketQuests.Data.Relational.Commands;

internal static class MutationBindings
{
    internal static void Bind<T>(SqlCommand sql, IEnumerable<T> rows) where T : class
    {
        var name = typeof(T).Name[..^6];
        var columns = name switch
        {
            "Account" => new[] { "Id", "IdentityUserId", "TimeZoneId", "IsOnboardingComplete", "HasExpiryWarnings", "IsAccountPaused", "SelectedBadgeId", "SelectedBadgeKind", "SelectedFrameId", "SelectedFrameKind", "LastRecordedAt", "MutationVersion", "ProjectionVersion", "ProjectionAsOfAt", "CreatedAt", "ModifiedAt", "HasPendingReconciliation" },
            "CustomSkill" => new[] { "Id", "AccountId", "Name", "NormalizedName", "NameNormalizationVersion", "Revision", "ArchivedAt", "CreatedAt", "ModifiedAt", "CreationOrdinal", "ClientKey" },
            "QuestDefinition" => new[] { "Id", "AccountId", "SystemQuestId", "Revision", "ArchivedAt", "CreatedAt", "ModifiedAt", "CreationOrdinal", "ClientKey" },
            "QuestDefinitionRevision" => new[] { "Id", "AccountId", "QuestDefinitionId", "Revision", "Title", "Criterion", "Description", "CategoryId", "RankCode", "EffortCode", "BaseXp", "PenaltyPercent", "RulesetVersion", "DisplaySnapshotVersion", "DisplaySnapshotJson", "EffectiveAt", "CommandReceiptId", "CreatedAt" },
            "QuestDefinitionAttributeAllocation" => new[] { "AccountId", "QuestDefinitionRevisionId", "AttributeId", "BasisPoints", "CreatedAt", "Position" },
            "QuestDefinitionSkillAllocation" => new[] { "Id", "AccountId", "QuestDefinitionRevisionId", "SystemSkillId", "CustomSkillId", "BasisPoints", "CreatedAt", "Position" },
            "QuestSeries" => new[] { "Id", "AccountId", "QuestDefinitionId", "Revision", "NextSequence", "PauseDays", "NextDeliveryOn", "StoppedAt", "CreatedAt", "ModifiedAt", "CreationOrdinal" },
            "QuestSeriesRevision" => new[] { "Id", "AccountId", "QuestSeriesId", "Revision", "QuestDefinitionRevisionId", "CadenceCode", "Interval", "AnchorOn", "PlannedTime", "HasAutoAcceptPenalty", "EffectiveAt", "CommandReceiptId", "CreatedAt", "ScheduleVersion" },
            "QuestOccurrence" => new[] { "Id", "AccountId", "QuestDefinitionId", "QuestDefinitionRevisionId", "CategoryId", "DueOn", "PlannedTime", "DeadlineAt", "DeadlineTimeZoneId", "StateCode", "AcceptedAt", "FrozenAt", "IsIndividuallyFrozen", "AbandonedAt", "LockedLoss", "LossCategoryId", "Revision", "QuestSeriesId", "QuestSeriesRevisionId", "SeriesSequence", "ParentQuestOccurrenceId", "SourceSyncAnchorId", "CreatedAt", "ModifiedAt", "OriginatedAt", "CreationOrdinal", "OriginatedOffsetMinutes" },
            "QuestOccurrenceRevision" => new[] { "Id", "AccountId", "QuestOccurrenceId", "Revision", "QuestDefinitionId", "QuestDefinitionRevisionId", "CategoryId", "DueOn", "PlannedTime", "DeadlineAt", "DeadlineTimeZoneId", "StateCode", "AcceptedAt", "FrozenAt", "IsIndividuallyFrozen", "AbandonedAt", "LockedLoss", "LossCategoryId", "AccountMutationVersion", "EffectiveAt", "CommandReceiptId", "CreatedAt", "OriginatedAt", "OriginatedOffsetMinutes" },
            "QuestOccurrenceEvent" => new[] { "Id", "AccountId", "QuestOccurrenceId", "QuestOccurrenceRevisionId", "EventCode", "EffectiveAt", "AccountMutationVersion", "CommandReceiptId", "CreatedAt" },
            "QuestCompletion" => new[] { "Id", "AccountId", "QuestOccurrenceId", "QuestOccurrenceRevisionId", "RecordedAt", "UndoneAt", "UndoQuestOccurrenceEventId", "CreatedAt", "ModifiedAt" },
            "AccountPause" => new[] { "Id", "AccountId", "ScopeCode", "CategoryId", "StartedAt", "EndedAt", "CommandReceiptId", "CreatedAt", "ModifiedAt", "CreationOrdinal" },
            "TimeZoneChange" => new[] { "Id", "AccountId", "FromTimeZoneId", "ToTimeZoneId", "EffectiveAt", "CommandReceiptId", "CreatedAt" },
            "SkillAssessment" => new[] { "Id", "AccountId", "SystemSkillId", "CustomSkillId", "ExperienceCode", "SeedXp", "RulesetVersion", "EffectiveAt", "CommandReceiptId", "CreatedAt" },
            "QuestCommandHistory" => new[] { "Id", "AccountId", "CommandReceiptId", "AccountMutationVersion", "ActionCode", "RulesetVersion", "TimeZoneBefore", "ReconciledAt", "RecordedAt", "ProjectionAt", "QuestOccurrenceId", "QuestCompletionId", "QuestDefinitionRevisionId", "CompletionTermsRevisionId", "ExpectedRevision", "SystemSkillId", "CustomSkillId", "SkillName", "ExperienceCode", "DueOn", "PlannedTime", "ParentQuestOccurrenceId", "ProfileRewardId", "QuestSeriesId", "CadenceCode", "Interval", "CategoryId", "ConfirmPenalty", "AcceptedLoss", "HasAcceptedTerms", "NewTimeZone", "ExpectedTimeZone", "ConfirmZoneChange", "HasExpiryWarnings", "SourceSyncAnchorId", "CreatedAt", "ReconciliationLimit", "ActionReconciliationLimit" },
            "QuestCommandInterest" => new[] { "AccountId", "QuestCommandHistoryId", "CategoryId", "Position", "CreatedAt" },
            "AccountInterest" => new[] { "AccountId", "CategoryId", "CreatedAt", "Position" },
            "XpLedgerEntry" => new[] { "Id", "AccountId", "QuestOccurrenceEventId", "ContributionCode", "TrackCode", "CategoryId", "AttributeId", "SystemSkillId", "CustomSkillId", "EffectiveAt", "Amount", "ProjectionVersion", "RulesetVersion", "CreatedAt", "ModifiedAt" },
            "XpBalance" => new[] { "Id", "AccountId", "TrackCode", "CategoryId", "AttributeId", "SystemSkillId", "CustomSkillId", "EarnedXp", "SeedXp", "Level", "ProjectionVersion", "CreatedAt", "ModifiedAt" },
            "CategoryProgress" => new[] { "Id", "AccountId", "CategoryId", "StreakDays", "BonusRatePercent", "HasQualifiedToday", "IsExplicitlyPaused", "AsOfDate", "TimeZoneId", "ProjectionVersion", "CreatedAt", "ModifiedAt" },
            "AccountEntitlement" => new[] { "Id", "AccountId", "ProfileRewardId", "QualifyingCount", "IsEarned", "ProjectionVersion", "RulesetVersion", "CreatedAt", "ModifiedAt" },
            _ => throw new InvalidOperationException("Entity is not in the reviewed command mutation policy."),
        };
        var table = new DataTable { Locale = System.Globalization.CultureInfo.InvariantCulture };
        var properties = columns.Select(name => typeof(T).GetProperty(name)!).ToArray();
        foreach (var property in properties)
        {
            var type = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
            table.Columns.Add(property.Name, type == typeof(DateOnly) ? typeof(DateTime) : type == typeof(TimeOnly) ? typeof(TimeSpan) : type);
        }
        foreach (var row in rows)
            table.Rows.Add(properties.Select(property => property.GetValue(row) switch { DateOnly date => date.ToDateTime(TimeOnly.MinValue), TimeOnly time => time.ToTimeSpan(), DateTimeOffset instant => instant.ToUniversalTime(), null => DBNull.Value, var value => value }).ToArray());
        var parameter = sql.Parameters.Add("@" + name, SqlDbType.Structured);
        parameter.TypeName = "pocketquests." + name + "MutationInput";
        parameter.Value = table;
    }

    internal static async Task<MutationBatch> Read(RelationalQuestReadContext db, AccountEntity account, CancellationToken token)
    {
        var batch = new MutationBatch();
        var accountId = account.Id;
        batch.Seed(new[] { account });
        await batch.Load<CustomSkillEntity>(db, accountId, token);
        await batch.Load<QuestDefinitionEntity>(db, accountId, token);
        await batch.Load<QuestDefinitionRevisionEntity>(db, accountId, token);
        await batch.Load<QuestDefinitionAttributeAllocationEntity>(db, accountId, token);
        await batch.Load<QuestDefinitionSkillAllocationEntity>(db, accountId, token);
        await batch.Load<QuestSeriesEntity>(db, accountId, token);
        await batch.Load<QuestSeriesRevisionEntity>(db, accountId, token);
        await batch.Load<QuestOccurrenceEntity>(db, accountId, token);
        await batch.Load<QuestOccurrenceRevisionEntity>(db, accountId, token);
        await batch.Load<QuestOccurrenceEventEntity>(db, accountId, token);
        await batch.Load<QuestCompletionEntity>(db, accountId, token);
        await batch.Load<AccountPauseEntity>(db, accountId, token);
        await batch.Load<TimeZoneChangeEntity>(db, accountId, token);
        await batch.Load<SkillAssessmentEntity>(db, accountId, token);
        batch.Seed(Array.Empty<QuestCommandHistoryEntity>());
        batch.Seed(Array.Empty<QuestCommandInterestEntity>());
        await batch.Load<AccountInterestEntity>(db, accountId, token);
        await batch.Load<XpLedgerEntryEntity>(db, accountId, token);
        await batch.Load<XpBalanceEntity>(db, accountId, token);
        await batch.Load<CategoryProgressEntity>(db, accountId, token);
        await batch.Load<AccountEntitlementEntity>(db, accountId, token);
        return batch;
    }

    internal static void BindAll(SqlCommand sql, MutationBatch batch)
    {
        Bind(sql, batch.Rows<AccountEntity>());
        Bind(sql, batch.Rows<CustomSkillEntity>());
        Bind(sql, batch.Rows<QuestDefinitionEntity>());
        Bind(sql, batch.Rows<QuestDefinitionRevisionEntity>());
        Bind(sql, batch.Rows<QuestDefinitionAttributeAllocationEntity>());
        Bind(sql, batch.Rows<QuestDefinitionSkillAllocationEntity>());
        Bind(sql, batch.Rows<QuestSeriesEntity>());
        Bind(sql, batch.Rows<QuestSeriesRevisionEntity>());
        Bind(sql, batch.Rows<QuestOccurrenceEntity>());
        Bind(sql, batch.Rows<QuestOccurrenceRevisionEntity>());
        Bind(sql, batch.Rows<QuestOccurrenceEventEntity>());
        Bind(sql, batch.Rows<QuestCompletionEntity>());
        Bind(sql, batch.Rows<AccountPauseEntity>());
        Bind(sql, batch.Rows<TimeZoneChangeEntity>());
        Bind(sql, batch.Rows<SkillAssessmentEntity>());
        Bind(sql, batch.Rows<QuestCommandHistoryEntity>());
        Bind(sql, batch.Rows<QuestCommandInterestEntity>());
        Bind(sql, batch.Rows<AccountInterestEntity>());
        Bind(sql, batch.Rows<XpLedgerEntryEntity>());
        Bind(sql, batch.Rows<XpBalanceEntity>());
        Bind(sql, batch.Rows<CategoryProgressEntity>());
        Bind(sql, batch.Rows<AccountEntitlementEntity>());
    }

    internal static string[] Keys(string name) => name switch
    {
        "Account" => new[] { "Id" },
        "CustomSkill" => new[] { "Id" },
        "QuestDefinition" => new[] { "Id" },
        "QuestDefinitionRevision" => new[] { "Id" },
        "QuestDefinitionAttributeAllocation" => new[] { "AccountId", "QuestDefinitionRevisionId", "AttributeId" },
        "QuestDefinitionSkillAllocation" => new[] { "Id" },
        "QuestSeries" => new[] { "Id" },
        "QuestSeriesRevision" => new[] { "Id" },
        "QuestOccurrence" => new[] { "Id" },
        "QuestOccurrenceRevision" => new[] { "Id" },
        "QuestOccurrenceEvent" => new[] { "Id" },
        "QuestCompletion" => new[] { "Id" },
        "AccountPause" => new[] { "Id" },
        "TimeZoneChange" => new[] { "Id" },
        "SkillAssessment" => new[] { "Id" },
        "QuestCommandHistory" => new[] { "Id" },
        "QuestCommandInterest" => new[] { "AccountId", "QuestCommandHistoryId", "CategoryId" },
        "AccountInterest" => new[] { "AccountId", "CategoryId" },
        "XpLedgerEntry" => new[] { "Id" },
        "XpBalance" => new[] { "Id" },
        "CategoryProgress" => new[] { "Id" },
        "AccountEntitlement" => new[] { "Id" },
        _ => throw new InvalidOperationException("Unknown mutation entity."),
    };

    internal static bool Replaces(string name) => name is "AccountInterest" or "XpLedgerEntry" or "XpBalance" or "CategoryProgress" or "AccountEntitlement";
}
