-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[AccountLifecycleState] (
    [Id] uniqueidentifier NOT NULL,
    [IdentityUserId] varchar(30) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [AccountId] uniqueidentifier NULL,
    [Version] bigint NOT NULL,
    [StateCode] varchar(8) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [EffectiveAt] datetimeoffset(7) NOT NULL,
    [PausedAt] datetimeoffset(7) NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_AccountLifecycleState_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_AccountLifecycleState_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    CONSTRAINT [PK_AccountLifecycleState] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_AccountLifecycleState_IdentityUserId] UNIQUE ([IdentityUserId]),
    CONSTRAINT [CK_AccountLifecycleState_Version] CHECK ([Version] >= 0),
    CONSTRAINT [CK_AccountLifecycleState_StateCode] CHECK ([StateCode] IN ('Active','Inactive','Erasing')),
    CONSTRAINT [CK_AccountLifecycleState_PauseOrder] CHECK ([PausedAt] IS NULL OR [PausedAt]<=[EffectiveAt]),
    CONSTRAINT [CK_AccountLifecycleState_EffectiveAtUtc] CHECK (DATEPART(TZOFFSET,[EffectiveAt])=0),
    CONSTRAINT [CK_AccountLifecycleState_PausedAtUtc] CHECK ([PausedAt] IS NULL OR DATEPART(TZOFFSET,[PausedAt])=0),
    CONSTRAINT [CK_AccountLifecycleState_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_AccountLifecycleState_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_AccountLifecycleState_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [CK_AccountLifecycleState_IdentityUserId] CHECK (DATALENGTH([IdentityUserId])=30 AND LEFT([IdentityUserId],4)='usr_' AND SUBSTRING([IdentityUserId],5,26) NOT LIKE '%[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]%' COLLATE Latin1_General_100_BIN2),
    CONSTRAINT [FK_AccountLifecycleState_Account] FOREIGN KEY ([AccountId], [IdentityUserId]) REFERENCES [pocketquests].[Account] ([Id], [IdentityUserId]) ON DELETE NO ACTION
);
GO
-- At most one lifecycle fence attached to a local profile.
CREATE UNIQUE INDEX [UQ_AccountLifecycleState_Account] ON [pocketquests].[AccountLifecycleState] ([AccountId]) WHERE [AccountId] IS NOT NULL;
GO
-- Supports FK_AccountLifecycleState_Account parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_AccountLifecycleState_FK_Account] ON [pocketquests].[AccountLifecycleState] ([AccountId], [IdentityUserId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one latest accepted lifecycle fence for a canonical Identity user, possibly before onboarding. Classification: Restricted. History: mutable; Retain while required to fence the account/pre-onboarding identity. On verified erasure replace with minimal marker; no content history.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canonical external Identity user being fenced; never a provider identity.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'IdentityUserId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Local product profile if one exists; null before onboarding or after purge.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Highest accepted monotonic Identity lifecycle version; old deliveries cannot reduce it.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'Version';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Active, Inactive or Erasing, as defined by the reviewed Identity lifecycle contract.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'StateCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Authoritative Identity transition instant. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'EffectiveAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original deletion-request pause origin, retained across cancellation. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'PausedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'At most one lifecycle fence attached to a local profile.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'INDEX', @level2name=N'UQ_AccountLifecycleState_Account';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_AccountLifecycleState_Account parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'AccountLifecycleState', @level2type=N'INDEX', @level2name=N'IX_AccountLifecycleState_FK_Account';
GO
