-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[LifecycleMessage] (
    [Id] uniqueidentifier NOT NULL,
    [IdentityUserId] varchar(30) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [AccountId] uniqueidentifier NULL,
    [LifecycleVersion] bigint NOT NULL,
    [OutboxMessageId] uniqueidentifier NOT NULL,
    [ExpiresAt] datetimeoffset(7) NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_LifecycleMessage_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_LifecycleMessage] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_LifecycleMessage_OutboxMessageId] UNIQUE ([OutboxMessageId]),
    CONSTRAINT [CK_LifecycleMessage_LifecycleVersion] CHECK ([LifecycleVersion] >= 1),
    CONSTRAINT [CK_LifecycleMessage_Expiry] CHECK ([ExpiresAt]>[CreatedAt] AND [ExpiresAt]<=DATEADD(hour,1,[CreatedAt])),
    CONSTRAINT [CK_LifecycleMessage_ExpiresAtUtc] CHECK (DATEPART(TZOFFSET,[ExpiresAt])=0),
    CONSTRAINT [CK_LifecycleMessage_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_LifecycleMessage_IdentityUserId] CHECK (DATALENGTH([IdentityUserId])=30 AND LEFT([IdentityUserId],4)='usr_' AND SUBSTRING([IdentityUserId],5,26) NOT LIKE '%[^0123456789ABCDEFGHJKMNPQRSTVWXYZ]%' COLLATE Latin1_General_100_BIN2),
    CONSTRAINT [FK_LifecycleMessage_Account] FOREIGN KEY ([AccountId], [IdentityUserId]) REFERENCES [pocketquests].[Account] ([Id], [IdentityUserId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_LifecycleMessage_OutboxMessages] FOREIGN KEY ([OutboxMessageId]) REFERENCES [outbox].[OutboxMessages] ([Id]) ON DELETE NO ACTION
);
GO
-- Erase/inspect user-owned delivery envelopes without JSON substring matching.
CREATE INDEX [IX_LifecycleMessage_OwnerVersion] ON [pocketquests].[LifecycleMessage] ([IdentityUserId], [LifecycleVersion]);
GO
-- Bounded expiry cleanup for delivery bindings.
CREATE INDEX [IX_LifecycleMessage_Retention] ON [pocketquests].[LifecycleMessage] ([ExpiresAt], [Id]);
GO
-- Supports FK_LifecycleMessage_Account parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_LifecycleMessage_FK_Account] ON [pocketquests].[LifecycleMessage] ([AccountId], [IdentityUserId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one short-lived acknowledgment-envelope ownership binding for private Identity delivery. Classification: Restricted. History: plumbing; Delete after dispatch or within one hour. May outlive Account only long enough to complete the current private acknowledgment.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canonical external user whose lifecycle acknowledgment this is.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'IdentityUserId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Product account if still present; null before onboarding or after purge.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Identity transition version being acknowledged.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'LifecycleVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Shared Data.Outbox row containing the acknowledgment capability and payload.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'OutboxMessageId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Hard delivery-envelope expiration; maximum one hour after creation, matching current protocol. UTC instant.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'ExpiresAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Erase/inspect user-owned delivery envelopes without JSON substring matching.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'INDEX', @level2name=N'IX_LifecycleMessage_OwnerVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Bounded expiry cleanup for delivery bindings.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'INDEX', @level2name=N'IX_LifecycleMessage_Retention';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_LifecycleMessage_Account parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'LifecycleMessage', @level2type=N'INDEX', @level2name=N'IX_LifecycleMessage_FK_Account';
GO
