-- Generated by generate_mutation.py from this template and the reviewed typed mutation policy.
-- The internal service computes domain transitions; SQL owns account boundaries, source immutability,
-- optimistic serialization, proof consumption and the atomic receipt/history/projection/Audit unit.
CREATE PROCEDURE [pocketquests].[CommitAccountMutation]
    @IdentityUserId varchar(30), @ExpectedVersion bigint, @IsInternal bit = 0,
    @OperationId uniqueidentifier, @Action varchar(40), @Digest binary(32), @Outcome nvarchar(max),
    @RecordedAt datetimeoffset(7), @ProjectionAt datetimeoffset(7), @Now datetimeoffset(7),
    @AnchorId uniqueidentifier = NULL, @BootId uniqueidentifier = NULL,
    @Ordinal bigint = NULL, @Elapsed float(53) = NULL,
-- <parameters>
    @AuditId varchar(32), @AuditCategory int, @AuditOutcome int, @AuditOperation int,
    @AuditTenant varchar(100), @AuditCorrelation nvarchar(max) = NULL, @AuditChanges nvarchar(max), @AuditMetadata nvarchar(max)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @IsInternal=1 AND @Action='$lifecycle-pause'
    BEGIN
        IF COALESCE(IS_ROLEMEMBER('pocketquests_lifecycle_runtime'),0)<>1
           AND COALESCE(IS_ROLEMEMBER('db_owner'),0)<>1 AND COALESCE(IS_SRVROLEMEMBER('sysadmin'),0)<>1
            THROW 51300, 'Only the trusted lifecycle role can freeze an inactive account.', 1;
        EXEC [pocketquests].[AcquireAccountLock] @IdentityUserId;
        IF EXISTS(SELECT 1 FROM [pocketquests].[ErasureMarker] WHERE Id=@IdentityUserId)
            THROW 51103, 'Erased accounts cannot acquire new source history.', 1;
    END
    ELSE EXEC [pocketquests].[LockAccount] @IdentityUserId;
    DECLARE @accountKey uniqueidentifier, @version bigint, @last datetimeoffset(7);
    SELECT @accountKey=Id,@version=MutationVersion,@last=LastRecordedAt
        FROM [pocketquests].[Account] WHERE IdentityUserId=@IdentityUserId;
    IF @accountKey IS NULL THROW 51104, 'Account was not initialized.', 1;
    IF @IsInternal=0 AND EXISTS (SELECT 1 FROM [pocketquests].[CommandReceipt] WHERE AccountId=@accountKey AND Id=@OperationId)
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM [pocketquests].[CommandReceipt]
            WHERE AccountId=@accountKey AND Id=@OperationId AND PayloadDigest=@Digest AND DigestVersion=1 AND ApiVersion=1 AND CommandType=@Action)
            THROW 51107, 'Operation ID already belongs to a different payload.', 1;
        RETURN;
    END;
    IF @ExpectedVersion IS NULL OR @version<>@ExpectedVersion THROW 51108, 'Account version changed.', 1;
    IF @OperationId IS NULL OR @OperationId='00000000-0000-0000-0000-000000000000' OR @IsInternal IS NULL OR @Action IS NULL
       OR (@IsInternal=1 AND @Action NOT IN ('$reconcile','$lifecycle-pause'))
       OR (@IsInternal=0 AND @Action IN ('$reconcile','$lifecycle-pause'))
        THROW 51109, 'An operation identifier is required.', 1;
    IF @RecordedAt IS NULL OR @ProjectionAt IS NULL OR @Now IS NULL
        THROW 51111, 'Explicit effective, projection and receipt clocks are required.', 1;
    IF @IsInternal=0 AND (@Outcome IS NULL OR ISJSON(@Outcome)<>1 OR DATALENGTH(@Outcome)>256
       OR EXISTS(SELECT 1 FROM OPENJSON(@Outcome) WHERE [key] NOT IN ('ProjectionAt','CompletionOutcome'))
       OR (SELECT COUNT_BIG(*) FROM OPENJSON(@Outcome))<>2
       OR NOT EXISTS(SELECT 1 FROM OPENJSON(@Outcome) WHERE [key]='CompletionOutcome' AND [type]=0)
       OR NOT EXISTS(SELECT 1 FROM OPENJSON(@Outcome) WHERE [key]='ProjectionAt' AND [type]=1)
       OR TRY_CONVERT(datetimeoffset(7),JSON_VALUE(@Outcome,'$.ProjectionAt')) IS NULL
       OR TRY_CONVERT(datetimeoffset(7),JSON_VALUE(@Outcome,'$.ProjectionAt'))<>@ProjectionAt)
        THROW 51110, 'Receipt must be a compact outcome.', 1;
    IF @IsInternal=0 AND @RecordedAt>DATEADD(second,5,@Now) THROW 51105, 'Server clock is not ready.', 1;
    IF @ProjectionAt<@RecordedAt OR @ProjectionAt<@Now OR @ProjectionAt<@last
        THROW 51111, 'Projection time cannot omit committed history.', 1;
    IF @AnchorId IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [pocketquests].[SyncAnchor]
        WHERE Id=@AnchorId AND AccountId=@accountKey AND BootId=@BootId AND InvalidatedAt IS NULL
          AND @Ordinal>LastOrdinal AND @Elapsed>=LastElapsedMilliseconds AND @Elapsed>=0
          AND @RecordedAt>=RecordedTimeFloorAt)
        THROW 51112, 'Proof is unavailable or already consumed.', 1;
    IF @IsInternal=1 AND (@AnchorId IS NOT NULL OR @Ordinal IS NOT NULL OR @Elapsed IS NOT NULL OR @BootId IS NOT NULL)
        THROW 51112, 'Internal reconciliation cannot consume a client proof.', 1;
    IF @AnchorId IS NULL AND (@Ordinal IS NOT NULL OR @Elapsed IS NOT NULL OR @BootId IS NOT NULL OR (@IsInternal=0 AND @RecordedAt<@last))
        THROW 51112, 'Unanchored command cannot precede committed history.', 1;
    IF (SELECT COUNT_BIG(*) FROM @Account)<>1 OR EXISTS(SELECT 1 FROM @Account
        WHERE Id<>@accountKey OR IdentityUserId<>@IdentityUserId OR MutationVersion<>@version+1
          OR ProjectionVersion<>@version+1 OR LastRecordedAt<>@ProjectionAt
          OR (HasPendingReconciliation=0 AND ProjectionAsOfAt<>@ProjectionAt)
          OR (HasPendingReconciliation=1 AND (ProjectionAsOfAt>@ProjectionAt OR ProjectionAsOfAt>(SELECT ProjectionAsOfAt FROM [pocketquests].[Account] WHERE Id=@accountKey))))
        THROW 51200, 'Account projection and mutation versions disagree.', 1;
    IF (SELECT COUNT_BIG(*) FROM @QuestCommandHistory)<>1 OR EXISTS(SELECT 1 FROM @QuestCommandHistory
        WHERE Id<>@OperationId OR AccountMutationVersion<>@version+1
          OR (@IsInternal=0 AND (CommandReceiptId IS NULL OR CommandReceiptId<>@OperationId))
          OR (@IsInternal=1 AND CommandReceiptId IS NOT NULL)
          OR ActionCode<>@Action OR RecordedAt<>@RecordedAt OR ProjectionAt<>@ProjectionAt OR RulesetVersion<>'1.0')
        THROW 51201, 'Exactly one matching typed command history row is required.', 1;
-- <ownership>
    -- Incoming source rows are deltas. They may never rewrite an existing immutable fact.
-- <immutability>
    IF EXISTS(SELECT 1 FROM @QuestSeries s JOIN [pocketquests].[QuestSeries] t ON t.AccountId=s.AccountId AND t.Id=s.Id
        WHERE s.QuestDefinitionId<>t.QuestDefinitionId AND (@Action<>'save-series' OR @IsInternal<>0 OR s.Revision<=t.Revision
          OR NOT EXISTS(SELECT 1 FROM @QuestSeriesRevision r
            JOIN (SELECT Id,AccountId,QuestDefinitionId FROM @QuestDefinitionRevision
                  UNION ALL SELECT Id,AccountId,QuestDefinitionId FROM [pocketquests].[QuestDefinitionRevision] WHERE AccountId=@accountKey) d
              ON d.AccountId=r.AccountId AND d.Id=r.QuestDefinitionRevisionId
            WHERE r.AccountId=s.AccountId AND r.QuestSeriesId=s.Id AND r.Revision=s.Revision AND d.QuestDefinitionId=s.QuestDefinitionId)))
        THROW 51206, 'Series quest changes require a new owned configuration from save-series.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCompletion s JOIN [pocketquests].[QuestCompletion] t ON t.AccountId=s.AccountId AND t.Id=s.Id
        WHERE t.UndoneAt IS NOT NULL AND (s.UndoneAt IS NULL OR s.UndoneAt<>t.UndoneAt OR s.UndoQuestOccurrenceEventId<>t.UndoQuestOccurrenceEventId))
        THROW 51202, 'Undo annotation is write-once.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionAttributeAllocation GROUP BY QuestDefinitionRevisionId HAVING SUM(CONVERT(bigint,BasisPoints))<>10000)
       OR EXISTS(SELECT 1 FROM @QuestDefinitionSkillAllocation GROUP BY QuestDefinitionRevisionId HAVING SUM(CONVERT(bigint,BasisPoints))<>10000)
        THROW 51113, 'Each nonempty allocation pool must total 10000.', 1;
    IF EXISTS(SELECT 1 FROM @CustomSkill s JOIN [pocketquests].[Skill] t ON s.NormalizedName=t.NormalizedName)
        THROW 51203, 'Custom skill name conflicts with a public skill.', 1;
    IF @IsInternal=0
      INSERT [pocketquests].[CommandReceipt]
        (Id,AccountId,CommandType,ApiVersion,PayloadDigest,DigestVersion,OutcomeVersion,OutcomeJson,AppliedMutationVersion,CreatedAt)
        VALUES(@OperationId,@accountKey,@Action,1,@Digest,1,2,@Outcome,@version+1,@Now);
-- <mutations>
    IF @AnchorId IS NOT NULL
        UPDATE [pocketquests].[SyncAnchor] SET LastOrdinal=@Ordinal,LastElapsedMilliseconds=@Elapsed,
            ModifiedAt=CASE WHEN ModifiedAt>@Now THEN ModifiedAt ELSE @Now END
            WHERE AccountId=@accountKey AND Id=@AnchorId;
    IF @IsInternal=0
    BEGIN
      INSERT [dbo].[AuditRecords](Id,OccurredAt,Actor,EventName,Category,Outcome,TargetType,TargetId,TenantId,CorrelationId,Operation,ChangesJson,MetadataJson)
        VALUES(@AuditId,@Now,@IdentityUserId,'pocketquests.quest.'+@Action,@AuditCategory,@AuditOutcome,'quest.account',
            CONVERT(nvarchar(36),@accountKey),@AuditTenant,@AuditCorrelation,@AuditOperation,@AuditChanges,@AuditMetadata);
      INSERT [pocketquests].[AccountAuditRecord](AccountId,AuditRecordId,CreatedAt) VALUES(@accountKey,@AuditId,@Now);
    END;
END;
GO
