"""Generate explicit TVPs and the controlled writer from reviewed column/update policies."""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[2]
SQL = ROOT / 'HoneyDrunk.PocketQuests/PocketQuests.Database'
DATA = ROOT / 'HoneyDrunk.PocketQuests/PocketQuests.Data/Relational/Commands'


def render():
    contract = json.loads((ROOT / 'docs/schema/schema-contract.json').read_text(encoding='utf-8'))
    tables = {t['name']: t for t in contract['tables']}
    policy = json.loads((ROOT / 'scripts/schema/mutation-policy.json').read_text(encoding='utf-8'))
    types, parameters, ownership, immutability, mutations = [], [], [], [], []
    loading, binding, keys, replacements = [], [], [], []
    cs = ['// <auto-generated />', '#nullable enable', 'using System.Data;', 'using Microsoft.Data.SqlClient;', 'using PocketQuests.Data.Relational.Entities;', '',
          'namespace PocketQuests.Data.Relational.Commands;', '', 'internal static class MutationBindings', '{',
          '    internal static void Bind<T>(SqlCommand sql, IEnumerable<T> rows) where T : class', '    {',
          '        var name = typeof(T).Name[..^6];', '        var columns = name switch', '        {']
    for name, writable in policy.items():
        t = tables[name]
        cols = [c for c in t['columns'] if c['type'] != 'rowversion']
        cn = [c['name'] for c in cols]
        key = t['primary_key']['columns']
        loading.append('        batch.Seed(Array.Empty<'+name+'Entity>());' if name in ('QuestCommandHistory','QuestCommandInterest') else '        await batch.Load<'+name+'Entity>(db, accountId, token);' if name != 'Account' else '        batch.Seed(new[] { account });')
        binding.append('        Bind(sql, batch.Rows<'+name+'Entity>());')
        keys.append('        "'+name+'" => new[] { '+', '.join('"'+k+'"' for k in key)+' },')
        if writable == 'replace':
            replacements.append(name)
        match = ' AND '.join('t.['+c+']=s.['+c+']' for c in key)
        declarations = []
        for c in cols:
            declarations.append('['+c['name']+'] '+c['type']+(' COLLATE '+c['collation'] if c['collation'] else '')+(' NULL' if c['nullable'] else ' NOT NULL'))
        declarations.append('PRIMARY KEY ('+','.join('['+c+']' for c in key)+')')
        types.append('CREATE TYPE [pocketquests].['+name+'MutationInput] AS TABLE (\n    '+',\n    '.join(declarations)+'\n);\nGO')
        parameters.append('    @'+name+' [pocketquests].['+name+'MutationInput] READONLY,')
        owner = 'Id' if name == 'Account' else 'AccountId'
        ownership.append('    IF EXISTS(SELECT 1 FROM @'+name+' WHERE ['+owner+"]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;")
        if writable != 'replace':
            fixed = [c for c in cn if c not in writable and c not in key]
            if fixed:
                a = ','.join('s.['+c+']' for c in fixed)
                b = ','.join('t.['+c+']' for c in fixed)
                immutability.append('    IF EXISTS(SELECT 1 FROM @'+name+' s JOIN [pocketquests].['+name+'] t ON '+match+' WHERE EXISTS(SELECT '+a+' EXCEPT SELECT '+b+")) THROW 51205, 'Immutable source fields cannot change: "+name+".', 1;")
        else:
            mutations.append('    DELETE FROM [pocketquests].['+name+'] WHERE AccountId=@accountKey;')
        if writable and writable != 'replace':
            mutations.append('    UPDATE t SET '+','.join('['+c+']=s.['+c+']' for c in writable)+' FROM [pocketquests].['+name+'] t JOIN @'+name+' s ON '+match+';')
        if name != 'Account':
            mutations.append('    INSERT [pocketquests].['+name+'] ('+','.join('['+c+']' for c in cn)+')\n        SELECT '+','.join('s.['+c+']' for c in cn)+' FROM @'+name+' s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].['+name+'] t WHERE '+match+');')
        cs.append('            "'+name+'" => new[] { '+', '.join('"'+c+'"' for c in cn)+' },')
    cs += ['            _ => throw new InvalidOperationException("Entity is not in the reviewed command mutation policy."),', '        };',
           '        var table = new DataTable { Locale = System.Globalization.CultureInfo.InvariantCulture };',
           '        var properties = columns.Select(name => typeof(T).GetProperty(name)!).ToArray();',
           '        foreach (var property in properties)', '        {',
           '            var type = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;',
           '            table.Columns.Add(property.Name, type == typeof(DateOnly) ? typeof(DateTime) : type == typeof(TimeOnly) ? typeof(TimeSpan) : type);', '        }',
           '        foreach (var row in rows)', '            table.Rows.Add(properties.Select(property => property.GetValue(row) switch { DateOnly date => date.ToDateTime(TimeOnly.MinValue), TimeOnly time => time.ToTimeSpan(), DateTimeOffset instant => instant.ToUniversalTime(), null => DBNull.Value, var value => value }).ToArray());',
           '        var parameter = sql.Parameters.Add("@" + name, SqlDbType.Structured);',
           '        parameter.TypeName = "pocketquests." + name + "MutationInput";', '        parameter.Value = table;', '    }', '',
           '    internal static async Task<MutationBatch> Read(RelationalQuestReadContext db, AccountEntity account, CancellationToken token)', '    {',
           '        var batch = new MutationBatch();', '        var accountId = account.Id;', *loading, '        return batch;', '    }', '',
           '    internal static void BindAll(SqlCommand sql, MutationBatch batch)', '    {', *binding, '    }', '',
           '    internal static string[] Keys(string name) => name switch', '    {', *keys, '        _ => throw new InvalidOperationException("Unknown mutation entity."),', '    };', '',
           '    internal static bool Replaces(string name) => name is '+ ' or '.join('"'+n+'"' for n in replacements)+';', '}']
    template = (ROOT / 'scripts/schema/commit-account-mutation.sql').read_text(encoding='utf-8')
    for marker, lines in [('parameters',parameters),('ownership',ownership),('immutability',immutability),('mutations',mutations)]:
        template = template.replace('-- <'+marker+'>','\n'.join(lines))
    grants = ['-- Generated grants: each table input is data, never direct table-write permission.', 'GRANT EXECUTE ON OBJECT::[pocketquests].[CommitAccountMutation] TO [pocketquests_command_runtime];', 'GO']
    for name in policy:
        grants += ['GRANT EXECUTE, REFERENCES ON TYPE::[pocketquests].['+name+'MutationInput] TO [pocketquests_command_runtime];','GO']
    grants += ['GRANT EXECUTE ON OBJECT::[pocketquests].[CommitAccountMutation] TO [pocketquests_lifecycle_runtime];','GO']
    for name in policy:
        grants += ['GRANT EXECUTE, REFERENCES ON TYPE::[pocketquests].['+name+'MutationInput] TO [pocketquests_lifecycle_runtime];','GO']
    return {SQL/'Types/pocketquests.MutationInputs.sql':'\n'.join(types)+'\n', SQL/'Procedures/pocketquests.CommitAccountMutation.sql':template,
            SQL/'Security/pocketquests.MutationRuntime.sql':'\n'.join(grants)+'\n', DATA/'MutationBindings.g.cs':'\n'.join(cs)+'\n'}


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    args = p.parse_args()
    drift = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content,encoding='utf-8',newline='\n')
    if drift:
        print('Mutation source drift:\n'+'\n'.join(drift))
        return 1
    print('Typed mutation source is reproducible.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
