"""Render the reviewed relational contract. --check fails on source/DDL/mapping drift."""
from pathlib import Path
import argparse
import html
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
DATABASE = ROOT / 'HoneyDrunk.PocketQuests/PocketQuests.Database'
DATA = ROOT / 'HoneyDrunk.PocketQuests/PocketQuests.Data/Relational'
CONTRACT = ROOT / 'docs/schema/schema-contract.json'
TABLE_DOMAINS = {'Account': 'Accounts', 'AccountInterest': 'Accounts', 'AccountPause': 'Accounts', 'TimeZoneChange': 'Accounts', 'AccountAuditRecord': 'Accounts', 'Category': 'Categories', 'CategoryProgress': 'Categories', 'Attribute': 'Attributes', 'Skill': 'Skills', 'CustomSkill': 'Skills', 'SkillAssessment': 'Skills', 'SystemQuest': 'Quests', 'QuestDefinition': 'Quests', 'QuestDefinitionRevision': 'Quests', 'QuestDefinitionAttributeAllocation': 'Quests', 'QuestDefinitionSkillAllocation': 'Quests', 'QuestSeries': 'Quests', 'QuestSeriesRevision': 'Quests', 'QuestOccurrence': 'Quests', 'QuestOccurrenceRevision': 'Quests', 'QuestOccurrenceEvent': 'Quests', 'QuestCompletion': 'Quests', 'QuestCommandHistory': 'Quests', 'QuestCommandInterest': 'Quests', 'ProfileReward': 'Progress', 'XpLedgerEntry': 'Progress', 'XpBalance': 'Progress', 'AccountEntitlement': 'Progress', 'SyncAnchor': 'Synchronization', 'CommandReceipt': 'Synchronization', 'AccountLifecycleState': 'Lifecycle', 'ErasureMarker': 'Lifecycle', 'LifecycleMessage': 'Lifecycle'}


def sql_string(value):
    return "N'" + value.replace("'", "''") + "'"


def names(values):
    return ', '.join('[' + value + ']' for value in values)


def csharp(value):
    return json.dumps(value, ensure_ascii=False)


def clr_type(column):
    name = column['type'].split('(')[0]
    result = {'varchar': 'string', 'nvarchar': 'string', 'char': 'string',
              'binary': 'byte[]', 'rowversion': 'byte[]', 'uniqueidentifier': 'Guid',
              'datetimeoffset': 'DateTimeOffset', 'date': 'DateOnly', 'time': 'TimeOnly',
              'int': 'int', 'bigint': 'long', 'float': 'double', 'smallint': 'short', 'tinyint': 'byte', 'bit': 'bool'}[name]
    return result + ('?' if column['nullable'] else '')


def table_sql(table):
    full = f"[{table['schema']}].[{table['name']}]"
    lines = []
    for column in table['columns']:
        line = f"[{column['name']}] {column['type']}"
        if column['collation']:
            line += ' COLLATE ' + column['collation']
        line += ' NULL' if column['nullable'] else ' NOT NULL'
        if column['default'] is not None:
            line += f" CONSTRAINT [DF_{table['name']}_{column['name']}] DEFAULT ({column['default']})"
        lines.append(line)
    key = table['primary_key']
    lines.append(f"CONSTRAINT [{key['name']}] PRIMARY KEY CLUSTERED ({names(key['columns'])})")
    for key in table['unique_keys']:
        lines.append(f"CONSTRAINT [{key['name']}] UNIQUE ({names(key['columns'])})")
    for check in table['checks']:
        lines.append(f"CONSTRAINT [{check['name']}] CHECK ({check['expression']})")
    for fk in table['foreign_keys']:
        lines.append(f"CONSTRAINT [{fk['name']}] FOREIGN KEY ({names(fk['columns'])}) REFERENCES [{fk['referenced_schema']}].[{fk['referenced_table']}] ({names(fk['referenced_columns'])}) ON DELETE NO ACTION")
    output = ['-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.',
              'CREATE TABLE ' + full + ' (\n    ' + ',\n    '.join(lines) + '\n);\nGO']
    for index in table['indexes']:
        output.append('-- ' + index['purpose'])
        output.append('CREATE ' + ('UNIQUE ' if index['unique'] else '') + f"INDEX [{index['name']}] ON {full} ({names(index['columns'])})"
                      + (' INCLUDE (' + names(index['include']) + ')' if index['include'] else '')
                      + (' WHERE ' + index['filter'] if index['filter'] else '') + ';\nGO')
    levels = f", @level0type=N'SCHEMA', @level0name={sql_string(table['schema'])}, @level1type=N'TABLE', @level1name={sql_string(table['name'])}"
    properties = [(table['description'], '')]
    properties += [(c['description'], ", @level2type=N'COLUMN', @level2name=" + sql_string(c['name'])) for c in table['columns']]
    properties += [(i['purpose'], ", @level2type=N'INDEX', @level2name=" + sql_string(i['name'])) for i in table['indexes']]
    for value, level in properties:
        output.append("EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=" + sql_string(value) + levels + level + ';\nGO')
    return '\n'.join(output) + '\n'


def seed_sql(data):
    result = ['-- Versioned public catalog only. Repeat publication preserves unchanged rows and timestamps.', 'SET NOCOUNT ON;']
    for table, rows in data.items():
        columns = list(rows[0])
        nonkeys = columns[1:]
        value = lambda v: sql_string(v) if isinstance(v, str) else str(v)
        values = ',\n    '.join('(' + ', '.join(value(row[c]) for c in columns) + ')' for row in rows)
        source = '(VALUES\n    ' + values + ') AS source (' + names(columns) + ')'
        changed = ' OR '.join(f'target.[{c}] <> source.[{c}]' for c in nonkeys)
        updates = ', '.join(f'[{c}]=source.[{c}]' for c in nonkeys)
        result += [f'UPDATE target SET {updates}, [ModifiedAt]=TODATETIMEOFFSET(SYSUTCDATETIME(),\'+00:00\')',
                   f'FROM [pocketquests].[{table}] AS target JOIN {source} ON target.Id=source.Id', f'WHERE {changed};',
                   f'INSERT [pocketquests].[{table}] ({names(columns)})', 'SELECT ' + ', '.join(f'source.[{c}]' for c in columns),
                   f'FROM {source}', f'WHERE NOT EXISTS (SELECT 1 FROM [pocketquests].[{table}] AS target WHERE target.Id=source.Id);', '']
    return '\n'.join(result).rstrip() + '\n'


def outputs(contract):
    result = {DATABASE / 'Schemas/pocketquests.sql': 'CREATE SCHEMA [pocketquests];\nGO\n'}
    for table in contract['tables']:
        result[DATABASE / f"Tables/{TABLE_DOMAINS[table['name']]}/{table['name']}.sql"] = table_sql(table)
    result[DATABASE / 'Data/Seed/PocketQuestsCatalog.sql'] = seed_sql(json.loads((ROOT / 'docs/schema/reference-data.json').read_text(encoding='utf-8')))
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    drift = []
    for path, content in outputs(json.loads(CONTRACT.read_text(encoding='utf-8'))).items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if drift:
        print('Generated schema drift:\n' + '\n'.join(drift))
        return 1
    print('Schema DDL and catalog seeds are current.' if args.check else 'Generated schema DDL and catalog seeds.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
