"""Render the reviewed relational contract. --check fails on source/DDL/mapping drift."""
from pathlib import Path
import argparse
import html
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
DATABASE = ROOT / 'HoneyDrunk.PocketQuests/PocketQuests.Database'
DATA = ROOT / 'HoneyDrunk.PocketQuests/PocketQuests.Data/Relational'
CONTRACT = ROOT / 'docs/schema/schema-contract.json'


def sql_string(value):
    return "N'" + value.replace("'", "''") + "'"


def names(values):
    return ', '.join('[' + value + ']' for value in values)


def csharp(value):
    return json.dumps(value, ensure_ascii=False)


def clr_type(column):
    name = column['type'].split('(')[0]
    result = {'varchar': 'string', 'nvarchar': 'string', 'char': 'string',
              'binary': 'byte[]', 'rowversion': 'byte[]', 'uniqueidentifier': 'Guid',
              'datetimeoffset': 'DateTimeOffset', 'date': 'DateOnly', 'time': 'TimeOnly',
              'int': 'int', 'bigint': 'long', 'float': 'double', 'smallint': 'short', 'tinyint': 'byte', 'bit': 'bool'}[name]
    return result + ('?' if column['nullable'] else '')


def table_sql(table):
    full = f"[{table['schema']}].[{table['name']}]"
    lines = []
    for column in table['columns']:
        line = f"[{column['name']}] {column['type']}"
        if column['collation']:
            line += ' COLLATE ' + column['collation']
        line += ' NULL' if column['nullable'] else ' NOT NULL'
        if column['default'] is not None:
            line += f" CONSTRAINT [DF_{table['name']}_{column['name']}] DEFAULT ({column['default']})"
        lines.append(line)
    key = table['primary_key']
    lines.append(f"CONSTRAINT [{key['name']}] PRIMARY KEY CLUSTERED ({names(key['columns'])})")
    for key in table['unique_keys']:
        lines.append(f"CONSTRAINT [{key['name']}] UNIQUE ({names(key['columns'])})")
    for check in table['checks']:
        lines.append(f"CONSTRAINT [{check['name']}] CHECK ({check['expression']})")
    for fk in table['foreign_keys']:
        lines.append(f"CONSTRAINT [{fk['name']}] FOREIGN KEY ({names(fk['columns'])}) REFERENCES [{fk['referenced_schema']}].[{fk['referenced_table']}] ({names(fk['referenced_columns'])}) ON DELETE NO ACTION")
    output = ['-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.',
              'CREATE TABLE ' + full + ' (\n    ' + ',\n    '.join(lines) + '\n);\nGO']
    for index in table['indexes']:
        output.append('-- ' + index['purpose'])
        output.append('CREATE ' + ('UNIQUE ' if index['unique'] else '') + f"INDEX [{index['name']}] ON {full} ({names(index['columns'])})"
                      + (' INCLUDE (' + names(index['include']) + ')' if index['include'] else '')
                      + (' WHERE ' + index['filter'] if index['filter'] else '') + ';\nGO')
    levels = f", @level0type=N'SCHEMA', @level0name={sql_string(table['schema'])}, @level1type=N'TABLE', @level1name={sql_string(table['name'])}"
    properties = [(table['description'], '')]
    properties += [(c['description'], ", @level2type=N'COLUMN', @level2name=" + sql_string(c['name'])) for c in table['columns']]
    properties += [(i['purpose'], ", @level2type=N'INDEX', @level2name=" + sql_string(i['name'])) for i in table['indexes']]
    for value, level in properties:
        output.append("EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=" + sql_string(value) + levels + level + ';\nGO')
    return '\n'.join(output) + '\n'


def entity_source(table):
    lines = ['// <auto-generated />', '#nullable enable', '', 'namespace PocketQuests.Data.Relational.Entities;', '',
             '/// <summary>' + html.escape(table['description']) + '</summary>',
             f"public sealed class {table['name']}Entity", '{']
    for column in table['columns']:
        typ = clr_type(column)
        initial = ' = string.Empty;' if typ == 'string' else ' = [];' if typ == 'byte[]' else ''
        lines += ['    /// <summary>' + html.escape(column['description']) + '</summary>',
                  f"    public {typ} {column['name']} {{ get; set; }}{initial}", '']
    return '\n'.join(lines).rstrip() + '\n}\n'


def model_source(contract):
    lines = ['// <auto-generated />', '#nullable enable', 'using Microsoft.EntityFrameworkCore;',
             'using PocketQuests.Data.Relational.Entities;', '', 'namespace PocketQuests.Data.Relational;', '',
             'internal static class RelationalQuestModel', '{', '    internal static void Configure(ModelBuilder model)', '    {']
    # Keys alone are enough to describe references; shared owners retain the full mappings.
    for table in contract['external_tables']:
        typ = 'string' if table['columns']['Id'].startswith('varchar') else 'Guid'
        lines += [f"        model.SharedTypeEntity<Dictionary<string, object>>({csharp(table['name'] + 'Reference')}, entity =>",
                  '        {', f"            entity.ToTable({csharp(table['name'])}, {csharp(table['schema'])});",
                  f"            entity.IndexerProperty<{typ}>(\"Id\").HasColumnType({csharp(table['columns']['Id'])}).ValueGeneratedNever();",
                  '            entity.HasKey("Id");', '        });']
    for table in contract['tables']:
        lines += [f"        model.Entity<Entities.{table['name']}Entity>(entity =>", '        {',
                  f"            entity.ToTable({csharp(table['name'])}, {csharp(table['schema'])}, table =>", '            {',
                  f"                table.HasComment({csharp(table['description'])});"]
        for check in table['checks']:
            lines.append(f"                table.HasCheckConstraint({csharp(check['name'])}, {csharp(check['expression'])});")
        lines += ['            });', f"            entity.HasKey({', '.join(map(csharp, table['primary_key']['columns']))}).HasName({csharp(table['primary_key']['name'])}).IsClustered();"]
        for key in table['unique_keys']:
            # EF alternate keys force NOT NULL. SQL uniqueness over nullable target tuples
            # is a unique index mapping, not an EF identity/relationship key.
            nullable = any(c['nullable'] and c['name'] in key['columns'] for c in table['columns'])
            if nullable:
                lines.append(f"            entity.HasIndex(new[] {{ {', '.join(map(csharp, key['columns']))} }}, {csharp(key['name'])}).IsUnique().HasFilter(null);")
            else:
                lines.append(f"            entity.HasAlternateKey({', '.join(map(csharp, key['columns']))}).HasName({csharp(key['name'])});")
        for column in table['columns']:
            line = f"            entity.Property(row => row.{column['name']}).HasColumnType({csharp(column['type'])}).HasComment({csharp(column['description'])})"
            if column['collation'] and column['collation'] != 'DATABASE_DEFAULT':
                line += '.UseCollation(' + csharp(column['collation']) + ')'
            match = re.fullmatch(r'(n?varchar|char|binary)\((\d+)\)', column['type'])
            if match:
                line += f'.HasMaxLength({match[2]})'
                if match[1] != 'binary':
                    line += '.IsUnicode(' + ('true' if match[1].startswith('n') else 'false') + ')'
            if column['type'].startswith(('datetimeoffset', 'time(')):
                line += '.HasPrecision(' + column['type'].split('(')[1].rstrip(')') + ')'
            line += '.IsRequired(' + ('false' if column['nullable'] else 'true') + ')'
            if column['type'] == 'rowversion':
                line += '.IsRowVersion()'
            elif column['default'] is not None:
                line += '.HasDefaultValueSql(' + csharp(column['default']) + ')'
            else:
                line += '.ValueGeneratedNever()'
            lines.append(line + ';')
        for index in table['indexes']:
            line = f"            entity.HasIndex(new[] {{ {', '.join(map(csharp, index['columns']))} }}, {csharp(index['name'])}).IsUnique({str(index['unique']).lower()}).HasFilter({csharp(index['filter'])})"
            if index['include']:
                line += '.IncludeProperties(' + ', '.join(map(csharp, index['include'])) + ')'
            lines.append(line + ';')
        for fk in table['foreign_keys']:
            target = f"Entities.{fk['referenced_table']}Entity" if fk['referenced_schema'] == 'pocketquests' else None
            line = f"            entity.HasOne<{target}>()" if target else f"            entity.HasOne({csharp(fk['referenced_table'] + 'Reference')}, null)"
            line += f".WithMany().HasForeignKey({', '.join(map(csharp, fk['columns']))}).HasPrincipalKey({', '.join(map(csharp, fk['referenced_columns']))}).OnDelete(DeleteBehavior.NoAction).HasConstraintName({csharp(fk['name'])});"
            lines.append(line)
        lines += ['        });']
    return '\n'.join(lines + ['    }', '}']) + '\n'


def seed_sql(data):
    result = ['-- Versioned public catalog only. Repeat publication preserves unchanged rows and timestamps.', 'SET NOCOUNT ON;']
    for table, rows in data.items():
        columns = list(rows[0])
        nonkeys = columns[1:]
        value = lambda v: sql_string(v) if isinstance(v, str) else str(v)
        values = ',\n    '.join('(' + ', '.join(value(row[c]) for c in columns) + ')' for row in rows)
        source = '(VALUES\n    ' + values + ') AS source (' + names(columns) + ')'
        changed = ' OR '.join(f'target.[{c}] <> source.[{c}]' for c in nonkeys)
        updates = ', '.join(f'[{c}]=source.[{c}]' for c in nonkeys)
        result += [f'UPDATE target SET {updates}, [ModifiedAt]=TODATETIMEOFFSET(SYSUTCDATETIME(),\'+00:00\')',
                   f'FROM [pocketquests].[{table}] AS target JOIN {source} ON target.Id=source.Id', f'WHERE {changed};',
                   f'INSERT [pocketquests].[{table}] ({names(columns)})', 'SELECT ' + ', '.join(f'source.[{c}]' for c in columns),
                   f'FROM {source}', f'WHERE NOT EXISTS (SELECT 1 FROM [pocketquests].[{table}] AS target WHERE target.Id=source.Id);', '']
    return '\n'.join(result).rstrip() + '\n'


def outputs(contract):
    result = {DATABASE / 'Schemas/pocketquests.sql': 'CREATE SCHEMA [pocketquests];\nGO\n'}
    for table in contract['tables']:
        result[DATABASE / f"Tables/pocketquests.{table['name']}.sql"] = table_sql(table)
        result[DATA / f"Entities/{table['name']}Entity.g.cs"] = entity_source(table)
    result[DATA / 'RelationalQuestModel.g.cs'] = model_source(contract)
    result[DATABASE / 'Data/Seed/PocketQuestsCatalog.sql'] = seed_sql(json.loads((ROOT / 'docs/schema/reference-data.json').read_text(encoding='utf-8')))
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    drift = []
    for path, content in outputs(json.loads(CONTRACT.read_text(encoding='utf-8'))).items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if drift:
        print('Generated schema drift:\n' + '\n'.join(drift))
        return 1
    print('Schema DDL, EF read mappings and catalog seeds are current.' if args.check else 'Generated schema DDL, EF read mappings and catalog seeds.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
