-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestDefinitionAttributeAllocation] (
    [AccountId] uniqueidentifier NOT NULL,
    [QuestDefinitionRevisionId] uniqueidentifier NOT NULL,
    [AttributeId] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [BasisPoints] int NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestDefinitionAttributeAllocation_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [Position] int NOT NULL CONSTRAINT [DF_QuestDefinitionAttributeAllocation_Position] DEFAULT (0),
    CONSTRAINT [PK_QuestDefinitionAttributeAllocation] PRIMARY KEY CLUSTERED ([AccountId], [QuestDefinitionRevisionId], [AttributeId]),
    CONSTRAINT [CK_QuestDefinitionAttributeAllocation_BasisPoints] CHECK ([BasisPoints] BETWEEN 0 AND 10000),
    CONSTRAINT [CK_QuestDefinitionAttributeAllocation_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestDefinitionAttributeAllocation_Position] CHECK ([Position]>=0),
    CONSTRAINT [FK_QuestDefinitionAttributeAllocation_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestDefinitionAttributeAllocation_QuestDefinitionRevision] FOREIGN KEY ([AccountId], [QuestDefinitionRevisionId]) REFERENCES [pocketquests].[QuestDefinitionRevision] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestDefinitionAttributeAllocation_Attribute] FOREIGN KEY ([AttributeId]) REFERENCES [pocketquests].[Attribute] ([Id]) ON DELETE NO ACTION
);
GO
-- Supports FK_QuestDefinitionAttributeAllocation_Attribute parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestDefinitionAttributeAllocation_FK_Attribute] ON [pocketquests].[QuestDefinitionAttributeAllocation] ([AttributeId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one attribute recipient in an immutable definition revision. Classification: Restricted. History: event; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Immutable revision that owns this allocation.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'COLUMN', @level2name=N'QuestDefinitionRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable attribute receiving this share.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'COLUMN', @level2name=N'AttributeId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact share 0..10000; nonempty allocation pool must sum to 10000 in the controlled write.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'COLUMN', @level2name=N'BasisPoints';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original allocation array position, preserving the existing API order; v1 rows retain their display-order adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'COLUMN', @level2name=N'Position';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestDefinitionAttributeAllocation_Attribute parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestDefinitionAttributeAllocation', @level2type=N'INDEX', @level2name=N'IX_QuestDefinitionAttributeAllocation_FK_Attribute';
GO
