-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[QuestOccurrence] (
    [Id] uniqueidentifier NOT NULL,
    [AccountId] uniqueidentifier NOT NULL,
    [QuestDefinitionId] uniqueidentifier NOT NULL,
    [QuestDefinitionRevisionId] uniqueidentifier NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [DueOn] date NULL,
    [PlannedTime] time(0) NULL,
    [DeadlineAt] datetimeoffset(7) NULL,
    [DeadlineTimeZoneId] varchar(100) COLLATE Latin1_General_100_BIN2 NULL,
    [StateCode] varchar(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [AcceptedAt] datetimeoffset(7) NULL,
    [FrozenAt] datetimeoffset(7) NULL,
    [IsIndividuallyFrozen] bit NOT NULL CONSTRAINT [DF_QuestOccurrence_IsIndividuallyFrozen] DEFAULT (0),
    [AbandonedAt] datetimeoffset(7) NULL,
    [LockedLoss] bigint NULL,
    [LossCategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [Revision] int NOT NULL,
    [QuestSeriesId] uniqueidentifier NULL,
    [QuestSeriesRevisionId] uniqueidentifier NULL,
    [SeriesSequence] int NULL,
    [ParentQuestOccurrenceId] uniqueidentifier NULL,
    [SourceSyncAnchorId] uniqueidentifier NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestOccurrence_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_QuestOccurrence_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [RowVersion] rowversion NOT NULL,
    [OriginatedAt] datetimeoffset(7) NULL,
    [CreationOrdinal] int NOT NULL CONSTRAINT [DF_QuestOccurrence_CreationOrdinal] DEFAULT (0),
    [OriginatedOffsetMinutes] smallint NOT NULL CONSTRAINT [DF_QuestOccurrence_OriginatedOffsetMinutes] DEFAULT (0),
    CONSTRAINT [PK_QuestOccurrence] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_QuestOccurrence_AccountId_Id] UNIQUE ([AccountId], [Id]),
    CONSTRAINT [CK_QuestOccurrence_StateCode] CHECK ([StateCode] IN ('Active','Completed','Missed','Frozen','Abandoned','Offered')),
    CONSTRAINT [CK_QuestOccurrence_ScheduleNulls] CHECK (([DueOn] IS NULL AND [DeadlineAt] IS NULL AND [PlannedTime] IS NULL) OR ([DueOn] IS NOT NULL AND [DeadlineAt] IS NOT NULL AND [DeadlineTimeZoneId] IS NOT NULL AND [DueOn]<CONVERT(date,'9999-01-01'))),
    CONSTRAINT [CK_QuestOccurrence_LockedPenalty] CHECK (([LockedLoss] IS NULL AND [LossCategoryId] IS NULL) OR ([LockedLoss] IS NOT NULL AND [LockedLoss]>=0 AND [LossCategoryId] IS NOT NULL)),
    CONSTRAINT [CK_QuestOccurrence_Acceptance] CHECK (([StateCode]='Offered' AND [AcceptedAt] IS NULL AND [LockedLoss] IS NULL) OR ([StateCode]<>'Offered' AND [AcceptedAt] IS NOT NULL)),
    CONSTRAINT [CK_QuestOccurrence_FreezeFlag] CHECK ([IsIndividuallyFrozen]=0 OR [FrozenAt] IS NOT NULL),
    CONSTRAINT [CK_QuestOccurrence_Revision] CHECK ([Revision] >= 1),
    CONSTRAINT [CK_QuestOccurrence_SeriesFields] CHECK (([QuestSeriesId] IS NULL AND [QuestSeriesRevisionId] IS NULL AND [SeriesSequence] IS NULL) OR ([QuestSeriesId] IS NOT NULL AND [QuestSeriesRevisionId] IS NOT NULL AND [SeriesSequence] IS NOT NULL AND [SeriesSequence]>=0)),
    CONSTRAINT [CK_QuestOccurrence_NotOwnParent] CHECK ([ParentQuestOccurrenceId] IS NULL OR [ParentQuestOccurrenceId]<>[Id]),
    CONSTRAINT [CK_QuestOccurrence_DeadlineAtUtc] CHECK ([DeadlineAt] IS NULL OR DATEPART(TZOFFSET,[DeadlineAt])=0),
    CONSTRAINT [CK_QuestOccurrence_AcceptedAtUtc] CHECK ([AcceptedAt] IS NULL OR DATEPART(TZOFFSET,[AcceptedAt])=0),
    CONSTRAINT [CK_QuestOccurrence_FrozenAtUtc] CHECK ([FrozenAt] IS NULL OR DATEPART(TZOFFSET,[FrozenAt])=0),
    CONSTRAINT [CK_QuestOccurrence_AbandonedAtUtc] CHECK ([AbandonedAt] IS NULL OR DATEPART(TZOFFSET,[AbandonedAt])=0),
    CONSTRAINT [CK_QuestOccurrence_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_QuestOccurrence_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_QuestOccurrence_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [CK_QuestOccurrence_OriginatedAtUtc] CHECK ([OriginatedAt] IS NULL OR DATEPART(TZOFFSET,[OriginatedAt])=0),
    CONSTRAINT [CK_QuestOccurrence_CreationOrdinal] CHECK ([CreationOrdinal]>=0),
    CONSTRAINT [CK_QuestOccurrence_OriginatedOffset] CHECK ([OriginatedOffsetMinutes]>=-840 AND [OriginatedOffsetMinutes]<=840),
    CONSTRAINT [FK_QuestOccurrence_Account] FOREIGN KEY ([AccountId]) REFERENCES [pocketquests].[Account] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrence_QuestDefinitionRevision] FOREIGN KEY ([AccountId], [QuestDefinitionId], [QuestDefinitionRevisionId]) REFERENCES [pocketquests].[QuestDefinitionRevision] ([AccountId], [QuestDefinitionId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrence_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrence_Category_Loss] FOREIGN KEY ([LossCategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrence_QuestSeriesRevision] FOREIGN KEY ([AccountId], [QuestSeriesId], [QuestSeriesRevisionId]) REFERENCES [pocketquests].[QuestSeriesRevision] ([AccountId], [QuestSeriesId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrence_QuestOccurrence_Parent] FOREIGN KEY ([AccountId], [ParentQuestOccurrenceId]) REFERENCES [pocketquests].[QuestOccurrence] ([AccountId], [Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_QuestOccurrence_SyncAnchor_Source] FOREIGN KEY ([AccountId], [SourceSyncAnchorId]) REFERENCES [pocketquests].[SyncAnchor] ([AccountId], [Id]) ON DELETE NO ACTION
);
GO
-- Deduplicate each delivered recurrence occurrence.
CREATE UNIQUE INDEX [UQ_QuestOccurrence_SeriesDelivery] ON [pocketquests].[QuestOccurrence] ([AccountId], [QuestSeriesId], [QuestSeriesRevisionId], [SeriesSequence]) WHERE [QuestSeriesId] IS NOT NULL;
GO
-- Account-scoped current quest list in due-date order.
CREATE INDEX [IX_QuestOccurrence_QuestList] ON [pocketquests].[QuestOccurrence] ([AccountId], [StateCode], [DueOn], [Id]);
GO
-- Bounded due reconciliation by stored state/deadline.
CREATE INDEX [IX_QuestOccurrence_DueWork] ON [pocketquests].[QuestOccurrence] ([AccountId], [StateCode], [DeadlineAt], [Id]);
GO
-- Supports FK_QuestOccurrence_QuestDefinitionRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrence_FK_QuestDefinitionRevision] ON [pocketquests].[QuestOccurrence] ([AccountId], [QuestDefinitionId], [QuestDefinitionRevisionId]);
GO
-- Supports FK_QuestOccurrence_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrence_FK_Category] ON [pocketquests].[QuestOccurrence] ([CategoryId]);
GO
-- Supports FK_QuestOccurrence_Category_Loss parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrence_FK_Category_Loss] ON [pocketquests].[QuestOccurrence] ([LossCategoryId]);
GO
-- Supports FK_QuestOccurrence_QuestSeriesRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrence_FK_QuestSeriesRevision] ON [pocketquests].[QuestOccurrence] ([AccountId], [QuestSeriesId], [QuestSeriesRevisionId]);
GO
-- Supports FK_QuestOccurrence_QuestOccurrence_Parent parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrence_FK_QuestOccurrence_Parent] ON [pocketquests].[QuestOccurrence] ([AccountId], [ParentQuestOccurrenceId]);
GO
-- Supports FK_QuestOccurrence_SyncAnchor_Source parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_QuestOccurrence_FK_SyncAnchor_Source] ON [pocketquests].[QuestOccurrence] ([AccountId], [SourceSyncAnchorId]);
GO
-- Stable bounded keyset paging of current occurrences by creation order; positive ordinals are unique per account, while zero retains only the v1 adapter.
CREATE UNIQUE INDEX [UX_QuestOccurrence_CreationPage] ON [pocketquests].[QuestOccurrence] ([AccountId], [CreationOrdinal]) WHERE [CreationOrdinal]>0;
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one current offered or accepted occurrence, with immutable past versions below. Classification: Restricted. History: mutable; Retain while the account exists, including its recovery interval; erase with the account. No arbitrary age-based pruning of replay source facts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Application-generated stable row UUID; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Pocket Quests account that exclusively owns this row; supplied by trusted server context.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'AccountId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Persistent account-owned definition identity.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'QuestDefinitionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact immutable content/reward revision used by this occurrence version.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'QuestDefinitionRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Materialized current/frozen category for filtering, constrained to the controlled revision write.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Due date in DeadlineTimeZoneId; null means unscheduled with no deadline.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'DueOn';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Optional local planned clock time; null means none; requires DueOn.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'PlannedTime';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Absolute end-of-due-day deadline; null for unscheduled occurrence. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'DeadlineAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'IANA calendar zone used to calculate DueOn/DeadlineAt. Null only for unscheduled occurrence.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'DeadlineTimeZoneId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Active, Completed, Missed, Frozen, Abandoned or Offered; time-dependent projection can be newer than persisted reconciliation.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'StateCode';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recorded acceptance time; null while only an unaccepted offer. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'AcceptedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Start of the current freeze, if any. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'FrozenAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Whether an individual freeze remains after account/category resume.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'IsIndividuallyFrozen';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Explicit abandonment time, if any. UTC instant. Null means this event has not happened.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'AbandonedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact accepted nonnegative penalty amount. Null means no penalty commitment.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'LockedLoss';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Category frozen with an accepted loss; null exactly when LockedLoss is null.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'LossCategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Positive immutable occurrence-version number matching this current row.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'Revision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Recurrence source; null for a one-off quest.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'QuestSeriesId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Exact recurrence configuration; null for a one-off quest.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'QuestSeriesRevisionId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Nonnegative sequence within the source series version; null for a one-off quest.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'SeriesSequence';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Optional independently attested Large parent owned by the same account; null means no parent.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'ParentQuestOccurrenceId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Proof under which an occurrence was created offline; null for ordinary online creation.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'SourceSyncAnchorId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SQL-generated opaque concurrency token; compare as bytes, not as a clock.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'RowVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original occurrence creation/delivery instant used by the domain even while the recurring occurrence is still an unaccepted offer. Null means not applicable to this transition.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'OriginatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable one-based position in the existing API array, set once at creation; zero is reserved for public catalog adoption or the retained v1 adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'CreationOrdinal';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Original domain/API display offset of OriginatedAt, retained separately from its authoritative UTC instant for exact recurring-offer response reconstruction.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'COLUMN', @level2name=N'OriginatedOffsetMinutes';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Deduplicate each delivered recurrence occurrence.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'UQ_QuestOccurrence_SeriesDelivery';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Account-scoped current quest list in due-date order.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_QuestList';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Bounded due reconciliation by stored state/deadline.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_DueWork';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrence_QuestDefinitionRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_FK_QuestDefinitionRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrence_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_FK_Category';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrence_Category_Loss parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_FK_Category_Loss';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrence_QuestSeriesRevision parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_FK_QuestSeriesRevision';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrence_QuestOccurrence_Parent parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_FK_QuestOccurrence_Parent';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_QuestOccurrence_SyncAnchor_Source parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'IX_QuestOccurrence_FK_SyncAnchor_Source';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable bounded keyset paging of current occurrences by creation order; positive ordinals are unique per account, while zero retains only the v1 adapter.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'QuestOccurrence', @level2type=N'INDEX', @level2name=N'UX_QuestOccurrence_CreationPage';
GO
