-- Generated by scripts/schema/generate_schema.py; edit the reviewed contract.
CREATE TABLE [pocketquests].[SystemQuest] (
    [Id] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CategoryId] varchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Title] nvarchar(120) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CatalogVersion] varchar(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CreatedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_SystemQuest_CreatedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    [ModifiedAt] datetimeoffset(7) NOT NULL CONSTRAINT [DF_SystemQuest_ModifiedAt] DEFAULT (TODATETIMEOFFSET(SYSUTCDATETIME(), '+00:00')),
    CONSTRAINT [PK_SystemQuest] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [CK_SystemQuest_CreatedAtUtc] CHECK (DATEPART(TZOFFSET,[CreatedAt])=0),
    CONSTRAINT [CK_SystemQuest_ModifiedAtUtc] CHECK (DATEPART(TZOFFSET,[ModifiedAt])=0),
    CONSTRAINT [CK_SystemQuest_ModificationClock] CHECK ([ModifiedAt]>=[CreatedAt]),
    CONSTRAINT [FK_SystemQuest_Category] FOREIGN KEY ([CategoryId]) REFERENCES [pocketquests].[Category] ([Id]) ON DELETE NO ACTION
);
GO
-- Supports FK_SystemQuest_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.
CREATE INDEX [IX_SystemQuest_FK_Category] ON [pocketquests].[SystemQuest] ([CategoryId]);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'One row is one stable system quest identity whose full template is owned by the versioned catalog. Classification: Public. History: reference; Retain referenced codes; source-controlled template versions retain old terms. Not erased with accounts.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Stable system quest code, for example PQ-CAT-Q01; never reused.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'COLUMN', @level2name=N'Id';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Canonical category of the system template.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'COLUMN', @level2name=N'CategoryId';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Current public system-quest title; accepted terms use immutable account definition revisions.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'COLUMN', @level2name=N'Title';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Reviewed template version; seeds must agree with the canonical catalog.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'COLUMN', @level2name=N'CatalogVersion';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC insertion time; not the effective time of a delayed offline action.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'COLUMN', @level2name=N'CreatedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Server UTC time of the most recent persisted change; writer must set on each update.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'COLUMN', @level2name=N'ModifiedAt';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Supports FK_SystemQuest_Category parent-reference validation/deletion and direct child lookup; no covering payload columns.', @level0type=N'SCHEMA', @level0name=N'pocketquests', @level1type=N'TABLE', @level1name=N'SystemQuest', @level2type=N'INDEX', @level2name=N'IX_SystemQuest_FK_Category';
GO
