-- Generated by generate_mutation.py from this template and the reviewed typed mutation policy.
-- The internal service computes domain transitions; SQL owns account boundaries, source immutability,
-- optimistic serialization, proof consumption and the atomic receipt/history/projection/Audit unit.
CREATE PROCEDURE [pocketquests].[CommitAccountMutation]
    @IdentityUserId varchar(30), @ExpectedVersion bigint, @IsInternal bit = 0,
    @OperationId uniqueidentifier, @Action varchar(40), @Digest binary(32), @Outcome nvarchar(max),
    @RecordedAt datetimeoffset(7), @ProjectionAt datetimeoffset(7), @Now datetimeoffset(7),
    @AnchorId uniqueidentifier = NULL, @BootId uniqueidentifier = NULL,
    @Ordinal bigint = NULL, @Elapsed float(53) = NULL,
    @Account [pocketquests].[AccountMutationInput] READONLY,
    @CustomSkill [pocketquests].[CustomSkillMutationInput] READONLY,
    @QuestDefinition [pocketquests].[QuestDefinitionMutationInput] READONLY,
    @QuestDefinitionRevision [pocketquests].[QuestDefinitionRevisionMutationInput] READONLY,
    @QuestDefinitionAttributeAllocation [pocketquests].[QuestDefinitionAttributeAllocationMutationInput] READONLY,
    @QuestDefinitionSkillAllocation [pocketquests].[QuestDefinitionSkillAllocationMutationInput] READONLY,
    @QuestSeries [pocketquests].[QuestSeriesMutationInput] READONLY,
    @QuestSeriesRevision [pocketquests].[QuestSeriesRevisionMutationInput] READONLY,
    @QuestOccurrence [pocketquests].[QuestOccurrenceMutationInput] READONLY,
    @QuestOccurrenceRevision [pocketquests].[QuestOccurrenceRevisionMutationInput] READONLY,
    @QuestOccurrenceEvent [pocketquests].[QuestOccurrenceEventMutationInput] READONLY,
    @QuestCompletion [pocketquests].[QuestCompletionMutationInput] READONLY,
    @AccountPause [pocketquests].[AccountPauseMutationInput] READONLY,
    @TimeZoneChange [pocketquests].[TimeZoneChangeMutationInput] READONLY,
    @SkillAssessment [pocketquests].[SkillAssessmentMutationInput] READONLY,
    @QuestCommandHistory [pocketquests].[QuestCommandHistoryMutationInput] READONLY,
    @QuestCommandInterest [pocketquests].[QuestCommandInterestMutationInput] READONLY,
    @AccountInterest [pocketquests].[AccountInterestMutationInput] READONLY,
    @XpLedgerEntry [pocketquests].[XpLedgerEntryMutationInput] READONLY,
    @XpBalance [pocketquests].[XpBalanceMutationInput] READONLY,
    @CategoryProgress [pocketquests].[CategoryProgressMutationInput] READONLY,
    @AccountEntitlement [pocketquests].[AccountEntitlementMutationInput] READONLY,
    @AuditId varchar(32), @AuditCategory int, @AuditOutcome int, @AuditOperation int,
    @AuditTenant varchar(100), @AuditCorrelation nvarchar(max) = NULL, @AuditChanges nvarchar(max), @AuditMetadata nvarchar(max)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    IF @IsInternal=1 AND @Action='$lifecycle-pause'
    BEGIN
        IF COALESCE(IS_ROLEMEMBER('pocketquests_lifecycle_runtime'),0)<>1
           AND COALESCE(IS_ROLEMEMBER('db_owner'),0)<>1 AND COALESCE(IS_SRVROLEMEMBER('sysadmin'),0)<>1
            THROW 51300, 'Only the trusted lifecycle role can freeze an inactive account.', 1;
        EXEC [pocketquests].[AcquireAccountLock] @IdentityUserId;
        IF EXISTS(SELECT 1 FROM [pocketquests].[ErasureMarker] WHERE Id=@IdentityUserId)
            THROW 51103, 'Erased accounts cannot acquire new source history.', 1;
    END
    ELSE EXEC [pocketquests].[LockAccount] @IdentityUserId;
    DECLARE @accountKey uniqueidentifier, @version bigint, @last datetimeoffset(7);
    SELECT @accountKey=Id,@version=MutationVersion,@last=LastRecordedAt
        FROM [pocketquests].[Account] WHERE IdentityUserId=@IdentityUserId;
    IF @accountKey IS NULL THROW 51104, 'Account was not initialized.', 1;
    IF @IsInternal=0 AND EXISTS (SELECT 1 FROM [pocketquests].[CommandReceipt] WHERE AccountId=@accountKey AND Id=@OperationId)
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM [pocketquests].[CommandReceipt]
            WHERE AccountId=@accountKey AND Id=@OperationId AND PayloadDigest=@Digest AND DigestVersion=1 AND ApiVersion=1 AND CommandType=@Action)
            THROW 51107, 'Operation ID already belongs to a different payload.', 1;
        RETURN;
    END;
    IF @ExpectedVersion IS NULL OR @version<>@ExpectedVersion THROW 51108, 'Account version changed.', 1;
    IF @OperationId IS NULL OR @OperationId='00000000-0000-0000-0000-000000000000' OR @IsInternal IS NULL OR @Action IS NULL
       OR (@IsInternal=1 AND @Action NOT IN ('$reconcile','$lifecycle-pause'))
       OR (@IsInternal=0 AND @Action IN ('$reconcile','$lifecycle-pause'))
        THROW 51109, 'An operation identifier is required.', 1;
    IF @RecordedAt IS NULL OR @ProjectionAt IS NULL OR @Now IS NULL
        THROW 51111, 'Explicit effective, projection and receipt clocks are required.', 1;
    IF @IsInternal=0 AND (@Outcome IS NULL OR ISJSON(@Outcome)<>1 OR DATALENGTH(@Outcome)>256
       OR EXISTS(SELECT 1 FROM OPENJSON(@Outcome) WHERE [key] NOT IN ('ProjectionAt','CompletionOutcome'))
       OR (SELECT COUNT_BIG(*) FROM OPENJSON(@Outcome))<>2
       OR NOT EXISTS(SELECT 1 FROM OPENJSON(@Outcome) WHERE [key]='CompletionOutcome' AND [type]=0)
       OR NOT EXISTS(SELECT 1 FROM OPENJSON(@Outcome) WHERE [key]='ProjectionAt' AND [type]=1)
       OR TRY_CONVERT(datetimeoffset(7),JSON_VALUE(@Outcome,'$.ProjectionAt')) IS NULL
       OR TRY_CONVERT(datetimeoffset(7),JSON_VALUE(@Outcome,'$.ProjectionAt'))<>@ProjectionAt)
        THROW 51110, 'Receipt must be a compact outcome.', 1;
    IF @IsInternal=0 AND @RecordedAt>DATEADD(second,5,@Now) THROW 51105, 'Server clock is not ready.', 1;
    IF @ProjectionAt<@RecordedAt OR @ProjectionAt<@Now OR @ProjectionAt<@last
        THROW 51111, 'Projection time cannot omit committed history.', 1;
    IF @AnchorId IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [pocketquests].[SyncAnchor]
        WHERE Id=@AnchorId AND AccountId=@accountKey AND BootId=@BootId AND InvalidatedAt IS NULL
          AND @Ordinal>LastOrdinal AND @Elapsed>=LastElapsedMilliseconds AND @Elapsed>=0
          AND @RecordedAt>=RecordedTimeFloorAt)
        THROW 51112, 'Proof is unavailable or already consumed.', 1;
    IF @IsInternal=1 AND (@AnchorId IS NOT NULL OR @Ordinal IS NOT NULL OR @Elapsed IS NOT NULL OR @BootId IS NOT NULL)
        THROW 51112, 'Internal reconciliation cannot consume a client proof.', 1;
    IF @AnchorId IS NULL AND (@Ordinal IS NOT NULL OR @Elapsed IS NOT NULL OR @BootId IS NOT NULL OR (@IsInternal=0 AND @RecordedAt<@last))
        THROW 51112, 'Unanchored command cannot precede committed history.', 1;
    IF (SELECT COUNT_BIG(*) FROM @Account)<>1 OR EXISTS(SELECT 1 FROM @Account
        WHERE Id<>@accountKey OR IdentityUserId<>@IdentityUserId OR MutationVersion<>@version+1
          OR ProjectionVersion<>@version+1 OR LastRecordedAt<>@ProjectionAt
          OR (HasPendingReconciliation=0 AND ProjectionAsOfAt<>@ProjectionAt)
          OR (HasPendingReconciliation=1 AND (ProjectionAsOfAt>@ProjectionAt OR ProjectionAsOfAt>(SELECT ProjectionAsOfAt FROM [pocketquests].[Account] WHERE Id=@accountKey))))
        THROW 51200, 'Account projection and mutation versions disagree.', 1;
    IF (SELECT COUNT_BIG(*) FROM @QuestCommandHistory)<>1 OR EXISTS(SELECT 1 FROM @QuestCommandHistory
        WHERE Id<>@OperationId OR AccountMutationVersion<>@version+1
          OR (@IsInternal=0 AND (CommandReceiptId IS NULL OR CommandReceiptId<>@OperationId))
          OR (@IsInternal=1 AND CommandReceiptId IS NOT NULL)
          OR ActionCode<>@Action OR RecordedAt<>@RecordedAt OR ProjectionAt<>@ProjectionAt OR RulesetVersion<>'1.0')
        THROW 51201, 'Exactly one matching typed command history row is required.', 1;
    IF EXISTS(SELECT 1 FROM @Account WHERE [Id]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @CustomSkill WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinition WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionRevision WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionAttributeAllocation WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionSkillAllocation WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestSeries WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestSeriesRevision WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestOccurrence WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestOccurrenceRevision WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestOccurrenceEvent WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCompletion WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @AccountPause WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @TimeZoneChange WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @SkillAssessment WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCommandHistory WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCommandInterest WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @AccountInterest WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @XpLedgerEntry WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @XpBalance WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @CategoryProgress WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    IF EXISTS(SELECT 1 FROM @AccountEntitlement WHERE [AccountId]<>@accountKey) THROW 51204, 'Mutation includes another account.', 1;
    -- Incoming source rows are deltas. They may never rewrite an existing immutable fact.
    IF EXISTS(SELECT 1 FROM @Account s JOIN [pocketquests].[Account] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[IdentityUserId],s.[SelectedBadgeKind],s.[SelectedFrameKind],s.[CreatedAt] EXCEPT SELECT t.[IdentityUserId],t.[SelectedBadgeKind],t.[SelectedFrameKind],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: Account.', 1;
    IF EXISTS(SELECT 1 FROM @CustomSkill s JOIN [pocketquests].[CustomSkill] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[NameNormalizationVersion],s.[CreatedAt],s.[CreationOrdinal],s.[ClientKey] EXCEPT SELECT t.[AccountId],t.[NameNormalizationVersion],t.[CreatedAt],t.[CreationOrdinal],t.[ClientKey])) THROW 51205, 'Immutable source fields cannot change: CustomSkill.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinition s JOIN [pocketquests].[QuestDefinition] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[SystemQuestId],s.[CreatedAt],s.[CreationOrdinal],s.[ClientKey] EXCEPT SELECT t.[AccountId],t.[SystemQuestId],t.[CreatedAt],t.[CreationOrdinal],t.[ClientKey])) THROW 51205, 'Immutable source fields cannot change: QuestDefinition.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionRevision s JOIN [pocketquests].[QuestDefinitionRevision] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestDefinitionId],s.[Revision],s.[Title],s.[Criterion],s.[Description],s.[CategoryId],s.[RankCode],s.[EffortCode],s.[BaseXp],s.[PenaltyPercent],s.[RulesetVersion],s.[DisplaySnapshotVersion],s.[DisplaySnapshotJson],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt] EXCEPT SELECT t.[AccountId],t.[QuestDefinitionId],t.[Revision],t.[Title],t.[Criterion],t.[Description],t.[CategoryId],t.[RankCode],t.[EffortCode],t.[BaseXp],t.[PenaltyPercent],t.[RulesetVersion],t.[DisplaySnapshotVersion],t.[DisplaySnapshotJson],t.[EffectiveAt],t.[CommandReceiptId],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: QuestDefinitionRevision.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionAttributeAllocation s JOIN [pocketquests].[QuestDefinitionAttributeAllocation] t ON t.[AccountId]=s.[AccountId] AND t.[QuestDefinitionRevisionId]=s.[QuestDefinitionRevisionId] AND t.[AttributeId]=s.[AttributeId] WHERE EXISTS(SELECT s.[BasisPoints],s.[CreatedAt],s.[Position] EXCEPT SELECT t.[BasisPoints],t.[CreatedAt],t.[Position])) THROW 51205, 'Immutable source fields cannot change: QuestDefinitionAttributeAllocation.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionSkillAllocation s JOIN [pocketquests].[QuestDefinitionSkillAllocation] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestDefinitionRevisionId],s.[SystemSkillId],s.[CustomSkillId],s.[BasisPoints],s.[CreatedAt],s.[Position] EXCEPT SELECT t.[AccountId],t.[QuestDefinitionRevisionId],t.[SystemSkillId],t.[CustomSkillId],t.[BasisPoints],t.[CreatedAt],t.[Position])) THROW 51205, 'Immutable source fields cannot change: QuestDefinitionSkillAllocation.', 1;
    IF EXISTS(SELECT 1 FROM @QuestSeries s JOIN [pocketquests].[QuestSeries] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[CreatedAt],s.[CreationOrdinal] EXCEPT SELECT t.[AccountId],t.[CreatedAt],t.[CreationOrdinal])) THROW 51205, 'Immutable source fields cannot change: QuestSeries.', 1;
    IF EXISTS(SELECT 1 FROM @QuestSeriesRevision s JOIN [pocketquests].[QuestSeriesRevision] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestSeriesId],s.[Revision],s.[QuestDefinitionRevisionId],s.[CadenceCode],s.[Interval],s.[AnchorOn],s.[PlannedTime],s.[HasAutoAcceptPenalty],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt],s.[ScheduleVersion] EXCEPT SELECT t.[AccountId],t.[QuestSeriesId],t.[Revision],t.[QuestDefinitionRevisionId],t.[CadenceCode],t.[Interval],t.[AnchorOn],t.[PlannedTime],t.[HasAutoAcceptPenalty],t.[EffectiveAt],t.[CommandReceiptId],t.[CreatedAt],t.[ScheduleVersion])) THROW 51205, 'Immutable source fields cannot change: QuestSeriesRevision.', 1;
    IF EXISTS(SELECT 1 FROM @QuestOccurrence s JOIN [pocketquests].[QuestOccurrence] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestDefinitionId],s.[QuestSeriesId],s.[QuestSeriesRevisionId],s.[SeriesSequence],s.[SourceSyncAnchorId],s.[CreatedAt],s.[OriginatedAt],s.[CreationOrdinal],s.[OriginatedOffsetMinutes] EXCEPT SELECT t.[AccountId],t.[QuestDefinitionId],t.[QuestSeriesId],t.[QuestSeriesRevisionId],t.[SeriesSequence],t.[SourceSyncAnchorId],t.[CreatedAt],t.[OriginatedAt],t.[CreationOrdinal],t.[OriginatedOffsetMinutes])) THROW 51205, 'Immutable source fields cannot change: QuestOccurrence.', 1;
    IF EXISTS(SELECT 1 FROM @QuestOccurrenceRevision s JOIN [pocketquests].[QuestOccurrenceRevision] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestOccurrenceId],s.[Revision],s.[QuestDefinitionId],s.[QuestDefinitionRevisionId],s.[CategoryId],s.[DueOn],s.[PlannedTime],s.[DeadlineAt],s.[DeadlineTimeZoneId],s.[StateCode],s.[AcceptedAt],s.[FrozenAt],s.[IsIndividuallyFrozen],s.[AbandonedAt],s.[LockedLoss],s.[LossCategoryId],s.[AccountMutationVersion],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt],s.[OriginatedAt],s.[OriginatedOffsetMinutes] EXCEPT SELECT t.[AccountId],t.[QuestOccurrenceId],t.[Revision],t.[QuestDefinitionId],t.[QuestDefinitionRevisionId],t.[CategoryId],t.[DueOn],t.[PlannedTime],t.[DeadlineAt],t.[DeadlineTimeZoneId],t.[StateCode],t.[AcceptedAt],t.[FrozenAt],t.[IsIndividuallyFrozen],t.[AbandonedAt],t.[LockedLoss],t.[LossCategoryId],t.[AccountMutationVersion],t.[EffectiveAt],t.[CommandReceiptId],t.[CreatedAt],t.[OriginatedAt],t.[OriginatedOffsetMinutes])) THROW 51205, 'Immutable source fields cannot change: QuestOccurrenceRevision.', 1;
    IF EXISTS(SELECT 1 FROM @QuestOccurrenceEvent s JOIN [pocketquests].[QuestOccurrenceEvent] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestOccurrenceId],s.[QuestOccurrenceRevisionId],s.[EventCode],s.[EffectiveAt],s.[AccountMutationVersion],s.[CommandReceiptId],s.[CreatedAt] EXCEPT SELECT t.[AccountId],t.[QuestOccurrenceId],t.[QuestOccurrenceRevisionId],t.[EventCode],t.[EffectiveAt],t.[AccountMutationVersion],t.[CommandReceiptId],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: QuestOccurrenceEvent.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCompletion s JOIN [pocketquests].[QuestCompletion] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[QuestOccurrenceId],s.[QuestOccurrenceRevisionId],s.[RecordedAt],s.[CreatedAt] EXCEPT SELECT t.[AccountId],t.[QuestOccurrenceId],t.[QuestOccurrenceRevisionId],t.[RecordedAt],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: QuestCompletion.', 1;
    IF EXISTS(SELECT 1 FROM @AccountPause s JOIN [pocketquests].[AccountPause] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[ScopeCode],s.[CategoryId],s.[StartedAt],s.[CommandReceiptId],s.[CreatedAt],s.[CreationOrdinal] EXCEPT SELECT t.[AccountId],t.[ScopeCode],t.[CategoryId],t.[StartedAt],t.[CommandReceiptId],t.[CreatedAt],t.[CreationOrdinal])) THROW 51205, 'Immutable source fields cannot change: AccountPause.', 1;
    IF EXISTS(SELECT 1 FROM @TimeZoneChange s JOIN [pocketquests].[TimeZoneChange] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[FromTimeZoneId],s.[ToTimeZoneId],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt] EXCEPT SELECT t.[AccountId],t.[FromTimeZoneId],t.[ToTimeZoneId],t.[EffectiveAt],t.[CommandReceiptId],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: TimeZoneChange.', 1;
    IF EXISTS(SELECT 1 FROM @SkillAssessment s JOIN [pocketquests].[SkillAssessment] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[SystemSkillId],s.[CustomSkillId],s.[ExperienceCode],s.[SeedXp],s.[RulesetVersion],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt] EXCEPT SELECT t.[AccountId],t.[SystemSkillId],t.[CustomSkillId],t.[ExperienceCode],t.[SeedXp],t.[RulesetVersion],t.[EffectiveAt],t.[CommandReceiptId],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: SkillAssessment.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCommandHistory s JOIN [pocketquests].[QuestCommandHistory] t ON t.[Id]=s.[Id] WHERE EXISTS(SELECT s.[AccountId],s.[CommandReceiptId],s.[AccountMutationVersion],s.[ActionCode],s.[RulesetVersion],s.[TimeZoneBefore],s.[ReconciledAt],s.[RecordedAt],s.[ProjectionAt],s.[QuestOccurrenceId],s.[QuestCompletionId],s.[QuestDefinitionRevisionId],s.[CompletionTermsRevisionId],s.[ExpectedRevision],s.[SystemSkillId],s.[CustomSkillId],s.[SkillName],s.[ExperienceCode],s.[DueOn],s.[PlannedTime],s.[ParentQuestOccurrenceId],s.[ProfileRewardId],s.[QuestSeriesId],s.[CadenceCode],s.[Interval],s.[CategoryId],s.[ConfirmPenalty],s.[AcceptedLoss],s.[HasAcceptedTerms],s.[NewTimeZone],s.[ExpectedTimeZone],s.[ConfirmZoneChange],s.[HasExpiryWarnings],s.[SourceSyncAnchorId],s.[CreatedAt],s.[ReconciliationLimit],s.[ActionReconciliationLimit] EXCEPT SELECT t.[AccountId],t.[CommandReceiptId],t.[AccountMutationVersion],t.[ActionCode],t.[RulesetVersion],t.[TimeZoneBefore],t.[ReconciledAt],t.[RecordedAt],t.[ProjectionAt],t.[QuestOccurrenceId],t.[QuestCompletionId],t.[QuestDefinitionRevisionId],t.[CompletionTermsRevisionId],t.[ExpectedRevision],t.[SystemSkillId],t.[CustomSkillId],t.[SkillName],t.[ExperienceCode],t.[DueOn],t.[PlannedTime],t.[ParentQuestOccurrenceId],t.[ProfileRewardId],t.[QuestSeriesId],t.[CadenceCode],t.[Interval],t.[CategoryId],t.[ConfirmPenalty],t.[AcceptedLoss],t.[HasAcceptedTerms],t.[NewTimeZone],t.[ExpectedTimeZone],t.[ConfirmZoneChange],t.[HasExpiryWarnings],t.[SourceSyncAnchorId],t.[CreatedAt],t.[ReconciliationLimit],t.[ActionReconciliationLimit])) THROW 51205, 'Immutable source fields cannot change: QuestCommandHistory.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCommandInterest s JOIN [pocketquests].[QuestCommandInterest] t ON t.[AccountId]=s.[AccountId] AND t.[QuestCommandHistoryId]=s.[QuestCommandHistoryId] AND t.[CategoryId]=s.[CategoryId] WHERE EXISTS(SELECT s.[Position],s.[CreatedAt] EXCEPT SELECT t.[Position],t.[CreatedAt])) THROW 51205, 'Immutable source fields cannot change: QuestCommandInterest.', 1;
    IF EXISTS(SELECT 1 FROM @QuestSeries s JOIN [pocketquests].[QuestSeries] t ON t.AccountId=s.AccountId AND t.Id=s.Id
        WHERE s.QuestDefinitionId<>t.QuestDefinitionId AND (@Action<>'save-series' OR @IsInternal<>0 OR s.Revision<=t.Revision
          OR NOT EXISTS(SELECT 1 FROM @QuestSeriesRevision r
            JOIN (SELECT Id,AccountId,QuestDefinitionId FROM @QuestDefinitionRevision
                  UNION ALL SELECT Id,AccountId,QuestDefinitionId FROM [pocketquests].[QuestDefinitionRevision] WHERE AccountId=@accountKey) d
              ON d.AccountId=r.AccountId AND d.Id=r.QuestDefinitionRevisionId
            WHERE r.AccountId=s.AccountId AND r.QuestSeriesId=s.Id AND r.Revision=s.Revision AND d.QuestDefinitionId=s.QuestDefinitionId)))
        THROW 51206, 'Series quest changes require a new owned configuration from save-series.', 1;
    IF EXISTS(SELECT 1 FROM @QuestCompletion s JOIN [pocketquests].[QuestCompletion] t ON t.AccountId=s.AccountId AND t.Id=s.Id
        WHERE t.UndoneAt IS NOT NULL AND (s.UndoneAt IS NULL OR s.UndoneAt<>t.UndoneAt OR s.UndoQuestOccurrenceEventId<>t.UndoQuestOccurrenceEventId))
        THROW 51202, 'Undo annotation is write-once.', 1;
    IF EXISTS(SELECT 1 FROM @QuestDefinitionAttributeAllocation GROUP BY QuestDefinitionRevisionId HAVING SUM(CONVERT(bigint,BasisPoints))<>10000)
       OR EXISTS(SELECT 1 FROM @QuestDefinitionSkillAllocation GROUP BY QuestDefinitionRevisionId HAVING SUM(CONVERT(bigint,BasisPoints))<>10000)
        THROW 51113, 'Each nonempty allocation pool must total 10000.', 1;
    IF EXISTS(SELECT 1 FROM @CustomSkill s JOIN [pocketquests].[Skill] t ON s.NormalizedName=t.NormalizedName)
        THROW 51203, 'Custom skill name conflicts with a public skill.', 1;
    IF @IsInternal=0
      INSERT [pocketquests].[CommandReceipt]
        (Id,AccountId,CommandType,ApiVersion,PayloadDigest,DigestVersion,OutcomeVersion,OutcomeJson,AppliedMutationVersion,CreatedAt)
        VALUES(@OperationId,@accountKey,@Action,1,@Digest,1,2,@Outcome,@version+1,@Now);
    UPDATE t SET [TimeZoneId]=s.[TimeZoneId],[IsOnboardingComplete]=s.[IsOnboardingComplete],[HasExpiryWarnings]=s.[HasExpiryWarnings],[IsAccountPaused]=s.[IsAccountPaused],[SelectedBadgeId]=s.[SelectedBadgeId],[SelectedFrameId]=s.[SelectedFrameId],[LastRecordedAt]=s.[LastRecordedAt],[MutationVersion]=s.[MutationVersion],[ProjectionVersion]=s.[ProjectionVersion],[ProjectionAsOfAt]=s.[ProjectionAsOfAt],[ModifiedAt]=s.[ModifiedAt],[HasPendingReconciliation]=s.[HasPendingReconciliation] FROM [pocketquests].[Account] t JOIN @Account s ON t.[Id]=s.[Id];
    UPDATE t SET [Name]=s.[Name],[NormalizedName]=s.[NormalizedName],[Revision]=s.[Revision],[ArchivedAt]=s.[ArchivedAt],[ModifiedAt]=s.[ModifiedAt] FROM [pocketquests].[CustomSkill] t JOIN @CustomSkill s ON t.[Id]=s.[Id];
    INSERT [pocketquests].[CustomSkill] ([Id],[AccountId],[Name],[NormalizedName],[NameNormalizationVersion],[Revision],[ArchivedAt],[CreatedAt],[ModifiedAt],[CreationOrdinal],[ClientKey])
        SELECT s.[Id],s.[AccountId],s.[Name],s.[NormalizedName],s.[NameNormalizationVersion],s.[Revision],s.[ArchivedAt],s.[CreatedAt],s.[ModifiedAt],s.[CreationOrdinal],s.[ClientKey] FROM @CustomSkill s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[CustomSkill] t WHERE t.[Id]=s.[Id]);
    UPDATE t SET [Revision]=s.[Revision],[ArchivedAt]=s.[ArchivedAt],[ModifiedAt]=s.[ModifiedAt] FROM [pocketquests].[QuestDefinition] t JOIN @QuestDefinition s ON t.[Id]=s.[Id];
    INSERT [pocketquests].[QuestDefinition] ([Id],[AccountId],[SystemQuestId],[Revision],[ArchivedAt],[CreatedAt],[ModifiedAt],[CreationOrdinal],[ClientKey])
        SELECT s.[Id],s.[AccountId],s.[SystemQuestId],s.[Revision],s.[ArchivedAt],s.[CreatedAt],s.[ModifiedAt],s.[CreationOrdinal],s.[ClientKey] FROM @QuestDefinition s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestDefinition] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestDefinitionRevision] ([Id],[AccountId],[QuestDefinitionId],[Revision],[Title],[Criterion],[Description],[CategoryId],[RankCode],[EffortCode],[BaseXp],[PenaltyPercent],[RulesetVersion],[DisplaySnapshotVersion],[DisplaySnapshotJson],[EffectiveAt],[CommandReceiptId],[CreatedAt])
        SELECT s.[Id],s.[AccountId],s.[QuestDefinitionId],s.[Revision],s.[Title],s.[Criterion],s.[Description],s.[CategoryId],s.[RankCode],s.[EffortCode],s.[BaseXp],s.[PenaltyPercent],s.[RulesetVersion],s.[DisplaySnapshotVersion],s.[DisplaySnapshotJson],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt] FROM @QuestDefinitionRevision s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestDefinitionRevision] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestDefinitionAttributeAllocation] ([AccountId],[QuestDefinitionRevisionId],[AttributeId],[BasisPoints],[CreatedAt],[Position])
        SELECT s.[AccountId],s.[QuestDefinitionRevisionId],s.[AttributeId],s.[BasisPoints],s.[CreatedAt],s.[Position] FROM @QuestDefinitionAttributeAllocation s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestDefinitionAttributeAllocation] t WHERE t.[AccountId]=s.[AccountId] AND t.[QuestDefinitionRevisionId]=s.[QuestDefinitionRevisionId] AND t.[AttributeId]=s.[AttributeId]);
    INSERT [pocketquests].[QuestDefinitionSkillAllocation] ([Id],[AccountId],[QuestDefinitionRevisionId],[SystemSkillId],[CustomSkillId],[BasisPoints],[CreatedAt],[Position])
        SELECT s.[Id],s.[AccountId],s.[QuestDefinitionRevisionId],s.[SystemSkillId],s.[CustomSkillId],s.[BasisPoints],s.[CreatedAt],s.[Position] FROM @QuestDefinitionSkillAllocation s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestDefinitionSkillAllocation] t WHERE t.[Id]=s.[Id]);
    UPDATE t SET [QuestDefinitionId]=s.[QuestDefinitionId],[Revision]=s.[Revision],[NextSequence]=s.[NextSequence],[PauseDays]=s.[PauseDays],[NextDeliveryOn]=s.[NextDeliveryOn],[StoppedAt]=s.[StoppedAt],[ModifiedAt]=s.[ModifiedAt] FROM [pocketquests].[QuestSeries] t JOIN @QuestSeries s ON t.[Id]=s.[Id];
    INSERT [pocketquests].[QuestSeries] ([Id],[AccountId],[QuestDefinitionId],[Revision],[NextSequence],[PauseDays],[NextDeliveryOn],[StoppedAt],[CreatedAt],[ModifiedAt],[CreationOrdinal])
        SELECT s.[Id],s.[AccountId],s.[QuestDefinitionId],s.[Revision],s.[NextSequence],s.[PauseDays],s.[NextDeliveryOn],s.[StoppedAt],s.[CreatedAt],s.[ModifiedAt],s.[CreationOrdinal] FROM @QuestSeries s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestSeries] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestSeriesRevision] ([Id],[AccountId],[QuestSeriesId],[Revision],[QuestDefinitionRevisionId],[CadenceCode],[Interval],[AnchorOn],[PlannedTime],[HasAutoAcceptPenalty],[EffectiveAt],[CommandReceiptId],[CreatedAt],[ScheduleVersion])
        SELECT s.[Id],s.[AccountId],s.[QuestSeriesId],s.[Revision],s.[QuestDefinitionRevisionId],s.[CadenceCode],s.[Interval],s.[AnchorOn],s.[PlannedTime],s.[HasAutoAcceptPenalty],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt],s.[ScheduleVersion] FROM @QuestSeriesRevision s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestSeriesRevision] t WHERE t.[Id]=s.[Id]);
    UPDATE t SET [QuestDefinitionRevisionId]=s.[QuestDefinitionRevisionId],[CategoryId]=s.[CategoryId],[DueOn]=s.[DueOn],[PlannedTime]=s.[PlannedTime],[DeadlineAt]=s.[DeadlineAt],[DeadlineTimeZoneId]=s.[DeadlineTimeZoneId],[StateCode]=s.[StateCode],[AcceptedAt]=s.[AcceptedAt],[FrozenAt]=s.[FrozenAt],[IsIndividuallyFrozen]=s.[IsIndividuallyFrozen],[AbandonedAt]=s.[AbandonedAt],[LockedLoss]=s.[LockedLoss],[LossCategoryId]=s.[LossCategoryId],[Revision]=s.[Revision],[ParentQuestOccurrenceId]=s.[ParentQuestOccurrenceId],[ModifiedAt]=s.[ModifiedAt] FROM [pocketquests].[QuestOccurrence] t JOIN @QuestOccurrence s ON t.[Id]=s.[Id];
    INSERT [pocketquests].[QuestOccurrence] ([Id],[AccountId],[QuestDefinitionId],[QuestDefinitionRevisionId],[CategoryId],[DueOn],[PlannedTime],[DeadlineAt],[DeadlineTimeZoneId],[StateCode],[AcceptedAt],[FrozenAt],[IsIndividuallyFrozen],[AbandonedAt],[LockedLoss],[LossCategoryId],[Revision],[QuestSeriesId],[QuestSeriesRevisionId],[SeriesSequence],[ParentQuestOccurrenceId],[SourceSyncAnchorId],[CreatedAt],[ModifiedAt],[OriginatedAt],[CreationOrdinal],[OriginatedOffsetMinutes])
        SELECT s.[Id],s.[AccountId],s.[QuestDefinitionId],s.[QuestDefinitionRevisionId],s.[CategoryId],s.[DueOn],s.[PlannedTime],s.[DeadlineAt],s.[DeadlineTimeZoneId],s.[StateCode],s.[AcceptedAt],s.[FrozenAt],s.[IsIndividuallyFrozen],s.[AbandonedAt],s.[LockedLoss],s.[LossCategoryId],s.[Revision],s.[QuestSeriesId],s.[QuestSeriesRevisionId],s.[SeriesSequence],s.[ParentQuestOccurrenceId],s.[SourceSyncAnchorId],s.[CreatedAt],s.[ModifiedAt],s.[OriginatedAt],s.[CreationOrdinal],s.[OriginatedOffsetMinutes] FROM @QuestOccurrence s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestOccurrence] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestOccurrenceRevision] ([Id],[AccountId],[QuestOccurrenceId],[Revision],[QuestDefinitionId],[QuestDefinitionRevisionId],[CategoryId],[DueOn],[PlannedTime],[DeadlineAt],[DeadlineTimeZoneId],[StateCode],[AcceptedAt],[FrozenAt],[IsIndividuallyFrozen],[AbandonedAt],[LockedLoss],[LossCategoryId],[AccountMutationVersion],[EffectiveAt],[CommandReceiptId],[CreatedAt],[OriginatedAt],[OriginatedOffsetMinutes])
        SELECT s.[Id],s.[AccountId],s.[QuestOccurrenceId],s.[Revision],s.[QuestDefinitionId],s.[QuestDefinitionRevisionId],s.[CategoryId],s.[DueOn],s.[PlannedTime],s.[DeadlineAt],s.[DeadlineTimeZoneId],s.[StateCode],s.[AcceptedAt],s.[FrozenAt],s.[IsIndividuallyFrozen],s.[AbandonedAt],s.[LockedLoss],s.[LossCategoryId],s.[AccountMutationVersion],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt],s.[OriginatedAt],s.[OriginatedOffsetMinutes] FROM @QuestOccurrenceRevision s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestOccurrenceRevision] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestOccurrenceEvent] ([Id],[AccountId],[QuestOccurrenceId],[QuestOccurrenceRevisionId],[EventCode],[EffectiveAt],[AccountMutationVersion],[CommandReceiptId],[CreatedAt])
        SELECT s.[Id],s.[AccountId],s.[QuestOccurrenceId],s.[QuestOccurrenceRevisionId],s.[EventCode],s.[EffectiveAt],s.[AccountMutationVersion],s.[CommandReceiptId],s.[CreatedAt] FROM @QuestOccurrenceEvent s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestOccurrenceEvent] t WHERE t.[Id]=s.[Id]);
    UPDATE t SET [UndoneAt]=s.[UndoneAt],[UndoQuestOccurrenceEventId]=s.[UndoQuestOccurrenceEventId],[ModifiedAt]=s.[ModifiedAt] FROM [pocketquests].[QuestCompletion] t JOIN @QuestCompletion s ON t.[Id]=s.[Id];
    INSERT [pocketquests].[QuestCompletion] ([Id],[AccountId],[QuestOccurrenceId],[QuestOccurrenceRevisionId],[RecordedAt],[UndoneAt],[UndoQuestOccurrenceEventId],[CreatedAt],[ModifiedAt])
        SELECT s.[Id],s.[AccountId],s.[QuestOccurrenceId],s.[QuestOccurrenceRevisionId],s.[RecordedAt],s.[UndoneAt],s.[UndoQuestOccurrenceEventId],s.[CreatedAt],s.[ModifiedAt] FROM @QuestCompletion s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestCompletion] t WHERE t.[Id]=s.[Id]);
    UPDATE t SET [EndedAt]=s.[EndedAt],[ModifiedAt]=s.[ModifiedAt] FROM [pocketquests].[AccountPause] t JOIN @AccountPause s ON t.[Id]=s.[Id];
    INSERT [pocketquests].[AccountPause] ([Id],[AccountId],[ScopeCode],[CategoryId],[StartedAt],[EndedAt],[CommandReceiptId],[CreatedAt],[ModifiedAt],[CreationOrdinal])
        SELECT s.[Id],s.[AccountId],s.[ScopeCode],s.[CategoryId],s.[StartedAt],s.[EndedAt],s.[CommandReceiptId],s.[CreatedAt],s.[ModifiedAt],s.[CreationOrdinal] FROM @AccountPause s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[AccountPause] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[TimeZoneChange] ([Id],[AccountId],[FromTimeZoneId],[ToTimeZoneId],[EffectiveAt],[CommandReceiptId],[CreatedAt])
        SELECT s.[Id],s.[AccountId],s.[FromTimeZoneId],s.[ToTimeZoneId],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt] FROM @TimeZoneChange s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[TimeZoneChange] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[SkillAssessment] ([Id],[AccountId],[SystemSkillId],[CustomSkillId],[ExperienceCode],[SeedXp],[RulesetVersion],[EffectiveAt],[CommandReceiptId],[CreatedAt])
        SELECT s.[Id],s.[AccountId],s.[SystemSkillId],s.[CustomSkillId],s.[ExperienceCode],s.[SeedXp],s.[RulesetVersion],s.[EffectiveAt],s.[CommandReceiptId],s.[CreatedAt] FROM @SkillAssessment s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[SkillAssessment] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestCommandHistory] ([Id],[AccountId],[CommandReceiptId],[AccountMutationVersion],[ActionCode],[RulesetVersion],[TimeZoneBefore],[ReconciledAt],[RecordedAt],[ProjectionAt],[QuestOccurrenceId],[QuestCompletionId],[QuestDefinitionRevisionId],[CompletionTermsRevisionId],[ExpectedRevision],[SystemSkillId],[CustomSkillId],[SkillName],[ExperienceCode],[DueOn],[PlannedTime],[ParentQuestOccurrenceId],[ProfileRewardId],[QuestSeriesId],[CadenceCode],[Interval],[CategoryId],[ConfirmPenalty],[AcceptedLoss],[HasAcceptedTerms],[NewTimeZone],[ExpectedTimeZone],[ConfirmZoneChange],[HasExpiryWarnings],[SourceSyncAnchorId],[CreatedAt],[ReconciliationLimit],[ActionReconciliationLimit])
        SELECT s.[Id],s.[AccountId],s.[CommandReceiptId],s.[AccountMutationVersion],s.[ActionCode],s.[RulesetVersion],s.[TimeZoneBefore],s.[ReconciledAt],s.[RecordedAt],s.[ProjectionAt],s.[QuestOccurrenceId],s.[QuestCompletionId],s.[QuestDefinitionRevisionId],s.[CompletionTermsRevisionId],s.[ExpectedRevision],s.[SystemSkillId],s.[CustomSkillId],s.[SkillName],s.[ExperienceCode],s.[DueOn],s.[PlannedTime],s.[ParentQuestOccurrenceId],s.[ProfileRewardId],s.[QuestSeriesId],s.[CadenceCode],s.[Interval],s.[CategoryId],s.[ConfirmPenalty],s.[AcceptedLoss],s.[HasAcceptedTerms],s.[NewTimeZone],s.[ExpectedTimeZone],s.[ConfirmZoneChange],s.[HasExpiryWarnings],s.[SourceSyncAnchorId],s.[CreatedAt],s.[ReconciliationLimit],s.[ActionReconciliationLimit] FROM @QuestCommandHistory s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestCommandHistory] t WHERE t.[Id]=s.[Id]);
    INSERT [pocketquests].[QuestCommandInterest] ([AccountId],[QuestCommandHistoryId],[CategoryId],[Position],[CreatedAt])
        SELECT s.[AccountId],s.[QuestCommandHistoryId],s.[CategoryId],s.[Position],s.[CreatedAt] FROM @QuestCommandInterest s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[QuestCommandInterest] t WHERE t.[AccountId]=s.[AccountId] AND t.[QuestCommandHistoryId]=s.[QuestCommandHistoryId] AND t.[CategoryId]=s.[CategoryId]);
    DELETE FROM [pocketquests].[AccountInterest] WHERE AccountId=@accountKey;
    INSERT [pocketquests].[AccountInterest] ([AccountId],[CategoryId],[CreatedAt],[Position])
        SELECT s.[AccountId],s.[CategoryId],s.[CreatedAt],s.[Position] FROM @AccountInterest s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[AccountInterest] t WHERE t.[AccountId]=s.[AccountId] AND t.[CategoryId]=s.[CategoryId]);
    DELETE FROM [pocketquests].[XpLedgerEntry] WHERE AccountId=@accountKey;
    INSERT [pocketquests].[XpLedgerEntry] ([Id],[AccountId],[QuestOccurrenceEventId],[ContributionCode],[TrackCode],[CategoryId],[AttributeId],[SystemSkillId],[CustomSkillId],[EffectiveAt],[Amount],[ProjectionVersion],[RulesetVersion],[CreatedAt],[ModifiedAt])
        SELECT s.[Id],s.[AccountId],s.[QuestOccurrenceEventId],s.[ContributionCode],s.[TrackCode],s.[CategoryId],s.[AttributeId],s.[SystemSkillId],s.[CustomSkillId],s.[EffectiveAt],s.[Amount],s.[ProjectionVersion],s.[RulesetVersion],s.[CreatedAt],s.[ModifiedAt] FROM @XpLedgerEntry s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[XpLedgerEntry] t WHERE t.[Id]=s.[Id]);
    DELETE FROM [pocketquests].[XpBalance] WHERE AccountId=@accountKey;
    INSERT [pocketquests].[XpBalance] ([Id],[AccountId],[TrackCode],[CategoryId],[AttributeId],[SystemSkillId],[CustomSkillId],[EarnedXp],[SeedXp],[Level],[ProjectionVersion],[CreatedAt],[ModifiedAt])
        SELECT s.[Id],s.[AccountId],s.[TrackCode],s.[CategoryId],s.[AttributeId],s.[SystemSkillId],s.[CustomSkillId],s.[EarnedXp],s.[SeedXp],s.[Level],s.[ProjectionVersion],s.[CreatedAt],s.[ModifiedAt] FROM @XpBalance s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[XpBalance] t WHERE t.[Id]=s.[Id]);
    DELETE FROM [pocketquests].[CategoryProgress] WHERE AccountId=@accountKey;
    INSERT [pocketquests].[CategoryProgress] ([Id],[AccountId],[CategoryId],[StreakDays],[BonusRatePercent],[HasQualifiedToday],[IsExplicitlyPaused],[AsOfDate],[TimeZoneId],[ProjectionVersion],[CreatedAt],[ModifiedAt])
        SELECT s.[Id],s.[AccountId],s.[CategoryId],s.[StreakDays],s.[BonusRatePercent],s.[HasQualifiedToday],s.[IsExplicitlyPaused],s.[AsOfDate],s.[TimeZoneId],s.[ProjectionVersion],s.[CreatedAt],s.[ModifiedAt] FROM @CategoryProgress s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[CategoryProgress] t WHERE t.[Id]=s.[Id]);
    DELETE FROM [pocketquests].[AccountEntitlement] WHERE AccountId=@accountKey;
    INSERT [pocketquests].[AccountEntitlement] ([Id],[AccountId],[ProfileRewardId],[QualifyingCount],[IsEarned],[ProjectionVersion],[RulesetVersion],[CreatedAt],[ModifiedAt])
        SELECT s.[Id],s.[AccountId],s.[ProfileRewardId],s.[QualifyingCount],s.[IsEarned],s.[ProjectionVersion],s.[RulesetVersion],s.[CreatedAt],s.[ModifiedAt] FROM @AccountEntitlement s WHERE NOT EXISTS(SELECT 1 FROM [pocketquests].[AccountEntitlement] t WHERE t.[Id]=s.[Id]);
    IF @AnchorId IS NOT NULL
        UPDATE [pocketquests].[SyncAnchor] SET LastOrdinal=@Ordinal,LastElapsedMilliseconds=@Elapsed,
            ModifiedAt=CASE WHEN ModifiedAt>@Now THEN ModifiedAt ELSE @Now END
            WHERE AccountId=@accountKey AND Id=@AnchorId;
    IF @IsInternal=0
    BEGIN
      INSERT [dbo].[AuditRecords](Id,OccurredAt,Actor,EventName,Category,Outcome,TargetType,TargetId,TenantId,CorrelationId,Operation,ChangesJson,MetadataJson)
        VALUES(@AuditId,@Now,@IdentityUserId,'pocketquests.quest.'+@Action,@AuditCategory,@AuditOutcome,'quest.account',
            CONVERT(nvarchar(36),@accountKey),@AuditTenant,@AuditCorrelation,@AuditOperation,@AuditChanges,@AuditMetadata);
      INSERT [pocketquests].[AccountAuditRecord](AccountId,AuditRecordId,CreatedAt) VALUES(@accountKey,@AuditId,@Now);
    END;
END;
GO
